<?php
defined( 'ABSPATH' ) || exit;
return array(
	'schemas'   => array(),
	'mock_data' => array(
		'main_banner'         => array(
			'head_text'       => 'Blockchain Development Services',
			'content'         => 'Explore blockchain with our high-quality custom decentralized solutions. TechnBrains blockchain development services offer a variety of decentralized solutions that enhance the security and transparency of your business.',
			'img_src'         => '/next-gen/block-chain/crypto-banner.webp',
			'img_width'       => '691',
			'img_height'      => '794',
			'img_alt'         => 'blockchain-banner',
		),
		'dedicated_lang_desc' => array(
			'para_html' => 'At TechnBrains, we pride ourselves on being at the forefront of blockchain innovation, offering a comprehensive range of <span>Blockchain Development Services</span> to meet your every need. Our team of experienced blockchain developers understands the intricacies of this transformative technology and is committed to creating custom blockchain solutions that drive your business forward. Our blockchain development services help you streamline operations, enhance security, and unlock new revenue streams.<br><br>TechnBrains is a trusted, smart contract development company that focuses on excellence and pushing the boundaries of what\'s possible. We take a meticulous approach to ensure that every smart contract we develop is not only functional but also optimized for performance and reliability. As your reliable blockchain partner, we are here to help you navigate the complexities of this rapidly evolving landscape. We provide guidance and support to assist you in achieving your goals with confidence.',
		),
		'language_services'   => array(
			'head_text' => 'Enhanced Blockchain Development Solutions',
			'para_text' => 'At TechnBrains, we offer Blockchain Development Services that will undoubtedly empower your business. Our expert team provides cutting-edge solutions for smart contract development and blockchain app development, ensuring that you get the most out of your digital presence. With our assistance, you can take your business to new heights and bring your vision to life. Let us help you get the benefits of blockchain technology and achieve success like never before.',
			'btn_text'  => 'Hire Developers NOW!',
			'listing'   => array(
				array(
					'img_src'   => '/next-gen/block-chain/icon-1.webp',
					'width'     => '80',
					'height'    => '80',
					'list_head' => 'Smart Contract Auditing Services',
					'list_para' => 'Our blockchain services include a thorough review of code vulnerabilities, along with advice on how to eliminate them. At TechnBrains, we have extensive knowledge of smart contracts in various programming languages such as Solidity, Vyper, Cairo, Motoko, and Move, and a separate team for Rust audits for platforms like Solana, Near, Secret Network, Aptos, and others.',
				),
				array(
					'img_src'   => '/next-gen/block-chain/icon-2.webp',
					'width'     => '80',
					'height'    => '80',
					'list_head' => 'Technical Due Diligence',
					'list_para' => 'Our smart contract audit services include tech due diligence and a detailed independent inspection by TechnBrains crypto auditors, followed by an assessment of the platform or protocol with a detailed use case.',
				),
				array(
					'img_src'   => '/next-gen/block-chain/icon-3.webp',
					'width'     => '80',
					'height'    => '80',
					'list_head' => 'Blockchain Auditing Services',
					'list_para' => 'A comprehensive analysis of the blockchain ecosystem to identify potential vulnerabilities and weaknesses, with a detailed guide on how to eliminate them.',
				),
				array(
					'img_src'   => '/next-gen/block-chain/icon-4.webp',
					'width'     => '80',
					'height'    => '80',
					'list_head' => 'Enterprise Solutions Audit',
					'list_para' => 'After conducting an in-depth analysis, we will provide feedback on code clarity and consistency and suggest potential enhancements.',
				),
				array(
					'img_src'   => '/next-gen/block-chain/icon-5.webp',
					'width'     => '80',
					'height'    => '80',
					'list_head' => 'Smart Contracts Development',
					'list_para' => 'We are a leading Ethereum smart contract development company that specializes in automating business operations and streamlining workflows through the use of smart contracts. Our team of experienced smart contract developers has extensive knowledge of various smart contract technologies and programming languages. We create secure, immutable, and accurate contracts that ensure a conflict-free business ecosystem.',
				),
				array(
					'img_src'   => '/next-gen/block-chain/icon-6.webp',
					'width'     => '80',
					'height'    => '80',
					'list_head' => 'Custom Blockchain Development',
					'list_para' => 'If you are looking for a custom blockchain application development or software development service company, TechnBrains can help you. We can develop proficient blockchain solutions either from scratch or by revamping existing systems. Our blockchain software developers are highly skilled in building solutions that are both robust and secure and can help you achieve your business goals faster.',
				),
				array(
					'img_src'   => '/next-gen/block-chain/icon-7.webp',
					'width'     => '80',
					'height'    => '80',
					'list_head' => 'dApps Development',
					'list_para' => 'We are a dApp development company that specializes in designing apps to be scalable, secure, and profitable across various industries. With our extensive expertise in creating complex applications of all sizes, we can build custom dApps that give businesses a competitive advantage in the blockchain ecosystem.',
				),
				array(
					'img_src'   => '/next-gen/block-chain/icon-8.webp',
					'width'     => '80',
					'height'    => '80',
					'list_head' => 'Blockchain Wallet App Development',
					'list_para' => 'Our blockchain wallet development services can assist your business in expanding its DeFi portfolio to a wider customer base by providing enhanced security and faster transactions. Our team of skilled blockchain app developers can proficiently build and deploy your crypto wallet with all the essential features that your business requires, such as a QR scanner, biometrics, cross-platform compatibility, and more.',
				),
				array(
					'img_src'   => '/next-gen/block-chain/icon-9.webp',
					'width'     => '80',
					'height'    => '80',
					'list_head' => 'Polygon Development Services',
					'list_para' => 'We are a blockchain development company for enterprises based in the USA. We specialize in helping organizations unleash the full potential of the web3 ecosystem by building their blockchain applications and software on Polygon. Our expertise on Polygon enables us to develop high-performance software, including dApps, blockchain wallets, smart contracts, and NFT marketplaces, that ensure greater interoperability, scalability, robust architecture, and enhanced user experience.',
				),
				array(
					'img_src'   => '/next-gen/block-chain/icon-10.webp',
					'width'     => '80',
					'height'    => '80',
					'list_head' => 'Support Tokenization Platform Development',
					'list_para' => 'As a distinguished consulting service provider, we focus on blockchain technology. Our company delivers comprehensive tokenization solutions to assist businesses in digitizing their financial assets, thereby making them tradable across multiple digital platforms. With our top-notch enterprise-grade asset tokenization platform development services, we enable companies to explore new opportunities for financial growth.',
				),
				array(
					'img_src'   => '/next-gen/block-chain/icon-11.webp',
					'width'     => '80',
					'height'    => '80',
					'list_head' => 'Crypto Exchange Development',
					'list_para' => 'TechnBrains is a cryptocurrency app development company with the goal of assisting your business in constructing a decentralized financial system that is both secure and transparent. Our team of cryptocurrency experts has extensive experience and possesses all the necessary tools to create a dependable and scalable exchange platform. This platform will enable users to buy, sell, or trade cryptocurrencies effortlessly.',
				),
				array(
					'img_src'   => '/next-gen/block-chain/icon-12.webp',
					'width'     => '80',
					'height'    => '80',
					'list_head' => 'IEO and ICO Development',
					'list_para' => 'We are a top-notch cryptocurrency software development company that provides comprehensive IEO and ICO development services. Our team of expert blockchain and crypto developers can assist you in building a complete initial exchange offering platform that has the potential to gather significant funding for your cryptocurrency business.',
				),
			),
		),
		'software_solutions'  => array(
			'main_title' => 'Custom Blockchain Solutions',
			'title'      => 'Tailored Blockchain Solutions for Your Business',
			'para'       => 'At TechnBrains, we specialize in delivering custom blockchain solutions meticulously designed to address your enterprise needs. Renowned as a leading blockchain development company, we prioritize an agile methodology that centers on comprehending your distinct requirements. This enables us to engineer custom solutions that not only meet but exceed your expectations, fostering innovation across your business landscape.',
			'listing'    => array(
				array( 'img_src' => '/next-gen/block-chain/t1.webp',  'img_width' => 48, 'img_height' => 48, 'title' => 'Blockchain-based Supply Chain Management' ),
				array( 'img_src' => '/next-gen/block-chain/t2.webp',  'img_width' => 48, 'img_height' => 48, 'title' => 'Decentralized Finance (DeFi) Solutions' ),
				array( 'img_src' => '/next-gen/block-chain/t3.webp',  'img_width' => 48, 'img_height' => 48, 'title' => 'Tokenization Platforms' ),
				array( 'img_src' => '/next-gen/block-chain/t4.webp',  'img_width' => 48, 'img_height' => 48, 'title' => 'Digital Identity Management Systems' ),
				array( 'img_src' => '/next-gen/block-chain/t5.webp',  'img_width' => 48, 'img_height' => 48, 'title' => 'Blockchain-powered Voting Systems' ),
				array( 'img_src' => '/next-gen/block-chain/t6.webp',  'img_width' => 48, 'img_height' => 48, 'title' => 'Smart Contract Automation Tools' ),
				array( 'img_src' => '/next-gen/block-chain/t7.webp',  'img_width' => 48, 'img_height' => 48, 'title' => 'Immutable Data Storage Solutions' ),
				array( 'img_src' => '/next-gen/block-chain/t8.webp',  'img_width' => 48, 'img_height' => 48, 'title' => 'Decentralized Application (DApp) Development' ),
				array( 'img_src' => '/next-gen/block-chain/t9.webp',  'img_width' => 48, 'img_height' => 48, 'title' => 'Blockchain-enabled IoT Integration' ),
				array( 'img_src' => '/next-gen/block-chain/t10.webp', 'img_width' => 48, 'img_height' => 48, 'title' => 'Cross-border Payment Solutions' ),
			),
		),
		'proposal'            => array(
			'head_html' => '<h2>Partner With TechnBrains For Expert Blockchain Development And Revolutionize Your Business. Build The Future Together With Our Innovative Blockchain Development Services</h2>',
			'btn_text'  => 'Let\'s Build',
			'anchor'    => false,
			'btn_url'   => '',
		),
		'dev_services'        => array(
			'subtitle' => 'Tap into blockchain Excellence',
			'title'    => 'The Benefits Of Partnering With The Best Custom Blockchain App Development Company',
			'para'     => 'Partnering with TechnBrains, the premier Custom Blockchain App Development Company offers a multitude of benefits that elevate your business to new heights. With our comprehensive range of blockchain development services, including blockchain app development services, smart contract development, and blockchain application development solutions, you gain access to cutting-edge technology tailored to your unique needs.',
			'listing'  => array(
				array(
					'img_src' => '/next-gen/block-chain/why-block.webp',
					'width'   => '534',
					'height'  => '600',
					'content' => array(
						array(
							'title' => 'Comprehensive Blockchain Development Services',
							'para'  => '',
						),
						array(
							'title' => '<span>Blockchain App Development Services:</span>',
							'para'  => 'Tailored solutions to meet your specific business requirements.',
						),
						array(
							'title' => '<span>Smart Contract Development:</span>',
							'para'  => 'Harness the power of smart contracts for automated and secure transactions.',
						),
						array(
							'title' => '<span>Blockchain Application Development Solutions:</span>',
							'para'  => 'Innovative applications designed to drive efficiency and scalability.',
						),
						array(
							'title' => 'Expertise in a Trusted Blockchain Development Agency',
							'para'  => '',
						),
						array(
							'title' => '<span>Blockchain Software Development Services:</span>',
							'para'  => 'Access to a team of seasoned experts proficient in blockchain technology.',
						),
						array(
							'title' => '<span>Proven Track Record:</span>',
							'para'  => 'Hundreds of successful projects across various industries and complexity levels.',
						),
						array(
							'title' => '<span>Cutting-edge Solutions:</span>',
							'para'  => 'Stay ahead of the curve with our innovative blockchain development solutions.',
						),
						array(
							'title' => 'Personalized Support and Client-Centric Approach',
							'para'  => '',
						),
						array(
							'title' => '<span>Dedicated Attention:</span>',
							'para'  => 'Your vision is our priority, and we work closely with you to ensure it\'s realized.',
						),
						array(
							'title' => '<span>Continuous Support:</span>',
							'para'  => 'From concept to deployment and beyond, we\'re with you every step of the way.',
						),
						array(
							'title' => '<span>Commitment to Excellence:</span>',
							'para'  => 'Our goal is to exceed your expectations and deliver exceptional results.<br><br>Partner with TechnBrains today and embark on a journey of innovation, efficiency, and success in the realm of blockchain technology.',
						),
					),
				),
			),
		),
		'dev_process'         => array(
			'classes'    => 'gray-bg',
			'main_title' => 'Our Cooperation process',
			'lang_title' => 'Crafting a Trusted Blockchain Development Process',
			'lang_para'  => 'At our esteemed blockchain software development company, boasting nearly a decade of industry expertise, we\'ve honed a meticulous approach to delivering tailored blockchain solutions. With a thorough understanding of diverse project requirements, we embark on a journey that blends innovation with reliability.',
			'listing'    => array(
				array(
					'number'     => '01',
					'width_img'  => '',
					'height_img' => '',
					'title'      => 'Insightful Requirement Gathering',
					'para'       => 'Our journey begins with an immersive brainstorming session, where our seasoned experts meticulously gather project requirements. Through comprehensive analysis, we identify potential risks and devise strategic solutions while presenting innovative ideas to enhance your vision.',
				),
				array(
					'number'     => '02',
					'width_img'  => '',
					'height_img' => '',
					'title'      => 'Blockchain-integrated Solution Design',
					'para'       => 'Smart Contracts: We encode decentralized interactions into smart contracts, facilitating tasks like asset storage and retrieval. Our comprehensive smart contract development services encompass architectural definition, design pattern selection, and modular implementation for seamless execution.',
				),
				array(
					'number'     => '03',
					'width_img'  => '',
					'height_img' => '',
					'title'      => 'Middleware Architecture',
					'para'       => 'Crafting a robust middleware layer is essential for integrating multiple features into blockchain platforms. We design secure and scalable middleware solutions to encapsulate smart contracts, fostering a restful API model for seamless frontend and admin interaction.',
				),
				array(
					'number'     => '04',
					'width_img'  => '',
					'height_img' => '',
					'title'      => 'System Architecture for Component Interaction',
					'para'       => 'We meticulously model interactions between smart contracts, middleware, frontend, and admin layers, ensuring a cohesive system design that optimizes intra and inter-component communication.',
				),
				array(
					'number'     => '05',
					'width_img'  => '',
					'height_img' => '',
					'title'      => 'Technical Documentation',
					'para'       => 'Building comprehensive technical documents is pivotal for effective communication between program blocks. We meticulously outline logic for payments, rewards, and other critical aspects of system design.',
				),
				array(
					'number'     => '06',
					'width_img'  => '',
					'height_img' => '',
					'title'      => 'Smart Contract Development',
					'para'       => 'Building upon the meticulously crafted architecture, our expert team codes smart contracts tailored to your project\'s specifications.',
				),
				array(
					'number'     => '07',
					'width_img'  => '',
					'height_img' => '',
					'title'      => 'UI and Admin Interface Development',
					'para'       => 'Frontend UI: We create intuitive user interfaces enabling seamless transactions, web wallet connections, message transactions to chains, and retrieval of chain and contract information.',
				),
				array(
					'number'     => '08',
					'width_img'  => '',
					'height_img' => '',
					'title'      => 'Admin Interface',
					'para'       => 'Depending on your use case, our admin interface may include features such as transaction analytics, platform fee management, and user administration.',
				),
				array(
					'number'     => '09',
					'width_img'  => '',
					'height_img' => '',
					'title'      => 'Component Integration',
					'para'       => 'Through an iterative process of smart contract development and UI/admin interface development, we seamlessly integrate components to form a cohesive workflow. Our blockchain integration services ensure rigorous testing to guarantee functionality and reliability.',
				),
				array(
					'number'     => '10',
					'width_img'  => '',
					'height_img' => '',
					'title'      => 'UAT and QA on Testnets and Custom Environments',
					'para'       => 'Prior to deployment, our expert blockchain developers conduct comprehensive testing across testnets and custom environments, ensuring the highest standards of quality and user experience.',
				),
				array(
					'number'     => '11',
					'width_img'  => '',
					'height_img' => '',
					'title'      => 'Production Level Deployment',
					'para'       => 'As a trusted blockchain application development company, we adhere to industry-standard protocols for deploying blockchain products across various platforms, ensuring accessibility and usability for your target audience.',
				),
			),
		),
		'stack_new_box'       => array(
			'subtitle' => 'Empower Your Projects with BLOCKCHAIN',
			'title'    => 'Technologies we use for Blockchain Development',
			'para'     => '',
			'listing'  => array(
				array(
					'tab_title' => 'Ethereum-based',
					'data_list' => array(
						array( 'title' => 'Ethereum' ),
						array( 'title' => 'BNB Chain' ),
						array( 'title' => 'Polygon' ),
						array( 'title' => 'NEAR' ),
						array( 'title' => 'Solana' ),
						array( 'title' => 'Avalanche' ),
						array( 'title' => 'Arbitrum' ),
						array( 'title' => 'Optimism' ),
					),
				),
				array(
					'tab_title' => 'Blockchain Platforms',
					'data_list' => array(
						array( 'title' => 'Aurora' ),
						array( 'title' => 'Aptos' ),
						array( 'title' => 'Sui' ),
						array( 'title' => 'Klayth' ),
						array( 'title' => 'Polkadot' ),
						array( 'title' => 'Cosmos' ),
						array( 'title' => 'Secret Network' ),
						array( 'title' => 'StarkNet' ),
					),
				),
				array(
					'tab_title' => 'Backend Programming Languages',
					'data_list' => array(
						array( 'title' => 'C++' ),
						array( 'title' => 'Python' ),
						array( 'title' => 'Rust' ),
						array( 'title' => 'Node.js' ),
						array( 'title' => 'Go' ),
						array( 'title' => 'Solidity' ),
						array( 'title' => 'TypeScript' ),
						array( 'title' => 'JavaScript' ),
					),
				),
				array(
					'tab_title' => 'Backend Tools & Technologies',
					'data_list' => array(
						array( 'title' => 'SQL & NoSQL' ),
						array( 'title' => 'Redis' ),
						array( 'title' => 'Elasticsearch' ),
						array( 'title' => 'Docker' ),
					),
				),
				array(
					'tab_title' => 'Front End',
					'data_list' => array(
						array( 'title' => 'Vue.js' ),
						array( 'title' => 'React.js' ),
						array( 'title' => 'Redux' ),
						array( 'title' => 'Typescript' ),
						array( 'title' => 'Mobx' ),
						array( 'title' => 'RxJS' ),
						array( 'title' => 'GraphQL' ),
						array( 'title' => 'Next.js' ),
					),
				),
				array(
					'tab_title' => 'Mobile',
					'data_list' => array(
						array( 'title' => 'Android: Java, Kotlin' ),
						array( 'title' => 'iOS: Objective-C, Swift' ),
						array( 'title' => 'React Native' ),
					),
				),
			),
		),
		'industries_slider'   => array(
			'subtitle' => 'Using Top Blockchain Development Platforms of 2024',
			'title'    => 'Blockchain Development Platforms',
			'para'     => 'Discover our Ethereum application development services for creating state-of-the-art blockchain solutions. Our team of blockchain developers is skilled in building solutions on various platforms, including Ethereum and Polkadot, based on your business requirements.',
			'listing'  => array(
				array(
					'img_src'   => '/next-gen/block-chain/custom-1.webp',
					'tab_title' => 'Ethereum',
					'content'   => '',
				),
				array(
					'img_src'   => '/next-gen/block-chain/custom-2.webp',
					'tab_title' => 'Hyperledger',
					'content'   => '',
				),
				array(
					'img_src'   => '/next-gen/block-chain/custom-3.webp',
					'tab_title' => 'Corda',
					'content'   => '',
				),
				array(
					'img_src'   => '/next-gen/block-chain/custom-4.webp',
					'tab_title' => 'Eos',
					'content'   => '',
				),
				array(
					'img_src'   => '/next-gen/block-chain/custom-5.webp',
					'tab_title' => 'Stellar',
					'content'   => '',
				),
				array(
					'img_src'   => '/next-gen/block-chain/custom-6.webp',
					'tab_title' => 'Tron',
					'content'   => '',
				),
				array(
					'img_src'   => '/next-gen/block-chain/hedera.webp',
					'tab_title' => 'Hedera',
					'content'   => '',
				),
			),
		),
	),
	'components' => array(
		array( 'name' => 'main-banner',          'modifier_class' => '' ),
		array( 'name' => 'dedicated-lang-desc',  'modifier_class' => '' ),
		array( 'name' => 'language-services',    'modifier_class' => '' ),
		array( 'name' => 'solution-business',    'modifier_class' => '' ),
		array( 'name' => 'proposal',             'modifier_class' => '' ),
		array( 'name' => 'development-services', 'modifier_class' => 'white-bg' ),
		array( 'name' => 'development-process',  'modifier_class' => '' ),
		array( 'name' => 'stack-new-box',        'modifier_class' => '' ),
		array( 'name' => 'platform-slider',      'modifier_class' => '' ),
		array( 'name' => 'testimonials',         'modifier_class' => '' ),
	),
);
