<?php
return array(
	'schemas'   => array(),
	'mock_data' => array(
		'banner' => array(
    'head_text'   => 'Hire Android Developers for Scalable Mobile Apps',
    'para_text'   => 'Hire Android developers from TechnBrains to build secure, responsive, and scalable Android applications for smartphones, tablets, wearables, and Android-powered devices. Our Android developers work with Kotlin, Java, Android Studio, Android SDK, Jetpack, Firebase, REST APIs, third-party integrations, and modern app architecture. Whether you are launching an MVP, expanding an existing app, or modernizing a legacy Android product, we help you hire the right developers or build a complete Android development team.',
    'span_text'   => 'Ready to bring your Android app vision to life? Hire our expert Android developers today!',
    'form_title'  => 'Deploy Android Projects',
    'form_para'   => 'With Top Android Developers we are here to launch your app with a bang!',
    'banner_list' => array(
        array( 'li_list' => 'Extensive knowledge of Android SDK, Kotlin, Android Studio, and Java.' ),
        array( 'li_list' => 'Skilled in Android Framework and Architecture Components.' ),
        array( 'li_list' => 'Strong understanding of External APIs, Web Services, JSON, and XML data.' ),
        array( 'li_list' => 'Android UI/UX Material Design, working with third-party libraries and APIs.' ),
    ),
),
		'freelance'        => array(
			'img_src'    => '/hire/laravel/freelance-banner.png',
			'img_width'  => 512,
			'img_height' => 612,
			'img_alt'    => 'freelance-banner',
			'head_text'  => 'Hire Offshore Android <span>Developers</span>',
			'para_text'  => 'Looking to hire Android developers with proven expertise? Don\'t waste your resources on a senior developer if your project only requires an MVP Android app. At TechnBrains, we offer a diverse pool of remote Android developers with varying levels of experience. We\'ll match your project requirements with the most suitable developers for your project\'s scale and budget. Choose the best Android developers for hire with TechnBrains.<br><br>Our team of skilled Android engineers have extensive experience working on numerous Android projects. This makes Aglowid the perfect choice for hiring Android developers. With our assistance, you can quickly establish a secure, scalable and robust app without sacrificing security or time to market.',
			'head1'      => '10+',
			'para1'      => 'Years of Experience',
			'head2'      => '350+',
			'para2'      => 'Happy Clients',
			'head3'      => '250+',
			'para3'      => 'Experienced Developers',
		),
		'hire_cta_1'       => array(
			'title'              => 'LOOKING TO PARTNER WITH US?',
			'para'               => 'Prepare For a Genuine Business Partnership',
			'primary_button'     => true,
			'secondary_button'   => true,
			'primary_btn_title'  => 'Book a Consultation',
			'primary_btn_popup'  => true,
			'secondary_btn_title'=> 'LET\'S TALK',
		),
		'hire_cta_2'       => array(
			'title'             => 'READY TO START YOUR DREAM PROJECT?',
			'para'              => 'WE HAVE A TEAM TO GET YOU THERE.',
			'primary_button'    => true,
			'secondary_button'  => false,
			'primary_btn_title' => 'GET IN TOUCH',
			'primary_btn_popup' => true,
		),
		'hire_tab' => array(
    'sub_head'  => 'Engagement Models to Hire Android Developers',
    'para_text' => 'Choose the model that matches your internal capacity, delivery needs, and level of control.',
    'tab_list'  => array(
        array(
            'key'       => 'tab-1',
            'label'     => 'Staff Augmentation',
            'title'     => 'Staff Augmentation',
            'tab_heads' => array(
                array( 'text' => 'For Whom',          'texttwo' => 'Businesses and startups with an existing development team that needs Android expertise' ),
                array( 'text' => 'Size of Project',   'texttwo' => 'Small to large' ),
                array( 'text' => 'Requirements',      'texttwo' => 'Partially or fully defined' ),
                array( 'text' => 'Client\'s Control', 'texttwo' => 'Very high' ),
                array( 'text' => 'Flexibility',       'texttwo' => 'High, scale developers up or down based on workload' ),
                array( 'text' => 'When to Choose',    'texttwo' => 'Choose staff augmentation when you need Android developers to join your team, follow your sprint cycle, and work directly with your product managers, designers, backend engineers, and the QA team.' ),
                array( 'text' => 'Rates',             'texttwo' => 'Hourly, part-time, or full-time' ),
            ),
            'src' => '/hire/staff.png', 'width' => 227, 'height' => 180, 'alt' => 'Staff Augmentation',
        ),
        array(
            'key'       => 'tab-2',
            'label'     => 'Software Outsourcing',
            'title'     => 'Software Outsourcing',
            'tab_heads' => array(
                array( 'text' => 'For Whom',          'texttwo' => 'Startups, SMBs, and enterprises that want a managed Android app development experience' ),
                array( 'text' => 'Size of Project',   'texttwo' => 'Small to medium, or clearly scoped enterprise projects' ),
                array( 'text' => 'Requirements',      'texttwo' => 'Clearly defined or ready for discovery' ),
                array( 'text' => 'Client\'s Control', 'texttwo' => 'Medium, with milestone-based visibility' ),
                array( 'text' => 'Flexibility',       'texttwo' => 'Moderate' ),
                array( 'text' => 'When to Choose',    'texttwo' => 'Choose software outsourcing when you want TechnBrains to handle Android app design implementation, development, integrations, QA, deployment, and support while you focus on business priorities.' ),
                array( 'text' => 'Rates',             'texttwo' => 'Fixed-scope or time and material' ),
            ),
            'src' => '/hire/team.png', 'width' => 227, 'height' => 180, 'alt' => 'Software Outsourcing',
        ),
        array(
            'key'       => 'tab-3',
            'label'     => 'Dedicated Teams',
            'title'     => 'Dedicated Teams',
            'tab_heads' => array(
                array( 'text' => 'For Whom',          'texttwo' => 'Businesses building long-term Android products, multi-feature apps, or platform extensions' ),
                array( 'text' => 'Size of Project',   'texttwo' => 'Medium to large' ),
                array( 'text' => 'Requirements',      'texttwo' => 'Evolving roadmap' ),
                array( 'text' => 'Client\'s Control', 'texttwo' => 'High' ),
                array( 'text' => 'Flexibility',       'texttwo' => 'High' ),
                array( 'text' => 'When to Choose',    'texttwo' => 'Choose dedicated teams when you need Android developers, QA engineers, designers, and delivery support working consistently on your product roadmap.' ),
                array( 'text' => 'Rates',             'texttwo' => 'Monthly team-based billing' ),
            ),
            'src' => '/hire/outsourcing.png', 'width' => 227, 'height' => 180, 'alt' => 'Dedicated Teams',
        ),
    ),
),
		'hire_choose' => array(
    'sub_head'    => 'Why Choose Our Android Developers?',
    'para_text'   => 'Hiring our Android developers means tapping into a reservoir of expertise dedicated to crafting exceptional mobile experiences. Our team\'s deep knowledge of Android technologies and a track record of delivering innovative and user-friendly apps ensures your project\'s success. With us, you\'re not just hiring developers; you\'re securing a pathway to Android excellence.',
    'choose_list' => array(
        array( 'src' => '/hire/a-1.png', 'width' => 88, 'height' => 88, 'head' => 'Native Android Apps',              'para' => 'Build secure, fast, and scalable Android apps with Kotlin, Java, Android SDK, and modern architecture patterns.' ),
        array( 'src' => '/hire/a-2.png', 'width' => 88, 'height' => 88, 'head' => 'Android App Modernization',        'para' => 'Improve legacy Android apps with code cleanup, UI updates, API upgrades, performance improvements, and better maintainability.' ),
        array( 'src' => '/hire/a-3.png', 'width' => 88, 'height' => 88, 'head' => 'Android Apps With Firebase',       'para' => 'Add authentication, cloud messaging, analytics, crash reporting, real-time data, and backend functionality with Firebase.' ),
    ),
),
		'hire_table' => array(
    'sub_head'   => 'Why Hire Android Developers From TechnBrains',
    'para_text'  => 'Hiring Android developers from TechnBrains offers a distinct advantage over freelance or in-house developers. Our dedicated team brings years of specialized experience, ensuring your project benefits from their expertise in <a href="/android-app-development/">Android app development</a>. With us, you can count on reliable, collaborative, and streamlined development processes that deliver exceptional results on time and within budget.',
    'table_list' => array(
        array( 'id' => 1,  'hiring' => 'Time to Get Right Developers',          'in_house' => '4 - 12 weeks',      'technbrains' => '1 day - 2 weeks',                          'freelancer' => '1 - 12 weeks' ),
        array( 'id' => 2,  'hiring' => 'Time to Start a Project',               'in_house' => '2 - 10 weeks',      'technbrains' => '1 day - 2 weeks',                          'freelancer' => '1 - 10 weeks' ),
        array( 'id' => 3,  'hiring' => 'Recurring Cost of Training & Benefits', 'in_house' => '$10,000 - $30,000', 'technbrains' => '0',                                        'freelancer' => '0' ),
        array( 'id' => 4,  'hiring' => 'Time to Scale Size of the Team',        'in_house' => '4 - 16 weeks',      'technbrains' => '48 hours - 1 week',                        'freelancer' => '1 - 12 weeks' ),
        array( 'id' => 5,  'hiring' => 'Pricing (weekly average)',               'in_house' => '2.5 X',             'technbrains' => '1.5 X',                                    'freelancer' => '1 X' ),
        array( 'id' => 6,  'hiring' => 'Project Failure Risk',                  'in_house' => 'Low',               'technbrains' => 'Extremely low, we have a 98% success ratio', 'freelancer' => 'Very High' ),
        array( 'id' => 7,  'hiring' => 'Developers Backed by a Delivery Team',  'in_house' => 'Some',              'technbrains' => 'Yes',                                      'freelancer' => 'No' ),
        array( 'id' => 8,  'hiring' => 'Dedicated Resources',                   'in_house' => 'Yes',               'technbrains' => 'Yes',                                      'freelancer' => 'No' ),
        array( 'id' => 9,  'hiring' => 'Shadow Resource',                       'in_house' => 'Costly',            'technbrains' => 'Yes',                                      'freelancer' => 'No' ),
        array( 'id' => 10, 'hiring' => 'Project Manager',                       'in_house' => 'Extra Cost',        'technbrains' => 'Minimal cost',                             'freelancer' => 'No' ),
        array( 'id' => 11, 'hiring' => 'Quality Assurance Check',               'in_house' => 'Extra Cost',        'technbrains' => 'Assured',                                  'freelancer' => 'No' ),
        array( 'id' => 12, 'hiring' => 'Query Support',                         'in_house' => 'High',              'technbrains' => '24 Hours Assurance',                       'freelancer' => 'No' ),
        array( 'id' => 13, 'hiring' => 'Tools & Environment Depend on Team',    'in_house' => 'High',              'technbrains' => 'Uncertain',                                'freelancer' => 'Uncertain' ),
        array( 'id' => 14, 'hiring' => 'Agile Development Methodology',         'in_house' => 'May Be',            'technbrains' => 'Yes',                                      'freelancer' => 'No' ),
        array( 'id' => 15, 'hiring' => 'Impact Due to Turnover',                'in_house' => 'High',              'technbrains' => 'None',                                     'freelancer' => 'High' ),
        array( 'id' => 16, 'hiring' => 'Structured Training Programs',          'in_house' => 'Some',              'technbrains' => 'Yes',                                      'freelancer' => 'No' ),
        array( 'id' => 17, 'hiring' => 'Communications',                        'in_house' => 'Seamless',          'technbrains' => 'Seamless',                                 'freelancer' => 'Uncertain' ),
        array( 'id' => 18, 'hiring' => 'Termination Costs',                     'in_house' => 'High',              'technbrains' => 'None',                                     'freelancer' => 'None' ),
        array( 'id' => 19, 'hiring' => 'Assured Work Rigor',                    'in_house' => '40 hrs/week',       'technbrains' => '40 hrs/week',                              'freelancer' => 'Not Sure' ),
    ),
),
		'steps_hire'       => array(
			'sub_head' => 'Hire Andriod Developers in Just 3 Easy Steps.',
			'para_text'=> 'Hiring Andriod developers is now as simple as 1-2-3 with TechnBrains. Our streamlined process allows you to hire Andriod developers in just three easy steps, ensuring a hassle-free journey from idea to app reality.',
			'box_list' => array(
				array( 'number' => '01', 'title' => 'Choose your Engagement Model',      'content' => array( 'Select the engagement model that suits your project and budget.' ),                                                                                         'image_src' => '/hire/boxone-img.webp',   'width' => 225, 'height' => 267 ),
				array( 'number' => '02', 'title' => 'Select & Pick Android Developers',  'content' => array( 'Handpick Andriod developers from our talented pool of experts and interview them for their technical expertise.' ),                                          'image_src' => '/hire/boxtwo-img.webp',   'width' => 327, 'height' => 267 ),
				array( 'number' => '03', 'title' => 'ONBOARD Android APP DEVELOPERS',    'content' => array( 'Onboard your chosen Andriod app developers seamlessly for a productive collaboration.' ),                                                                    'image_src' => '/hire/boxthree-img.webp', 'width' => 334, 'height' => 267 ),
			),
		),
		'hire_tech_stack'  => array(
			'sub_head'  => 'OUR ANDRIOD DEVELOPER\'S TECH STACK EXPERTISE',
			'para_text' => 'Our team of developers specializing in Android possess a wide range of skills and experience in various tools and frameworks available in the Android ecosystem. They have an extensive understanding of Kotlin and Java languages. They are also proficient in UI/UX design, API integration, and performance optimization, ensuring that your app is exceptional and competitive in the Android market.',
			'hire_list' => array(
				array( 'number' => '01', 'head' => 'Editors',             'para' => '● Android Studio<br>● Android IDE<br>● Kotlin<br>● Java<br>● Microsoft Visual Studio<br>● IntellijiDE' ),
				array( 'number' => '02', 'head' => 'Andriod Frameworks',  'para' => '● Ionic<br>● Flutter<br>● React Native<br>● .Net MAUI<br>● PhoneGap<br>● Cordova' ),
				array( 'number' => '03', 'head' => 'UI Tools',            'para' => '● Panache<br>● Screenshot<br>● Supernova<br>● Adobe Plugins<br>● Rive' ),
				array( 'number' => '04', 'head' => 'Plugins & Libraries', 'para' => '● Retrofit<br>● Moshi<br>● IntelliJ<br>● CodeGlance<br>● ExoPlayer' ),
			),
		),
		'main_cta'         => array(),
		'faqs' => array(
    'head_text' => 'We\'re here to help',
    'faq_image' => true,
    'listing'   => array(
        array( 'faqhead' => 'How much does it cost to hire Android developers?',                          'faqbody' => 'The cost to hire Android developers depends on the developer\'s experience, app complexity, engagement model, required features, and backend integration needs. A simple Android MVP may cost less than an enterprise, fintech, healthcare, ecommerce, or SaaS app that needs advanced security, API integrations, QA, and Play Store deployment support. At TechnBrains, you can hire Android developers through staff augmentation, software outsourcing, or dedicated teams based on your project scope and budget.' ),
        array( 'faqhead' => 'What skills should I look for when hiring an Android developer?',            'faqbody' => 'When hiring an Android developer, look for experience in Kotlin, Java, Android SDK, Android Studio, Jetpack Compose, REST APIs, Firebase, databases, Git, testing, and Play Store deployment. For business-critical apps, the developer should also understand app architecture, performance optimization, secure authentication, responsive UI, third-party integrations, and long-term maintenance.' ),
        array( 'faqhead' => 'Can I hire Android developers for an existing app?',                         'faqbody' => 'Yes. You can hire Android developers to improve, maintain, or scale an existing Android app. This may include fixing bugs, improving app performance, updating older Java code, adding new features, redesigning screens, integrating APIs, improving security, or preparing the app for newer Android versions. This is a strong fit for staff augmentation when you already have an internal team and need additional Android expertise.' ),
        array( 'faqhead' => 'Should I hire an Android developer or outsource the full Android app project?', 'faqbody' => 'Hire an Android developer through staff augmentation when you already have a product team and need Android expertise to support development. Choose software outsourcing when you want TechnBrains to manage the full Android app development process, including planning, UI/UX, development, backend integration, QA, and launch. Choose a dedicated team when your product needs ongoing Android development, regular feature releases, and long-term support.' ),
        array( 'faqhead' => 'Do your Android developers build apps with Kotlin and Jetpack Compose?',     'faqbody' => 'Yes. TechnBrains provides Android developers experienced in Kotlin, Java, Android Studio, Android SDK, Jetpack Compose, API integrations, and backend connectivity. Kotlin is widely used for modern Android development, while Jetpack Compose helps developers build native Android interfaces with cleaner UI development workflows.' ),
        array( 'faqhead' => 'Can TechnBrains help with Google Play Store submission?',                    'faqbody' => 'Yes. TechnBrains can help prepare your Android app for Google Play Store submission, including testing, build preparation, release setup, app metadata support, compliance checks, and launch coordination. Proper preparation before submission helps reduce publishing issues and improves the chances of a smoother app launch.' ),
        array( 'faqhead' => 'Do you provide post-launch support after hiring Android developers?',        'faqbody' => 'Yes. TechnBrains provides post-launch Android app support for bug fixes, performance monitoring, feature improvements, compatibility updates, regression testing, Play Store release management, and ongoing maintenance. Post-launch support is important because Android devices, OS versions, user expectations, and business requirements continue to change after the app goes live.' ),
    ),
),
	),
	'components' => array(
		array( 'name' => 'hire-banner',  'modifier_class' => '', 'args' => array() ),
		array( 'name' => 'freelance',    'modifier_class' => '', 'args' => array() ),
		array( 'name' => 'hire-cta',     'modifier_class' => '', 'args' => array( 'data_key' => 'hire_cta_1' ) ),
		array( 'name' => 'hire-tab',     'modifier_class' => '', 'args' => array() ),
		array( 'name' => 'hire-choose',  'modifier_class' => '', 'args' => array() ),
		array( 'name' => 'hire-table',   'modifier_class' => '', 'args' => array() ),
		array( 'name' => 'hire-cta',     'modifier_class' => '', 'args' => array( 'data_key' => 'hire_cta_2' ) ),
		array( 'name' => 'steps-hire',   'modifier_class' => '', 'args' => array() ),
		array( 'name' => 'hire',         'modifier_class' => '', 'args' => array() ),
		array( 'name' => 'main-cta',     'modifier_class' => '', 'args' => array() ),
		array( 'name' => 'main-faqs',    'modifier_class' => '', 'args' => array() ),
		array( 'name' => 'testimonials', 'modifier_class' => '', 'args' => array() ),
	),
);
