<?php
/**
 * Data Registry: Hire Dedicated Team
 *
 * @package technbrains-child
 */

defined( 'ABSPATH' ) || exit;

return array(
	'schemas'    => array(),
	'mock_data'  => array(
		'engagement_banner' => array(
    'head_text'   => 'Accelerate Product Delivery With a Dedicated Development Team',
    'para_text'   => 'Hire dedicated development team to quickly extend your engineering capacity with experienced developers who plug into your workflows and help move product development forward without hiring delays.',
    'banner_list' => array(
        array( 'li_list' => 'Faster execution without long recruitment cycles.' ),
        array( 'li_list' => 'Immediate access to experienced engineering talent.' ),
        array( 'li_list' => 'Smoother collaboration with your existing team structure.' ),
        array( 'li_list' => 'Flexible scaling based on project workload and priorities.' ),
    ),
    'form_title'  => 'Get Matched With A Dedicated Team Ready To Build',
    'form_para'   => 'Access a dedicated development team that aligns with your goals and accelerates product execution from day one.',
),
		'dedicated_lang_desc' => array(
    'para_html' => 'Hiring a dedicated software development team from TechnBrains gives you immediate access to experienced engineers who have delivered scalable digital products for startups, scaleups, and enterprises. Our teams help reduce delivery friction and accelerate execution from idea to launch. Our approach works on sprint cycles with clear milestones and performance metrics for full transparency. This ensures faster delivery, consistent quality, and the flexibility to scale resources as project needs evolve.',
),
		'benefits' => array(
    'title_html'  => '<span>What is</span> a Dedicated Development Team?',
    'para'        => 'A dedicated development team is a model where skilled engineers work exclusively on your project as an extension of your in-house team. They follow your workflows, priorities, and delivery processes while staying fully aligned with your business goals.',
    'para_two'    => '',
    'box_para'    => 'Dedicated Engineering Support Across Critical Product Development Areas',
    'para_three'  => 'Unlike traditional outsourcing, a dedicated team remains focused on your product long-term, enabling faster execution, better collaboration, and continuous development without the overhead of hiring and managing full-time employees.',
    'listing'     => array(
        array(
            'img_src' => '/engagement-model/dedicated-team/b1.png',
            'name'    => 'Web & Custom Software Development',
            'para'    => 'Get scalable <a href="/web-app-development/">web app development</a> and <a href="/custom-software-development/">custom software solutions</a> tailored to your workflows, business logic, and long-term operational goals with dedicated engineering support.',
        ),
        array(
            'img_src' => '/engagement-model/dedicated-team/b2.png',
            'name'    => 'Mobile App Development Across Platforms',
            'para'    => 'Accelerate <a href="/mobile-app-development/">mobile app development</a> with dedicated iOS and Android support focused on usability, performance, and consistent release cycles.',
        ),
        array(
            'img_src' => '/engagement-model/dedicated-team/b3.png',
            'name'    => 'Frontend, Backend & API Engineering',
            'para'    => 'Strengthen your product architecture with experienced developers skilled in responsive frontend systems, backend infrastructure, APIs, and scalable server-side development.',
        ),
        array(
            'img_src' => '/engagement-model/dedicated-team/b4.png',
            'name'    => 'AI-Powered Solutions',
            'para'    => 'Build intelligent digital products with dedicated engineers experienced in machine learning systems, workflow automation, predictive analytics, and advanced <a href="/ai-development-services/">AI development</a>.',
        ),
        array(
            'img_src' => '/engagement-model/dedicated-team/b5.png',
            'name'    => 'Product Scaling & Ongoing Development',
            'para'    => 'Support continuous product growth with dedicated developers who integrate into your workflows, accelerate feature delivery, and provide long-term engineering continuity.',
        ),
    ),
),
		'dev_process' => array(
    'classes'    => 'gray-bg',
    'main_title' => 'Our Process',
    'lang_title' => 'From First Consultation To Fully Aligned Development Team',
    'lang_para'  => 'We follow a structured process to understand your requirements, assemble the right dedicated team, and align them with your workflows.',
    'listing'    => array(
        array(
            'number' => '01',
            'title'  => 'Discovery & Requirement Consultation',
            'para'   => 'We begin with a detailed consultation to understand your product vision, technical requirements, team structure needs, and delivery expectations to define the right engagement setup.',
        ),
        array(
            'number' => '02',
            'title'  => 'Team Structuring & Skill Mapping',
            'para'   => 'Based on your requirements, we assemble a dedicated team with the right mix of skills, experience, and domain expertise to match your project goals and technical stack.',
        ),
        array(
            'number' => '03',
            'title'  => 'Team Alignment & Onboarding',
            'para'   => 'The selected team is aligned with your workflows, tools, and communication processes, ensuring they operate as a seamless extension of your internal team.',
        ),
        array(
            'number' => '04',
            'title'  => 'Project Kickoff & Execution Setup',
            'para'   => 'We initiate the project with clear milestones, sprint structure, and delivery planning, ensuring full transparency and a smooth transition into active development.',
        ),
        array(
            'number' => '05',
            'title'  => 'Continuous Collaboration & Optimization',
            'para'   => 'Throughout the engagement, we maintain ongoing coordination, performance tracking, and process optimization to ensure consistent output and long-term efficiency.',
        ),
    ),
),
		'steps_hire' => array(
    'head_text' => 'Dedicated Development Team',
    'sub_head'  => 'Strengthen Your Product Team With Experienced Engineers',
    'box_list'  => array(
        array(
            'number'    => '03',
            'title'     => 'Dedicated Team',
            'content'   => array(
                'Our engineers integrate seamlessly into your operations to support continuous development, faster execution, and long-term product growth.',
            ),
            'image_src' => '/engagement-model/dedicated-team/team.gif',
            'width'     => 368,
            'height'    => 261,
        ),
    ),
),
		'two_boxes' => array(
    'subtitle'    => 'Our approach',
    'title'       => 'Focused On The Product Outcomes That Matter To You',
    'tnb_logo'    => '/engagement-model/dedicated-team/tnblogo.png',
    'client_logo' => '/engagement-model/dedicated-team/cliet.png',
    'listing'     => array(
        array(
            'img_src'    => '/engagement-model/dedicated-team/sd1.png',
            'img_width'  => '60',
            'img_height' => '60',
            'title'      => 'Product Context Retention',
            'para'       => 'Engineers stay deeply familiar with your product architecture, reducing repeated knowledge transfer and improving development consistency over time.',
        ),
        array(
            'img_src'    => '/engagement-model/dedicated-team/sd2.png',
            'img_width'  => '60',
            'img_height' => '60',
            'title'      => 'Reduced Operational Overhead',
            'para'       => 'Avoid the internal burden of recruitment, onboarding, and team management while maintaining strong engineering output across ongoing initiatives.',
        ),
        array(
            'img_src'    => '/engagement-model/dedicated-team/sd3.png',
            'img_width'  => '60',
            'img_height' => '60',
            'title'      => 'Faster Feature Iteration',
            'para'       => 'Close collaboration between stakeholders and engineers enables quicker implementation, shorter feedback loops, and smoother release cycles.',
        ),
        array(
            'img_src'    => '/engagement-model/dedicated-team/sd4.png',
            'img_width'  => '60',
            'img_height' => '60',
            'title'      => 'Better Technical Continuity',
            'para'       => 'A stable engineering setup minimizes disruption during scaling, feature expansion, and long-term product evolution.',
        ),
        array(
            'img_src'    => '/engagement-model/dedicated-team/sd5.png',
            'img_width'  => '60',
            'img_height' => '60',
            'title'      => 'Delivery Visibility Across Execution',
            'para'       => 'Clear reporting structures and measurable engineering outcomes help maintain accountability throughout active development phases.',
        ),
        array(
            'img_src'    => '/engagement-model/dedicated-team/sd6.png',
            'img_width'  => '60',
            'img_height' => '60',
            'title'      => 'Adaptability To Changing Priorities',
            'para'       => 'Team capacity and engineering focus can adjust as roadmap priorities evolve without interrupting ongoing product development.',
        ),
    ),
),
		'requirements' => array(
    'main_title' => 'Hire Dedicated Development Team',
    'lang_title' => 'Hire Dedicated Experts Across Your Project Needs',
    'lang_para'  => 'We help you hire dedicated development team professionals based on your project scope, technology stack, and delivery requirements. From early-stage startups to enterprise systems, our engineers integrate into your workflow and contribute directly to product development with flexibility, speed, and consistency.',
    'listing'    => array(
        array(
            'img_src'   => '/engagement-model/dedicated-team/r1.png',
            'title'     => 'Web App Developer',
            'para_html' => '<ul><li>7+ years of experience</li><li>Available for flexible engagement hours</li><li>Skilled in building scalable web applications using modern frameworks like <a href="/technologies/react-native/">React</a>, <a href="/technologies/angular/">Angular</a>, <a href="/technologies/nodejs/">Node.js</a>, and <a href="/technologies/python/">Python</a></li></ul>',
        ),
        array(
            'img_src'   => '/engagement-model/dedicated-team/r2.png',
            'title'     => 'Mobile App Developer',
            'para_html' => '<ul><li>8+ years of experience</li><li>Available for flexible engagement hours</li><li>Experienced in <a href="/ios-app-development/">iOS</a>, <a href="/android-app-development/">Android</a>, and cross-platform app development with a strong UI/UX optimization focus</li></ul>',
        ),
        array(
    'img_src'   => '/engagement-model/dedicated-team/r3.png',
    'title'     => 'AI Engineer',
    'para_html' => '<ul><li>5+ years of experience</li><li>Available for flexible engagement hours</li><li>Expert in <a href="/ai-development-services/">AI development</a>, machine learning models, and smart contracts</li></ul>',
),
array(
    'img_src'   => '/engagement-model/dedicated-team/r4.png',
    'title'     => 'Frontend Developer',
    'para_html' => '<ul><li>8+ years of experience</li><li>Available for flexible engagement hours</li><li>Skilled in React, Angular, JavaScript, <a href="/technologies/html5/">HTML5</a>, and CSS3 for building responsive and high-performance user interfaces</li></ul>',
),
array(
    'img_src'   => '/engagement-model/dedicated-team/r5.png',
    'title'     => 'Backend Developer',
    'para_html' => '<ul><li>7+ years of experience</li><li>Available for flexible engagement hours</li><li>Experienced in Node.js, <a href="/technologies/php/">PHP</a>, Python, <a href="/technologies/java/">Java</a>, and <a href="/technologies/net/">.NET</a> for building secure, scalable, and high-performance server-side systems</li></ul>',
),
array(
    'img_src'   => '/engagement-model/dedicated-team/r6.png',
    'title'     => 'Software Engineer',
    'para_html' => '<ul><li>8+ years of experience</li><li>Available for flexible engagement hours</li><li>Strong background in system design, backend architecture, APIs, and full-cycle <a href="/custom-software-development/">software development</a></li></ul>',
),
        array(
            'img_src'   => '/engagement-model/dedicated-team/r7.png',
            'title'     => 'Product / Project Manager',
            'para_html' => '<ul><li>5+ years of experience</li><li>Available for flexible engagement hours</li><li>Ensures sprint planning, delivery tracking, coordination, and alignment between business goals and engineering execution</li></ul>',
        ),
    ),
),
		'table_two' => array(
    'head_text'  => 'Agile scalability with TechnBrains',
    'sub_head'   => 'Why Choose TechnBrains For Dedicated Development Teams?',
    'para_text'  => 'Partnering with TechnBrains gives you access to a dedicated development team that integrates directly into your product workflow. Instead of managing hiring, training, and coordination overhead, you get a stable engineering unit focused on consistent delivery, faster execution, and long-term product growth.',
    'classes'    => 'gray-bg',
    'table_list' => array(
        array( 'hiring' => 'Flexible Scalability',          'in_house' => true,  'technbrains' => true,  'para' => true ),
        array( 'hiring' => 'Access to Elite Tech Talent',   'in_house' => true,  'technbrains' => true,  'para' => true ),
        array( 'hiring' => 'Skill Gap Coverage',            'in_house' => true ),
        array( 'hiring' => 'Seamless Team Integration',     'in_house' => true ),
        array( 'hiring' => 'Self-Managed Execution',        'in_house' => true,  'technbrains' => true ),
        array( 'hiring' => 'Long-Term Team Collaboration',  'technbrains' => true, 'para' => true ),
        array( 'hiring' => 'Minimal In-House Management',   'technbrains' => true, 'para' => true ),
        array( 'hiring' => 'Structured Project Management', 'para' => true ),
    ),
),
		'proposal' => array(
    'head_html' => '<h2>Start Your Project With A Dedicated Development Team</h2>',
    'btn_text'  => "Get Your Team",
    'classes'   => 'boxHead',
),
		'progress' => array(
    'subtitle'    => 'Move your product forward with dedicated engineers.',
    'title'       => 'How Our Dedicated Team Supports Your Product Delivery Goals',
    'para'        => 'TechnBrains provides a certified, dedicated development team that integrates directly into your workflow, helping you overcome hiring delays and scale engineering capacity with ease. Our teams focus on execution, stability, and continuous delivery so your product progresses without blockers.',
    'classes'     => 'dedicatedTeam',
    'show_button' => false,
    'listing'     => array(
        array(
            'img_src'     => '/engagement-model/dedicated-team/p1.png',
            'tab_title'   => 'Faster Time-To-Market',
            'custom_para' => 'Reduce delays in development cycles through focused execution and structured sprint delivery. Our dedicated teams work with clear priorities and continuous progress tracking to keep development moving without unnecessary blockers.',
        ),
        array(
            'img_src'     => '/engagement-model/dedicated-team/p2.png',
            'tab_title'   => 'Lower Development Overhead',
            'custom_para' => 'Optimize engineering costs by removing the need for recruitment, onboarding, and ongoing team management. You gain a ready-to-work development team that reduces operational burden while maintaining consistent output and quality across the project lifecycle.',
        ),
        array(
            'img_src'     => '/engagement-model/dedicated-team/p3.png',
            'tab_title'   => 'Business-Focused Execution',
            'custom_para' => 'Your internal teams stay focused on strategy, product direction, and growth initiatives while we manage day-to-day engineering execution. This separation of responsibilities improves efficiency and ensures technical delivery stays aligned with business priorities.',
        ),
        array(
            'img_src'     => '/engagement-model/dedicated-team/p4.png',
            'tab_title'   => 'Certified Engineering Talent',
            'custom_para' => 'Access experienced engineers with proven expertise across modern technologies and complex product environments. Each team member is selected based on technical capability and project relevance, ensuring reliable performance and strong engineering standards throughout development.',
        ),
    ),
),
		'case_slider'         => array(
			'classes'    => 'gray-bg',
			'title_html' => 'Our<br><span>Global Clientele</span>',
			'para'       => 'TechnBrains converts business ideas into tangible products that deliver measurable results.',
			'listing'    => array(
				array(
					'link'        => '/case-studies/fixcarsharer/',
					'img_src'     => '/app-dev/case-study/fix.webp',
					'logo'        => '/app-dev/case-study/logo/fix.png',
					'logo_width'  => '200',
					'logo_height' => '30',
					'content'     => 'Fix Car Sharer revolutionizes commuting with a user-centric carpooling app. Powered by TechnBrains the app offers preference-based matchmaking, real-time tracking, payment integration, and QR code start.',
					'title'       => 'Platform',
					'stack'       => 'React Native',
					'tag'         => 'Mobile Application',
				),
				array(
					'link'        => '/case-studies/built-by-determination/',
					'img_src'     => '/app-dev/case-study/built.webp',
					'logo'        => '/app-dev/case-study/logo/built.png',
					'logo_width'  => '170',
					'logo_height' => '42',
					'content'     => 'Built By Determination revolutionizes fitness with personalized workouts, nutrition tracking, and certified trainers. Power by TechnBrains the app prioritizes client needs and innovation.',
					'title'       => 'Platform',
					'stack'       => 'React Native',
					'tag'         => 'Mobile Application',
				),
				array(
					'link'        => '/case-studies/white-tail/',
					'img_src'     => '/app-dev/case-study/white.webp',
					'logo'        => '/app-dev/case-study/logo/white.png',
					'logo_width'  => '200',
					'logo_height' => '35',
					'content'     => 'Whitetail Almanac is a hunting platform that prioritizes precision, safety, and adventure. Built with LEMP Stack, React Native, and Laravel, it caters to the Florida, USA region, integrating Aries Weather, Google Maps, and Google Firebase.',
					'title'       => 'Platform',
					'stack'       => 'React Native',
					'tag'         => 'Mobile Application',
				),
				array(
					'link'        => '/case-studies/cruze4cash/',
					'img_src'     => '/app-dev/case-study/cruze4cash.webp',
					'logo'        => '/app-dev/case-study/logo/cruze-logo.png',
					'logo_width'  => '150',
					'logo_height' => '30',
					'content'     => 'Cruze4cash revolutionizes property search with instant access, user-friendly design, secure login, and efficient navigation, simplifying the process and facilitating seamless connections between users, buyers, landlords, and sellers.',
					'title'       => 'Platform',
					'stack'       => 'React Native',
					'tag'         => 'Mobile Application',
				),
				array(
					'link'        => '/case-studies/cofit/',
					'img_src'     => '/app-dev/case-study/cofit 365.webp',
					'logo'        => '/app-dev/case-study/logo/Case-logo.webp',
					'logo_width'  => '60',
					'logo_height' => '50',
					'content'     => 'CoFit365, a health and fitness social network, addresses isolation and inactivity challenges. TechnBrains developed the hybrid app, ensuring robust performance and user-centric design. It promotes wellness, community engagement, and supports local businesses.',
					'title'       => 'Platform',
					'stack'       => 'React Native',
					'tag'         => 'Mobile Application',
				),
				array(
					'link'        => '/case-studies/the-5-spheres-of-fit/',
					'img_src'     => '/app-dev/case-study/5spheres.webp',
					'logo'        => '/app-dev/case-study/logo/brand-logo.webp',
					'logo_width'  => '50',
					'logo_height' => '50',
					'content'     => '5 Spheres of Fit, a wellness app, integrates cutting-edge technology MERN Stack and React Native for holistic well-being. Challenges addressed include data security, user engagement, content curation, expertise blending, and monetization.',
					'title'       => 'Platform',
					'stack'       => 'React Native',
					'tag'         => 'Mobile Application',
				),
			),
		),
		'proposal_alt' => array(
    'head_html' => '<h2>Take Your Product From Vision To Reliable Engineering Execution</h2>',
    'btn_text'  => "Hire Developers",
    'classes'   => 'dedicated',
),
		'industries_slider' => array(
    'subtitle' => 'Built For Every Industry Challenge',
    'title'    => 'Industry-Focused Development With Dedicated Teams Across Key Sectors',
    'para'     => 'TechnBrains provides dedicated development teams that understand the operational complexity of different industries. Instead of offering one-size-fits-all solutions, we align engineering capabilities with domain workflows, compliance requirements, and real-world system challenges.',
    'listing'  => array(
        array(
            'img_src'   => '/engagement-model/dedicated-team/i5.png',
            'tab_title' => 'Healthcare',
            'title_two' => '<a href="/industries/healthcare-app-development/">Healthcare</a>',
            'content'   => 'Secure and compliant healthcare systems for patient data management, clinical workflows, and operational efficiency across healthcare providers and platforms.',
        ),
        array(
            'img_src'   => '/engagement-model/dedicated-team/i1.png',
            'tab_title' => 'Automotive',
            'title_two' => '<a href="/industries/automotive-app-development/">Automotive</a>',
            'content'   => 'Connected mobility and vehicle management solutions that support fleet tracking, diagnostics, and real-time operational data processing.',
        ),
        array(
            'img_src'   => '/engagement-model/dedicated-team/i8.png',
            'tab_title' => 'Fintech',
            'title_two' => '<a href="/industries/fintech-software-development/">Fintech</a>',
            'content'   => 'Secure financial applications for payments, transactions, risk handling, and regulatory-compliant digital financial workflows.',
        ),
        array(
            'img_src'   => '/engagement-model/dedicated-team/i2.png',
            'tab_title' => 'Logistics',
            'title_two' => '<a href="/industries/logistics-software-development/">Logistics</a>',
            'content'   => 'End-to-end logistics platforms for shipment tracking, route optimization, fleet coordination, and supply chain visibility.',
        ),
        array(
            'img_src'   => '/engagement-model/dedicated-team/i6.png',
            'tab_title' => 'Real Estate',
            'title_two' => '<a href="/industries/real-estate-app-development/">Real Estate</a>',
            'content'   => 'Digital property platforms for listings, CRM workflows, lead management, and transaction processing across real estate operations.',
        ),
        array(
            'img_src'   => '/next-gen/cyber-security/w1.webp',
            'tab_title' => 'EdTech',
            'title_two' => '<a href="/industries/education-app-development/">EdTech</a>',
            'content'   => 'Learning management systems and digital education platforms that support content delivery, student tracking, and interactive learning experiences.',
        ),
        array(
            'img_src'   => '/engagement-model/dedicated-team/i7.png',
            'tab_title' => 'Energy',
            'title_two' => '<a href="/industries/energy-management-software-development/">Energy</a>',
            'content'   => 'Operational systems for monitoring, asset management, and infrastructure optimization in energy and utility networks.',
        ),
        array(
            'img_src'   => '/next-gen/augmented/custom-1.webp',
            'tab_title' => 'Retail',
            'title_two' => '<a href="/industries/retail-app-development/">Retail</a>',
            'content'   => 'Customer-focused retail solutions for inventory management, omnichannel commerce, and improved buying experiences across platforms.',
        ),
    ),
),
		'software_solutions' => array(
    'main_title'  => 'Why TechnBrains',
    'title'       => 'What You Should Never Compromise On When Hiring A Dedicated Team',
    'para'        => 'Many dedicated teams fail not because of technical capability, but because of poor alignment, inconsistent communication, and a lack of long-term ownership. Businesses often struggle with developers who work without product context, changing team structures, and delivery processes that become difficult to manage as projects grow. TechnBrains dedicated team services are built to solve these operational gaps by creating stable, product-aligned teams that integrate smoothly into your workflows and support continuous execution.',
    'show_button' => true,
    'listing'     => array(
        array( 'img_src' => '/engagement-model/dedicated-team/d1.png', 'img_width' => 48, 'img_height' => 48, 'title' => 'Product Context Retention'),
        array( 'img_src' => '/engagement-model/dedicated-team/d2.png', 'img_width' => 48, 'img_height' => 48, 'title' => 'Stable Team Structure'),
        array( 'img_src' => '/engagement-model/dedicated-team/d3.png', 'img_width' => 48, 'img_height' => 48, 'title' => 'Transparent Sprint Execution'),
        array( 'img_src' => '/engagement-model/dedicated-team/d4.png', 'img_width' => 48, 'img_height' => 48, 'title' => 'Clear Communication Flow'),
        array( 'img_src' => '/engagement-model/dedicated-team/d5.png', 'img_width' => 48, 'img_height' => 48, 'title' => 'Long-Term Delivery Alignment'),
        array( 'img_src' => '/engagement-model/dedicated-team/d6.png', 'img_width' => 48, 'img_height' => 48, 'title' => 'Workflow Integration Readiness'),
    ),
),
		'software_solutions_alt' => array(
    'main_title' => 'Skilled Developers Ready to Hire',
    'title'      => 'Hire Dedicated Developers Across Modern Technologies',
    'para'       => 'Access top 3% developers across frontend, backend, mobile, and cross-platform technologies aligned with your business goals and delivery requirements.',
    'listing'    => array(
        array( 'img_src' => '/engagement-model/dedicated-team/t1.png',  'img_width' => 48, 'img_height' => 48, 'title' => 'Hire Mobile App Developers',      'link' => '/mobile-app-development/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t2.png',  'img_width' => 48, 'img_height' => 48, 'title' => 'Hire iOS Developers',             'link' => '/hire-ios-developer/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t3.png',  'img_width' => 48, 'img_height' => 48, 'title' => 'Hire Android Developers',         'link' => '/hire-android-developer/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t5.png',  'img_width' => 48, 'img_height' => 48, 'title' => 'Hire Flutter Developers',         'link' => '/hire-flutter-developer/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t6.png',  'img_width' => 48, 'img_height' => 48, 'title' => 'Hire React Native Developers',    'link' => '/hire-react-native-developer/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t7.png',  'img_width' => 48, 'img_height' => 48, 'title' => 'Hire Swift Developers',           'link' => '/hire-swift-developer/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t17.png', 'img_width' => 48, 'img_height' => 48, 'title' => 'Hire Web App Developers',         'link' => '/web-app-development/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t14.png', 'img_width' => 48, 'img_height' => 48, 'title' => 'Hire ReactJS Developers',         'link' => '/hire-reactjs-developer/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t13.png', 'img_width' => 48, 'img_height' => 48, 'title' => 'Hire AngularJS Developers',       'link' => '/hire-angularjs-developer/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t15.png', 'img_width' => 48, 'img_height' => 48, 'title' => 'Hire JavaScript Developers',      'link' => '/hire-javascript-developer/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t11.png', 'img_width' => 48, 'img_height' => 48, 'title' => 'Hire NodeJS Developers',          'link' => '/hire-nodejs-developer/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t10.png', 'img_width' => 48, 'img_height' => 48, 'title' => 'Hire Python Developers',          'link' => '/hire-python-developer/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t9.png',  'img_width' => 48, 'img_height' => 48, 'title' => 'Hire PHP Developers',             'link' => '/hire-php-developer/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t8.png',  'img_width' => 48, 'img_height' => 48, 'title' => 'Hire Laravel Developers',         'link' => '/hire-laravel-developer/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t12.png', 'img_width' => 48, 'img_height' => 48, 'title' => 'Hire Java Developers',            'link' => '/hire-java-developer/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t19.png', 'img_width' => 48, 'img_height' => 48, 'title' => 'Hire .NET Developers',            'link' => '/technologies/net/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t4.png',  'img_width' => 48, 'img_height' => 48, 'title' => 'Hire Enterprise App Developers',  'link' => '/enterprise-app-development/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t16.png', 'img_width' => 48, 'img_height' => 48, 'title' => 'Hire Custom Software Developers', 'link' => '/custom-software-development/' ),
        array( 'img_src' => '/engagement-model/dedicated-team/t18.png', 'img_width' => 48, 'img_height' => 48, 'title' => 'Hire HTML5 Developers',           'link' => '/technologies/html5/' ),
    ),
),
		'faqs' => array(
    'head_text' => 'Things you might want to know',
    'add_class' => 'gray-bg',
    'listing'   => array(
        array(
            'faqhead' => 'What is a dedicated development team?',
            'faqbody' => 'A dedicated development team is a long-term engagement model where you hire a full team of developers, designers, and QA specialists who work exclusively on your project. It functions as an extension of your in-house team with full focus on your product roadmap.',
        ),
        array(
            'faqhead' => 'What exactly does a dedicated development team include?',
            'faqbody' => 'It typically includes a project manager, frontend and backend developers, UI/UX designers, QA engineers, and DevOps support if required. The setup is tailored to project complexity, ensuring all technical and delivery roles are covered under one aligned team.',
        ),
        array(
            'faqhead' => 'When should a business choose a dedicated development team model?',
            'faqbody' => 'This model is ideal for long-term digital products, SaaS platforms, or startups with evolving requirements. It works best when you need continuous development, faster scaling, and ongoing technical support without hiring full-time in-house staff.',
        ),
        array(
            'faqhead' => 'How is a dedicated development team different from outsourcing or freelancers?',
            'faqbody' => 'Freelancers work on isolated tasks, and traditional outsourcing is usually project-based with fixed scope. A dedicated team, however, works like your internal engineering unit, following your processes, participating in standups, and staying aligned with your long-term roadmap.',
        ),
        array(
            'faqhead' => 'What is the structure of a dedicated development team?',
            'faqbody' => 'A standard structure includes a project manager, frontend and backend developers, UI/UX designers, QA engineers, and optionally DevOps specialists. The structure can scale depending on project size, complexity, and delivery speed requirements.',
        ),
        array(
            'faqhead' => 'How do dedicated development teams handle changing requirements?',
            'faqbody' => 'Dedicated teams use agile methodology, which allows requirements to evolve during development. Changes are managed through sprint re-planning, priority adjustments, and iterative delivery without disrupting ongoing progress.',
        ),
        array(
            'faqhead' => 'How is productivity and progress tracked in a dedicated team setup?',
            'faqbody' => 'Progress is tracked through agile practices such as sprint planning, daily standups, milestone reviews, and reporting dashboards. Tools like Jira, Trello, or ClickUp are commonly used to ensure full transparency and accountability.',
        ),
        array(
            'faqhead' => 'How do dedicated teams ensure quality and handle delays?',
            'faqbody' => 'Quality is maintained through code reviews, automated testing, CI/CD pipelines, and QA validation before release. If delays occur, teams adjust sprint scope, rebalance workload, or scale resources to maintain delivery timelines without compromising quality.',
        ),
        array(
            'faqhead' => 'Can a dedicated development team scale during the project?',
            'faqbody' => 'Yes. One of the key advantages of this model is flexibility. You can scale the team up by adding developers or QA engineers during growth phases, or scale down during maintenance, without affecting ongoing development stability.',
        ),
    ),
),
	),
	'components' => array(
		array( 'name' => 'engagement-banner',      'modifier_class' => 'staff' ),
		array( 'name' => 'dedicated-lang-desc',    'modifier_class' => '' ),
		array( 'name' => 'benefits',               'modifier_class' => '' ),
		array( 'name' => 'development-process',    'modifier_class' => '' ),
		array( 'name' => 'engagement-steps-hire',  'modifier_class' => '' ),
		array( 'name' => 'two-boxes',              'modifier_class' => 'engagement redHover' ),
		array( 'name' => 'requirements',           'modifier_class' => '' ),
		array( 'name' => 'table-two',              'modifier_class' => '' ),
		array( 'name' => 'proposal',               'modifier_class' => 'boxHead' ),
		array( 'name' => 'progress',               'modifier_class' => '' ),
		array( 'name' => 'case-slider',            'modifier_class' => '' ),
		array( 'name' => 'proposal-alt',           'modifier_class' => 'dedicated' ),
		array( 'name' => 'industries-slider',      'modifier_class' => '' ),
		array( 'name' => 'solution-business',     'modifier_class' => 'devList' ),
		array( 'name' => 'solution-business-alt', 'modifier_class' => 'dedicatedDev' ),
		array( 'name' => 'main-faqs',              'modifier_class' => 'gray-bg' ),
	),
);
