<?php
defined('ABSPATH') || exit;

return array(
	'schemas'    => array(),
	'mock_data'  => array(
		'banner' => array(
    'head_text'   => 'Hire JavaScript Developer - JavaScript Experts for Interactive Websites',
    'para_text'   => "Harness the expertise of our JavaScript developers to create cutting-edge web and mobile applications. Our talented team specializes in crafting dynamic, responsive, and user-friendly solutions tailored to your project's unique requirements. Elevate your digital presence and stay ahead in the competitive digital landscape by partnering with us.",
    'form_title'  => 'Deploy React Projects',
    'form_para'   => 'With Top React Developers we are here to launch your app with a bang!',
    'banner_list' => array(
        array( 'li_list' => 'Proficiency in Handling Asynchronous JavaScript Operations' ),
        array( 'li_list' => 'Proficient in Integrating JavaScript with HTML and CSS Technologies' ),
        array( 'li_list' => 'Exceptional Skills in Both Frontend and Backend JavaScript Tech Stack' ),
        array( 'li_list' => 'In-Depth Knowledge of ECMAScript Standards' ),
    ),
),
		'steps_hire'       => array(
			'sub_head' => 'Hire JavaScript Developers in Just 3 Easy Steps',
			'para_text' => 'Streamline your development process with ease – Hire JavaScript developers in just three simple steps and unlock the potential of dynamic frontend solutions',
			'box_list' => array(
				array('number' => '01', 'title' => 'Choose your Engagement Model',  'content' => array('Select the engagement model that suits your project and budget.'),                                                                                                        'image_src' => '/hire/boxone-img.webp',   'width' => 225, 'height' => 267),
				array('number' => '02', 'title' => 'Pick JavaScript Developers',    'content' => array('Handpick JavaScript developers from our talented pool of experts and interview them for their technical expertise.'),                                                    'image_src' => '/hire/boxtwo-img.webp',   'width' => 327, 'height' => 267),
				array('number' => '03', 'title' => 'Onboard JavaScript Developers', 'content' => array('Onboard your chosen JavaScript Developer seamlessly for a productive collaboration.'),                                                                                   'image_src' => '/hire/boxthree-img.webp', 'width' => 334, 'height' => 267),
			),
		),
		'expert'           => array(
			'sub_head'   => 'Hire JavaScript Developers for Your Next Project',
			'para_text'  => 'Start your journey to exceptional web and app development by hiring JavaScript developers. Our skilled professionals bring a wealth of experience in JavaScript, delivering robust, dynamic, and user-friendly solutions tailored to your unique needs. Elevate your digital presence and achieve your business goals with our expert team. Choose from Hourly, Part-time and Full-time hiring to get started. Secure your project\'s success with us today!',
			'expert_box' => array(
				array(
					'src' => '/hire/angular/clock.png',
					'width' => 85,
					'height' => 85,
					'head' => 'Hourly Hiring',
					'expert_list' => array(
						array('item' => 'Dedicated 8 Hrs/day for consistent progress.'),
						array('item' => 'Enjoy adaptability with a minimum 30-day engagement.'),
						array('item' => 'Simplify payments with convenient monthly billing cycles.'),
					),
				),
				array(
					'src' => '/hire/angular/full.png',
					'width' => 85,
					'height' => 85,
					'head' => 'Full Time Hiring',
					'expert_list' => array(
						array('item' => 'Dedicated 8 Hrs/day for consistent progress.'),
						array('item' => 'Enjoy adaptability with a minimum 30-day engagement.'),
						array('item' => 'Simplify payments with convenient monthly billing cycles.'),
					),
				),
				array(
					'src' => '/hire/angular/part.png',
					'width' => 85,
					'height' => 85,
					'head' => 'Part Time Hiring',
					'expert_list' => array(
						array('item' => 'Dedicated 8 Hrs/day for consistent progress.'),
						array('item' => 'Enjoy adaptability with a minimum 30-day engagement.'),
						array('item' => 'Simplify payments with convenient monthly billing cycles.'),
					),
				),
			),
		),
		'hire_cta_1'       => array(
			'title'             => 'READY TO START YOUR DREAM PROJECT?',
			'para'              => 'WE HAVE A TEAM TO GET YOU THERE.',
			'primary_button'    => true,
			'secondary_button'  => false,
			'primary_btn_title' => 'GET IN TOUCH',
			'primary_btn_popup' => true,
		),
		'hire_choose' => array(
    'sub_head'    => 'Why Choose our JavaScript developers?',
    'para_text'   => 'Hire JavaScript developers for unparalleled expertise and results. Our team excels in crafting cutting- edge web and mobile applications, leveraging the latest JavaScript technologies and frameworks. With a proven track record of delivering innovative solutions, we offer reliability, quality, and a commitment to exceeding your development expectations.',
    'choose_list' => array(
        array( 'src' => '/hire/laravel/image1.png', 'width' => 88, 'height' => 88, 'head' => 'Senior JavaScript Developer',   'para' => '3+ Years of JavaScript Experience 6-11 Project Managed 7000+ Development Hours Completed Suitable for General Level Projects' ),
        array( 'src' => '/hire/laravel/image2.png', 'width' => 88, 'height' => 88, 'head' => 'Full-Stack JavaScript Developer', 'para' => '5-10 Years of JavaScript Experience 10-25 Project Managed 15000+ Development Hours Completed Suitable for Advance Level Projects' ),
        array( 'src' => '/hire/laravel/image3.png', 'width' => 88, 'height' => 88, 'head' => 'JavaScript Project Manager',      'para' => '10+ Years of JavaScript Experience 20-50 Project Managed 25000+ Development Hours Completed Suitable when you Hire JavaScript Team' ),
    ),
),
		'skills'           => array(
			'sub_head'  => 'Skilled JavaScript Developers at TechnBrains',
			'para_text' => 'TechnBrains offers a team of highly skilled JavaScript developers. Our experts are well-versed in creating dynamic and efficient frontend solutions, ensuring top-notch quality and innovation in every project we undertake.',
			'skill_box' => array(
				array(
					'head'       => 'Technical',
					'sub_head'   => 'JavaScript Developers Technical Skills',
					'skill_list' => array(
						array('item' => 'Profound expertise in core JavaScript, including ES6 and beyond.'),
						array('item' => 'Proficiency in front-end technologies such as HTML5, CSS3, and responsive design.'),
						array('item' => 'Mastery of popular JavaScript libraries and frameworks like React, Angular, or Vue.js.'),
						array('item' => 'Strong understanding of asynchronous programming and promises.'),
						array('item' => 'Knowledge of RESTful API integration and web services.'),
						array('item' => 'Experience with testing frameworks like Jest or Mocha.'),
						array('item' => 'Version control proficiency with Git.'),
					),
				),
				array(
					'head'       => 'Non-Technical',
					'sub_head'   => 'JavaScript Developers Non-Technical Skills',
					'skill_list' => array(
						array('item' => 'Effective communication and collaboration within development teams.'),
						array('item' => 'Problem-solving and critical thinking abilities to troubleshoot complex issues.'),
						array('item' => 'Time management and project planning skills for efficient development.'),
						array('item' => 'Adaptability to rapidly evolving technology trends.'),
						array('item' => 'Attention to detail to ensure code quality and reliability.'),
						array('item' => 'Strong work ethic and dedication to meeting project deadlines.'),
						array('item' => 'Continuous learning and staying updated with industry best practices.'),
					),
				),
			),
		),
		'hire_table'       => array(
			'sub_head'   => 'Why Hire JavaScript developers from TechnBrains over freelance or in-house developers?',
			'para_text'  => 'Hiring JavaScript developers from TechnBrains offers a distinct advantage over freelance or in-house developers. Our team brings a depth of expertise, collaborative synergy, and reliability that ensures streamlined development, consistent quality, and access to a diverse skill set, making us the ideal choice for your project\'s success.',
			'table_list' => array(
				array('id' => 1,  'hiring' => 'Time to Get Right Developers',          'in_house' => '4 - 12 weeks',         'technbrains' => '1 day - 2 weeks',                      'freelancer' => '1 - 12 weeks'),
				array('id' => 2,  'hiring' => 'Time to Start a Project',               'in_house' => '2 - 10 weeks',         'technbrains' => '1 day - 2 weeks',                      'freelancer' => '1 - 10 weeks'),
				array('id' => 3,  'hiring' => 'Recurring Cost of Training & Benefits', 'in_house' => '$10,000 - $30,000',    'technbrains' => '0',                                    'freelancer' => '0'),
				array('id' => 4,  'hiring' => 'Time to Scale Size of the Team',        'in_house' => '4 - 16 weeks',         'technbrains' => '48 hours - 1 week',                    'freelancer' => '1 - 12 weeks'),
				array('id' => 5,  'hiring' => 'Pricing (weekly average)',               'in_house' => '2.5 X',                'technbrains' => '1.5 X',                                'freelancer' => '1 X'),
				array('id' => 6,  'hiring' => 'Project Failure Risk',                  'in_house' => 'Low',                  'technbrains' => 'Extremely low, we have a 98% success ratio', 'freelancer' => 'Very High'),
				array('id' => 7,  'hiring' => 'Developers Backed by a Delivery Team',  'in_house' => 'Some',                 'technbrains' => 'Yes',                                  'freelancer' => 'No'),
				array('id' => 8,  'hiring' => 'Dedicated Resources',                   'in_house' => 'Yes',                  'technbrains' => 'Yes',                                  'freelancer' => 'No'),
				array('id' => 9,  'hiring' => 'Shadow Resource',                       'in_house' => 'Costly',               'technbrains' => 'Yes',                                  'freelancer' => 'No'),
				array('id' => 10, 'hiring' => 'Project Manager',                       'in_house' => 'Extra Cost',           'technbrains' => 'Minimal cost',                         'freelancer' => 'No'),
				array('id' => 11, 'hiring' => 'Quality Assurance Check',               'in_house' => 'Extra Cost',           'technbrains' => 'Assured',                              'freelancer' => 'No'),
				array('id' => 12, 'hiring' => 'Query Support',                         'in_house' => 'High',                 'technbrains' => '24 Hours Assurance',                   'freelancer' => 'No'),
				array('id' => 13, 'hiring' => 'Tools & Environment',                   'in_house' => 'Depend on Team',       'technbrains' => 'High',                                 'freelancer' => 'Uncertain'),
				array('id' => 14, 'hiring' => 'Agile Development Methodology',         'in_house' => 'May Be',               'technbrains' => 'Yes',                                  'freelancer' => 'No'),
				array('id' => 15, 'hiring' => 'Impact Due to Turnover',                'in_house' => 'High',                 'technbrains' => 'None',                                 'freelancer' => 'High'),
				array('id' => 16, 'hiring' => 'Structured Training Programs',          'in_house' => 'Some',                 'technbrains' => 'Yes',                                  'freelancer' => 'No'),
				array('id' => 17, 'hiring' => 'Communications',                        'in_house' => 'Seamless',             'technbrains' => 'Seamless',                             'freelancer' => 'Uncertain'),
				array('id' => 18, 'hiring' => 'Termination Costs',                     'in_house' => 'High',                 'technbrains' => 'None',                                 'freelancer' => 'None'),
				array('id' => 19, 'hiring' => 'Assured Work Rigor',                    'in_house' => '40 hrs/week',          'technbrains' => '40 hrs/week',                          'freelancer' => 'Not Sure'),
			),
		),
		'hire_cta_2'       => array(
			'title'              => 'LOOKING TO PARTNER WITH US?',
			'para'               => 'Prepare For a Genuine Business Partnership',
			'primary_button'     => true,
			'secondary_button'   => true,
			'primary_btn_title'  => 'Check Out Partnership Model',
			'primary_btn_popup'  => true,
			'secondary_btn_title' => "LET'S TALK",
		),
		'hire_tech_stack'  => array(
			'sub_head'  => 'Tailor Your JavaScript Development with Skilled Developers',
			'para_text' => 'Customize your JavaScript development with our proficient developers. We deliver tailored solutions to match your unique project requirements, ensuring efficient, high-quality development that meets your precise needs. Here\'s what we offer:',
			'hire_list' => array(
				array('img' => '/hire/angular/4.png', 'width' => 75, 'height' => 75, 'head' => 'Achieve Cutting-Edge JS Development',  'para' => 'Unlock the potential of highly skilled JavaScript development teams to effectively engage and convert casual users into loyal customers for your business.'),
				array('img' => '/hire/angular/3.png', 'width' => 75, 'height' => 75, 'head' => 'JavaScript Plug-In Development',       'para' => 'Our full-stack JavaScript engineers excel in crafting robust plugins that smartly enhance app functionalities in a scalable and secure manner.'),
				array('img' => '/hire/angular/2.png', 'width' => 75, 'height' => 75, 'head' => 'Custom Software Development',          'para' => 'Our JS engineers simplify complex business scenarios with customized Java structures, delivering tailored programming solutions.'),
				array('img' => '/hire/angular/1.png', 'width' => 75, 'height' => 75, 'head' => 'Mobile App Development',               'para' => 'Hire a JavaScript programmer who harnesses the right framework to deliver genuine functionality aligned with your business needs and market demands.'),
			),
		),
		'main_cta'         => array(),
		'faqs' => array(
    'head_text' => 'We\'re here to help',
    'faq_image' => true,
    'listing'   => array(
        array( 'faqhead' => 'How much does it cost to hire ReactJS developers?',                          'faqbody' => 'The cost to hire ReactJS developers depends on developer experience, project complexity, engagement model, UI requirements, backend integrations, and timeline. A simple frontend update may cost less than a SaaS dashboard, ecommerce platform, enterprise portal, or custom web app that needs complex state management, API integrations, performance optimization, and QA. At TechnBrains, you can hire ReactJS developers through staff augmentation, software outsourcing, or dedicated teams based on your project scope and budget.' ),
        array( 'faqhead' => 'What skills should I look for when hiring a ReactJS developer?',             'faqbody' => 'When hiring a ReactJS developer, look for experience in JavaScript, TypeScript, React, Redux, REST APIs, GraphQL, HTML, CSS, responsive design, Git, testing, and frontend performance optimization. For complex products, the developer should also understand component-based architecture, reusable UI systems, secure API handling, cloud deployment workflows, and scalable frontend development.' ),
        array( 'faqhead' => 'Can I hire ReactJS developers for an existing web app?',                     'faqbody' => 'Yes. You can hire ReactJS developers to improve, maintain, or scale an existing web application. This may include fixing frontend bugs, improving page speed, updating old React code, migrating class components to functional components, improving state management, redesigning UI screens, integrating APIs, or building new product features. This is a strong fit for staff augmentation when you already have an internal team and need additional ReactJS expertise.' ),
        array( 'faqhead' => 'Should I hire a ReactJS developer or outsource the full ReactJS project?',  'faqbody' => 'Hire a ReactJS developer through staff augmentation when you already have an internal product or engineering team and need frontend expertise to support development. Choose software outsourcing when you want TechnBrains to manage the full ReactJS development process, including planning, UI/UX, frontend development, backend integration, QA, deployment, and support. Choose a dedicated team when your product needs continuous frontend development, regular releases, and long-term technical support.' ),
        array( 'faqhead' => 'Do your ReactJS developers work with Redux, REST APIs, and GraphQL?',        'faqbody' => 'Yes. TechnBrains provides ReactJS developers experienced in React, Redux, RESTful APIs, GraphQL, JavaScript, Git, responsive web design, and component-based frontend development. These skills are useful for SaaS platforms, ecommerce websites, dashboards, admin panels, portals, and web apps that need clean user interfaces connected to reliable backend systems.' ),
        array( 'faqhead' => 'Can TechnBrains help migrate an existing frontend to ReactJS?',              'faqbody' => 'Yes. TechnBrains can help migrate an existing frontend to ReactJS when your business wants better performance, reusable components, easier maintenance, or a more scalable user interface. The migration process may include reviewing the current frontend, rebuilding key screens, improving component structure, connecting APIs, testing functionality, and preparing the application for stable deployment.' ),
        array( 'faqhead' => 'Do you provide post-launch support after hiring ReactJS developers?',        'faqbody' => 'Yes. TechnBrains provides post-launch ReactJS support for bug fixes, performance improvements, UI refinements, dependency updates, browser compatibility fixes, API integration support, feature improvements, QA, and ongoing maintenance. Post-launch support is important because user needs, browser behavior, frontend libraries, security requirements, and product priorities continue to change after deployment.' ),
    ),
),
	),
	'components' => array(
		array('name' => 'hire-banner',  'modifier_class' => '', 'args' => array()),
		array('name' => 'steps-hire',   'modifier_class' => '', 'args' => array()),
		array('name' => 'expert',       'modifier_class' => '', 'args' => array()),
		array('name' => 'hire-cta',     'modifier_class' => '', 'args' => array('data_key' => 'hire_cta_1')),
		array('name' => 'hire-choose',  'modifier_class' => 'white-bg', 'args' => array()),
		array('name' => 'skills',       'modifier_class' => '', 'args' => array()),
		array('name' => 'hire-table',   'modifier_class' => '', 'args' => array()),
		array('name' => 'hire-cta',     'modifier_class' => '', 'args' => array('data_key' => 'hire_cta_2')),
		array('name' => 'hire',         'modifier_class' => '', 'args' => array()),
		array('name' => 'main-cta',     'modifier_class' => '', 'args' => array()),
		array('name' => 'main-faqs',    'modifier_class' => '', 'args' => array()),
		array('name' => 'testimonials', 'modifier_class' => '', 'args' => array()),
	),
);
