<?php
defined( 'ABSPATH' ) || exit;

return array(
	'schemas'    => array(),
	'mock_data'  => array(
		'portfolio_banner'    => array(
			'head_text' => 'Case <span>Studies</span>',
			'content'   => 'TechnBrains specializes in providing solutions that deliver tangible results across various industries. Every project we embark upon is aimed at enhancing our clients\' profitability. Reach out to us today to kickstart your next major endeavor!',
		),
		'case_study_card_list' => array(
			array( 'bg_image' => '/case-study-card/case7.webp',  'image' => '/case-study-card/mob7.webp',  'width' => 283, 'height' => 358, 'heading' => 'Qpon App',              'para' => 'A discount app we built offering subscription-based access to brand coupons. It increased user engagement, simplified savings, drove repeat usage, and provided a seamless, enjoyable discount experience.', 'app_store_link' => 'https://apps.apple.com/us/app/qpon-app/id1658749756', 'logo' => '/case-study-card/qpon.png', 'logo_width' => '71', 'logo_height' => '71', 'page_link' => '/case-studies/qpon/' ),
			array( 'bg_image' => '/case-study-card/case8.webp',  'image' => '/case-study-card/mob8.webp',  'width' => 253, 'height' => 358, 'heading' => 'Fix Car Sharer',        'para' => 'A carpooling app we developed matching users by route preferences and schedules. It reduced commuting costs, cut carbon emissions, and fostered a community of eco-conscious, cost-conscious commuters.', 'play_store_link' => 'https://play.google.com/store/apps/details?id=com.carfixsharer&hl=en', 'app_store_link' => 'https://apps.apple.com/us/app/fix-car-sharer/id1666244616', 'logo' => '/case-study-card/fix-car.png', 'logo_width' => '71', 'logo_height' => '71', 'page_link' => '/case-studies/fixcarsharer/' ),
			array( 'bg_image' => '/case-study-card/case11.webp', 'image' => '/case-study-card/mob11.webp', 'width' => 348, 'height' => 425, 'heading' => 'CoFit 365',             'para' => 'A hybrid fitness and social connection app we built to reduce isolation and inactivity. It promoted wellness, fostered engagement, encouraged outdoor activity, and supported local communities through exercise.', 'play_store_link' => 'https://play.google.com/store/apps/details?id=com.newcofit365&hl=en', 'app_store_link' => 'https://apps.apple.com/us/app/cofit-365/id6443740496', 'logo' => '/case-study-card/cofit.png', 'logo_width' => '65', 'logo_height' => '65', 'page_link' => '/case-studies/cofit/' ),
			array( 'bg_image' => '/case-study-card/case12.webp', 'image' => '/case-study-card/mob12.webp', 'width' => 344, 'height' => 401, 'heading' => 'Whitetail Almanac',     'para' => 'A hunting companion app we developed predicting deer feeding and travel patterns with telemetry. It improved strategy, boosted success rates, and provided hunters with reliable, actionable field insights.', 'play_store_link' => 'https://play.google.com/store/apps/details?id=com.whitetail.almanac', 'app_store_link' => 'https://apps.apple.com/us/app/whitetail-almanac/id1603886153', 'logo' => '/case-study-card/white.png', 'logo_width' => '69', 'logo_height' => '69', 'page_link' => '/case-studies/white-tail/' ),
			array( 'bg_image' => '/case-study-card/case6.webp',  'image' => '/case-study-card/mob6.webp',  'width' => 307, 'height' => 358, 'heading' => 'The Wedding App',       'para' => 'A wedding-planning app we built to help couples manage vendors, guest lists, and timelines. It simplified coordination, reduced stress, and gave couples clarity, confidence, and smooth event planning.', 'play_store_link' => 'https://play.google.com/store/apps/details?id=com.carolinacreations.theweddingapp', 'app_store_link' => 'https://apps.apple.com/us/app/the-wedding-app-us/id6459477343', 'logo' => '/case-study-card/wedding-app.png', 'logo_width' => '71', 'logo_height' => '71', 'page_link' => '/case-studies/the-wedding-app/' ),
			array( 'bg_image' => '/case-study-card/case13.webp', 'image' => '/case-study-card/mob13.webp', 'width' => 262, 'height' => 353, 'heading' => 'PlateTalk',             'para' => 'A license plate-based messaging app we built to enable drivers to communicate safely. It enhanced road safety, facilitated travel connections, and maintained user privacy without sharing personal data.', 'play_store_link' => 'https://play.google.com/store/apps/details?id=com.platetalk&hl=en', 'app_store_link' => 'https://apps.apple.com/us/app/platetalk/id6702023236', 'logo' => '/case-study-card/plate.png', 'logo_width' => '70', 'logo_height' => '70', 'page_link' => '/case-studies/plate-talk/' ),
			array( 'bg_image' => '/case-study-card/case9.webp',  'image' => '/case-study-card/mob9.webp',  'width' => 328, 'height' => 358, 'heading' => 'Fit for Golf 50+',      'para' => 'A golf-fitness app we developed for players aged 50+ integrating physical, mental, and spiritual coaching. It boosted performance, improved fitness, sharpened focus, and united a thriving community.', 'logo' => '/case-study-card/golf-2.png', 'logo_width' => '71', 'logo_height' => '71', 'page_link' => '/case-studies/fitforgolf/' ),
			array( 'bg_image' => '/case-study-card/case10.webp', 'image' => '/case-study-card/mob10.webp', 'width' => 248, 'height' => 368, 'heading' => 'Built by Determination', 'para' => 'A fitness app we built motivating users with custom workouts, progress tracking, and community support. It helped users stay consistent, surpass goals, and create lasting healthy routines over time.', 'logo' => '/case-study-card/build.png', 'logo_width' => '198', 'logo_height' => '44', 'page_link' => '/case-studies/built-by-determination/' ),
			array( 'bg_image' => '/case-study-card/case1.webp',  'image' => '/case-study-card/mob1.webp',  'width' => 372, 'height' => 354, 'heading' => 'Haughton\'s RxPak',     'para' => 'A HIPAA-compliant pharmacy app we built to speed up refills and improve patient access. It streamlined workflows, cut delays, and gave users a safer, faster way to manage prescriptions efficiently.', 'play_store_link' => 'https://play.google.com/store/apps/details?id=com.rxpak', 'app_store_link' => 'https://apps.apple.com/us/app/rxpak/id6471603779', 'logo' => '/case-study-card/haughton.webp', 'logo_width' => '98', 'logo_height' => '39' ),
			array( 'bg_image' => '/case-study-card/case2.webp',  'image' => '/case-study-card/mob2.webp',  'width' => 277, 'height' => 393, 'heading' => 'Mind Circuit',           'para' => 'A mental wellness app we built that tracks moods and builds coping strategies. It empowered users to reduce anxiety, improve self-awareness, and create lasting emotional well-being every day.', 'play_store_link' => 'https://play.google.com/store/apps/details?id=com.app.ageOfUncertainty&hl=en', 'app_store_link' => 'https://apps.apple.com/in/app/aou-coaching/id6478664305', 'logo' => '/case-study-card/mind.png', 'logo_width' => '67', 'logo_height' => '67' ),
			array( 'bg_image' => '/case-study-card/case3.webp',  'image' => '/case-study-card/mob3.webp',  'width' => 309, 'height' => 326, 'heading' => 'Pure\'d Disc Golf',      'para' => 'A disc-golf network app we built that connects players and helps organize rounds nearby. It improved skills, coordinated local games, and strengthened active disc golf communities effectively.', 'play_store_link' => 'https://play.google.com/store/apps/details?id=com.pured&hl=en', 'app_store_link' => 'https://apps.apple.com/us/app/pured/id6473019669', 'logo' => '/case-study-card/pure.png', 'logo_width' => '65', 'logo_height' => '65' ),
			array( 'bg_image' => '/case-study-card/case4.webp',  'image' => '/case-study-card/mob4.webp',  'width' => 321, 'height' => 326, 'heading' => 'Preferred Ride',         'para' => 'A driver-side app we developed letting drivers manage schedules, earnings, and tips. It improved transparency, enabled efficient tracking, and supported reliable ride service delivery daily.', 'play_store_link' => 'https://play.google.com/store/apps/details?id=com.preferredride.driver', 'logo' => '/case-study-card/ride.png', 'logo_width' => '65', 'logo_height' => '65' ),
			array( 'bg_image' => '/case-study-card/case5.webp',  'image' => '/case-study-card/mob5.webp',  'width' => 290, 'height' => 326, 'heading' => 'NynJa Workspace',        'para' => 'A secure collaboration app we built to unify chat, video calls, file sharing, and live translation. It boosted productivity, removed language barriers, and kept enterprise data fully protected worldwide.', 'play_store_link' => 'https://play.google.com/store/apps/details?id=com.nynja.mobile.communicator&hl=en', 'logo' => '/case-study-card/nynja.png', 'logo_width' => '71', 'logo_height' => '65' ),
		),
	),
	'components' => array(
		array( 'name' => 'PortfolioBanner',      'modifier_class' => '' ),
		array( 'name' => 'PortfolioCardListing', 'modifier_class' => '' ),
		array( 'name' => 'PortfolioGrid',        'modifier_class' => '' ),
	),
);
