<?php
defined( 'ABSPATH' ) || exit;

return array(
	'schemas'    => array(),
	'mock_data'  => array(
		'industry_banner'    => array(
			'title'            => 'Leading WordPress Development Company',
			'para'             => 'TechnBrains is the leading WordPress development company in the USA. With over a decade of experience, our top 1% of WordPress experts create engaging websites that reflect your brand identity, propel your business, and optimize the functionality of your content management system.',
			'banner_img_src'   => '/cms/wordpress/banner.webp',
			'banner_img_width' => 780,
			'banner_img_height'=> 520,
			'banner_img_alt'   => 'WordPress Development Company',
			'second_button'    => true,
		),
		'dedicated_lang_desc'=> array(
			'para_html' => 'TechnBrains is a well-established WordPress Development company with over 10 years of experience specializing in creating custom solutions. Our dedicated team of WordPress Developers is committed to delivering excellence, ensuring top-notch security, and providing flexible solutions. We are dedicated to providing dependable services with 24/7 support. Our team specializes in creating custom WordPress websites that are designed to meet your unique needs, effectively strengthening and enhancing your brand. Choose excellence. Choose TechnBrains.',
		),
		'language_services'  => array(
			'head_text' => 'WordPress Development Services',
			'para_text' => 'Our expertise in WordPress Development solutions encompasses a diverse range of services, with our WordPress developers delivering top-quality solutions to meet your every need.',
			'btn_text'  => 'Book AN APPOINTMENT',
			'anchor'    => false,
			'listing'   => array(
				array( 'img_src' => '/cms/wordpress/d1.png',  'width' => '80', 'height' => '80', 'alt' => 'WordPress Theme Development',    'list_head' => 'WordPress Theme Development',    'list_para' => 'We craft high-quality, aesthetically savvy themes that are fully functional and responsive, adhering to the latest trends and best practices in the industry.' ),
				array( 'img_src' => '/cms/wordpress/d2.png',  'width' => '80', 'height' => '80', 'alt' => 'WordPress Plugin Development',   'list_head' => 'WordPress Plugin Development',   'list_para' => 'Our experienced WordPress developers create custom plugins from scratch, ensuring they fulfill your unique requirements and integrate seamlessly with your website.' ),
				array( 'img_src' => '/cms/wordpress/d3.png',  'width' => '80', 'height' => '80', 'alt' => 'WordPress Migration Services',   'list_head' => 'WordPress Migration Services',   'list_para' => 'Trust our professionals to handle migration seamlessly, minimizing the risks of data loss, leaks, or downtime during the transition to a new system.' ),
				array( 'img_src' => '/cms/wordpress/d4.png',  'width' => '80', 'height' => '80', 'alt' => 'WordPress Integrations',         'list_head' => 'WordPress Integrations',         'list_para' => 'Our services ensure that your website and third-party tools and applications work cohesively and securely together.' ),
				array( 'img_src' => '/cms/wordpress/d5.png',  'width' => '80', 'height' => '80', 'alt' => 'Custom WordPress Development',   'list_head' => 'Custom WordPress Development',   'list_para' => 'Experience the boundless capabilities of WordPress through the creation of custom plugins and seamless API integrations. Our skilled developers are poised to bring your ideas to life or seamlessly merge them into your existing teams to craft exceptional websites—Expert Custom WordPress Development for world-class sites.' ),
				array( 'img_src' => '/cms/wordpress/d6.png',  'width' => '80', 'height' => '80', 'alt' => 'Design and Front-end (Themes)',  'list_head' => 'Design and Front-end (Themes)',  'list_para' => 'exceptional design is non-negotiable at TechnBrains. Our skilled designers optimize UI and UX while seamlessly integrating your company\'s brand and vision into your website. Elevate your digital presence with captivating themes that leave a lasting impression.' ),
				array( 'img_src' => '/cms/wordpress/d7.png',  'width' => '80', 'height' => '80', 'alt' => 'WordPress Security',             'list_head' => 'WordPress Security',             'list_para' => 'Protecting your website is paramount. Our dedicated security consultants ensure the safety and security of your site remains a top priority. They conduct comprehensive code audits, scan for vulnerabilities, and collaborate with your team at any stage of the development process to fortify your defenses.' ),
				array( 'img_src' => '/cms/wordpress/d8.png',  'width' => '80', 'height' => '80', 'alt' => 'Multisite',                      'list_head' => 'Multisite',                      'list_para' => 'Leverage the expertise of our senior developers to create a network of interconnected sites or blogs or collaborate with them to access other existing Multisite networks. Seamlessly manage multiple online platforms with ease.' ),
				array( 'img_src' => '/cms/wordpress/d9.png',  'width' => '80', 'height' => '80', 'alt' => 'BuddyPress',                     'list_head' => 'BuddyPress',                     'list_para' => 'BuddyPress is a versatile suite of components that empowers your website with the functionality of a social network. It offers incredible add-on features and customizability, designed with a keen focus on extensibility. Enhance your site\'s social engagement with BuddyPress.' ),
				array( 'img_src' => '/cms/wordpress/d10.png', 'width' => '80', 'height' => '80', 'alt' => 'WP Engine',                      'list_head' => 'WP Engine',                      'list_para' => 'When it comes to hosting, WP Engine stands out as a leader in managed WordPress hosting. Hosting 5% of all online traffic on the sites it hosts, WP Engine offers enhanced security, faster response times, and minimal downtime. Experience the reliability and performance boost with WP Engine.' ),
			),
		),
		'dev_process_two'    => array(
			'main_title' => 'Our WordPress expertise',
			'lang_title' => 'Top-Notch WordPress Development Company',
			'lang_para'  => 'As a leading WordPress development company, we specialize in delivering top-tier custom WordPress development services tailored to your unique requirements. Our dedicated team consists of expertly matched talent, including senior software engineers, skilled designers, proficient project managers, and experienced product managers, all with vast expertise across a multitude of technologies. Whether you need WordPress design and development services or comprehensive WordPress development solutions, our seasoned professionals are here to craft a web presence that aligns seamlessly with your business objectives. When it comes to WordPress website development services, trust in our custom WordPress development to bring your vision to life, ensuring that every aspect is carefully managed and executed.',
			'listing'    => array(
				array( 'img_src' => '/cms/wordpress/dp-1.png', 'title' => 'Streamlined UX-Interface',       'para' => 'With its simple-to-use platform, WordPress paves the way for a streamlined user experience interface. Concentrate on the essence of your content and user engagement while we ensure the technology is hassle-free.' ),
				array( 'img_src' => '/cms/wordpress/dp-2.png', 'title' => 'Tailored Website Personalization','para' => 'Our team of talented developers collaborates closely with you to create a custom design that beautifully embodies your brand. Achieve a level of personalization and uniqueness that stands out.' ),
				array( 'img_src' => '/cms/wordpress/dp-3.png', 'title' => 'Elevate Brand Awareness',        'para' => 'A fully functional WordPress website serves as a powerful tool to elevate brand awareness. Make a memorable impression on your target audience through a platform optimized for visibility.' ),
				array( 'img_src' => '/cms/wordpress/dp-4.png', 'title' => 'SEO Support',                    'para' => 'WordPress not only offers user-friendly experiences but also supports effective SEO practices. Your content becomes more accessible to your audience, whether you\'re improving web design or implementing SEO techniques.' ),
				array( 'img_src' => '/cms/wordpress/dp-1.png', 'title' => 'Streamlined UX-Interface',       'para' => 'With its simple-to-use platform, WordPress paves the way for a streamlined user experience interface. Concentrate on the essence of your content and user engagement while we ensure the technology is hassle-free.' ),
				array( 'img_src' => '/cms/wordpress/dp-2.png', 'title' => 'Tailored Website Personalization','para' => 'Our team of talented developers collaborates closely with you to create a custom design that beautifully embodies your brand. Achieve a level of personalization and uniqueness that stands out.' ),
				array( 'img_src' => '/cms/wordpress/dp-3.png', 'title' => 'Elevate Brand Awareness',        'para' => 'A fully functional WordPress website serves as a powerful tool to elevate brand awareness. Make a memorable impression on your target audience through a platform optimized for visibility.' ),
				array( 'img_src' => '/cms/wordpress/dp-4.png', 'title' => 'SEO Support',                    'para' => 'WordPress not only offers user-friendly experiences but also supports effective SEO practices. Your content becomes more accessible to your audience, whether you\'re improving web design or implementing SEO techniques.' ),
			),
		),
		'dev_process'        => array(
			'main_title' => 'Our expertise ensures a delightful user experience',
			'lang_title' => 'Wordpress Application Development Process',
			'classes'    => 'gray-bg',
			'listing'    => array(
				array( 'number' => '01', 'title' => 'Define',  'para' => 'your project with precision, initiating your WordPress development journey. Make strategic technology choices, capture user roles, and outline personas.' ),
				array( 'number' => '02', 'title' => 'Design',  'para' => 'the user experience and aesthetics, shaping your website\'s look and feel. Prioritize features to create a user-centric journey and craft a plan for the site\'s launch.' ),
				array( 'number' => '03', 'title' => 'Deliver', 'para' => 'results with detailed specs, time, and cost estimates. Our top-notch WordPress development experts are ready to execute your plan.' ),
				array( 'number' => '04', 'title' => 'Develop', 'para' => 'your WordPress site under our watchful eye. Our commitment to quality assurance, DevOps, and deployment ensures a seamless experience. We keep you informed and updated throughout, using your preferred project management tool for clear communication.' ),
				array( 'number' => '01', 'title' => 'Define',  'para' => 'your project with precision, initiating your WordPress development journey. Make strategic technology choices, capture user roles, and outline personas.' ),
				array( 'number' => '02', 'title' => 'Design',  'para' => 'the user experience and aesthetics, shaping your website\'s look and feel. Prioritize features to create a user-centric journey and craft a plan for the site\'s launch.' ),
				array( 'number' => '03', 'title' => 'Deliver', 'para' => 'results with detailed specs, time, and cost estimates. Our top-notch WordPress development experts are ready to execute your plan.' ),
				array( 'number' => '04', 'title' => 'Develop', 'para' => 'your WordPress site under our watchful eye. Our commitment to quality assurance, DevOps, and deployment ensures a seamless experience. We keep you informed and updated throughout, using your preferred project management tool for clear communication.' ),
			),
		),
		'proposal'           => array(
			'head_html' => '<h2>Experience expert WordPress development - turn your vision into stunning reality!</h2>',
			'btn_text'  => 'Build Now',
			'btn_url'   => '/staff-augmentation/',
			'anchor'    => true,
		),
		'dev_services'       => array(
			'subtitle' => 'WordPress Professionals at Your Service',
			'title'    => 'Why Choose TechnBrains For Wordpress Development?',
			'para'     => '',
			'listing'  => array(
				array(
					'img_src' => '/cms/wordpress/d-banner.webp',
					'width'   => '558',
					'height'  => '497',
					'content' => array(
						array( 'title' => 'Decade of WordPress Technical Expertise',    'para' => 'We possess 10+ Years of WordPress Technical Expertise, with a team of seasoned WordPress developers who understand the platform inside out. Our track record is a testament to our capability to deliver successful projects, and we bring our technical expertise and in-depth knowledge of the custom software industry to transform your vision into reality.' ),
						array( 'title' => 'Starting with "Why" for Tailored Solutions', 'para' => 'At TechnBrains, we begin with Why, not What. We adopt a listening and understanding approach, delving into your business\'s unique challenges and opportunities. We prioritize a thorough analysis before diving into technology. This helps us create solutions tailored to your specific needs.' ),
						array( 'title' => 'Bridging Technical and Business Expertise',  'para' => 'Our team is fluent in both Technical and Business, effectively bridging the gap between your business requirements and technical implementation. With diverse expertise on board, we translate complex technical concepts into meaningful insights, ensuring crystal-clear communication that leads to practical solutions for your business.' ),
						array( 'title' => 'Simplicity in Complex Problem Solving',      'para' => 'TechnBrains believes in bringing Simplicity to Chaos. We advocate the pragmatic use of technology and prioritize simple, cost-effective solutions over high capital expenditures driven by tech trends. We make technology work for your benefit, ensuring it aligns with your business objectives.' ),
						array( 'title' => 'Commitment to Complete Transparency',        'para' => 'Complete Transparency is what we are proud of at TechnBrains. We stand by our word and demonstrate our commitment through actions. When we make a promise, we deliver tangible results. Our team is built on integrity, reliability, and accountability, emphasizing a consistent alignment of promises with actions. You can trust us to uphold transparency and consistently deliver on our commitments.' ),
					),
				),
			),
		),
		'we_offer'           => array(
			'subtitle' => 'Discover topnotch wordpress services',
			'title'    => 'Other services that we Excel in',
			'para'     => 'At our one-stop destination, we provide everything you need to create a dynamic and impactful mobile experience.',
			'listing'  => array(
				array( 'img_src' => '/cms/flutter-flow/w2.png', 'title' => 'Figma Design Solutions',       'para' => 'Crafting visually stunning and user-centric interfaces using the power of Figma, ensuring seamless collaboration and design innovation.' ),
				array( 'img_src' => '/cms/web-design/w3.png',   'title' => 'Flutter Flow Integration',     'para' => 'Empowering your mobile app development journey with the efficiency and flexibility of Flutter Flow, delivering cross-platform excellence.' ),
				array( 'img_src' => '/cms/flutter-flow/w1.png', 'title' => 'Mobile App Development',       'para' => 'Our team specializes in crafting seamless and high-performance apps that resonate with your audience. Let us help you elevate your business and stay ahead of the competition.' ),
				array( 'img_src' => '/cms/flutter-flow/w3.png', 'title' => 'Web Design and Development',   'para' => 'From concept to deployment, our web design and development services ensure robust, scalable, and tailored solutions for your digital success.' ),
				array( 'img_src' => '/cms/flutter-flow/w2.png', 'title' => 'Figma Design Solutions',       'para' => 'Crafting visually stunning and user-centric interfaces using the power of Figma, ensuring seamless collaboration and design innovation.' ),
				array( 'img_src' => '/cms/web-design/w3.png',   'title' => 'Flutter Flow Integration',     'para' => 'Empowering your mobile app development journey with the efficiency and flexibility of Flutter Flow, delivering cross-platform excellence.' ),
				array( 'img_src' => '/cms/flutter-flow/w1.png', 'title' => 'Mobile App Development',       'para' => 'Our team specializes in crafting seamless and high-performance apps that resonate with your audience. Let us help you elevate your business and stay ahead of the competition.' ),
				array( 'img_src' => '/cms/flutter-flow/w3.png', 'title' => 'Web Design and Development',   'para' => 'From concept to deployment, our web design and development services ensure robust, scalable, and tailored solutions for your digital success.' ),
			),
		),
		'faqs'               => array(
			'head_text' => 'Things you might want to know',
			'faq_image' => false,
			'listing'   => array(
				array( 'faqhead' => 'How do I hire the best WordPress developer?',                                                            'faqbody' => 'Hiring the best WordPress developer involves thorough research and consideration. Begin by seeking a reputable WordPress development company that specializes in custom WordPress development services. Evaluate their portfolio to ensure it showcases projects similar to your requirements. Look for a track record of successful deliveries, and inquire about their expertise in WordPress development solutions, especially in enterprise WordPress development, if you have extensive needs. Understand the pricing models they offer, such as fixed project costs, hourly rates, or retainers, and clarify any potential hidden or additional costs. To find experienced WordPress developers, explore online platforms and job boards, or consult industry peers for recommendations.' ),
				array( 'faqhead' => 'Why is custom WordPress development better for your business?',                                         'faqbody' => 'Custom WordPress development is a superior choice for your business because it provides a tailor-made solution that perfectly aligns with your unique objectives. Unlike generic themes or templates, custom development ensures that your website stands out, is fully scalable, and caters precisely to your needs. This approach allows you to implement specific features, design elements, and functionality essential for your business\'s success. It empowers you with a distinct online presence, offering WordPress website development services that are fine-tuned to your specific requirements.' ),
				array( 'faqhead' => 'What is enterprise WordPress development?',                                                              'faqbody' => 'Enterprise WordPress development entails the creation of highly customized and scalable solutions designed to meet the specific requirements of large businesses and organizations. This level of custom WordPress development is tailored to cater to the unique needs of enterprise clients. It often involves complex integrations, advanced security features, and the capability to handle high volumes of traffic. Enterprise WordPress development is aimed at empowering large corporations with websites that efficiently support their operations and marketing initiatives.' ),
				array( 'faqhead' => 'How much does it cost to build a WordPress theme?',                                                     'faqbody' => 'The cost of building a WordPress theme can vary widely, contingent on various factors. These factors encompass the theme\'s complexity, the features required, and the WordPress theme development services provider you choose. Prices can range from a few hundred dollars for a basic theme to thousands for a custom, feature-rich theme. To get an accurate estimate, it is advisable to consult with a reputable custom WordPress development company that can provide a detailed quote based on your specific requirements and business goals.' ),
				array( 'faqhead' => 'What pricing models do you offer: fixed project cost, hourly rate, or retainer?',                        'faqbody' => 'We offer various pricing models to cater to your unique preferences and project needs. Our pricing models include fixed project costs, hourly rates, and retainer agreements. The choice of model depends on the complexity and scope of your project, as well as your financial planning. We can engage in discussions to determine which model best aligns with your custom WordPress development needs.' ),
				array( 'faqhead' => 'Are there any hidden or additional costs that I should be aware of?',                                    'faqbody' => 'Transparency is at the core of our pricing structure. We ensure that there are no hidden costs, and the expense will be clearly defined in the initial proposal. Any potential additional costs, such as third-party plugin licenses or hosting fees, will be discussed and agreed upon in advance. We are committed to providing clear and comprehensive information on all expenses associated with your project, ensuring transparency and peace of mind.' ),
				array( 'faqhead' => 'Why should I choose WordPress as the platform for my website?',                                          'faqbody' => 'Opting for WordPress as your website platform is a strategic choice. WordPress is renowned for its versatility and robustness. It\'s known for its user-friendliness and scalability. With its extensive library of themes and plugins, you can create a professional, SEO-friendly website that effectively aligns with your business objectives. WordPress is cost-effective and easy to maintain, making it a popular choice for businesses of all sizes. Its vast community and abundant resources make it an excellent choice for anyone seeking a robust web platform complemented by WordPress web development services tailored to your needs.' ),
				array( 'faqhead' => 'Where can I find and hire experienced WordPress developers?',                                             'faqbody' => 'Finding and hiring experienced WordPress developers can be approached in various ways. You can explore online platforms like Upwork, Freelancer, and Toptal, which offer access to a broad talent pool. Job boards such as Indeed and LinkedIn are also valuable resources for discovering potential candidates. However, the most effective approach may be to consult with a reputable WordPress development company that offers custom WordPress development services. Such companies typically have a team of experienced developers ready to address your unique requirements and ensure a successful project, saving you time and effort in the hiring process.' ),
			),
		),
	),
	'components' => array(
		array( 'name' => 'industry-banner',     'modifier_class' => '' ),
		array( 'name' => 'dedicated-lang-desc', 'modifier_class' => '' ),
		array( 'name' => 'language-services',   'modifier_class' => '' ),
		array( 'name' => 'development-process', 'modifier_class' => '', 'args' => array( 'data_key' => 'dev_process_two' ) ),
		array( 'name' => 'development-process', 'modifier_class' => '', 'args' => array( 'data_key' => 'dev_process' ) ),
		array( 'name' => 'proposal',            'modifier_class' => 'wordpress' ),
		array( 'name' => 'development-services','modifier_class' => 'white-bg' ),
		array( 'name' => 'we-offer',            'modifier_class' => 'gray-bg' ),
		array( 'name' => 'main-faqs',           'modifier_class' => '' ),
		array( 'name' => 'testimonials',        'modifier_class' => '' ),
	),
);
