<?php
defined('ABSPATH') || exit;

return array(
	'schemas'    => array(
		array(
			'@context'    => 'https://schema.org',
			'@type'       => 'WebPage',
			'name'        => 'Hire JavaScript Developer for Interactive Websites | Technbrains',
			'description' => 'Make your websites interactive and engaging. Hire JavaScript developers from TechnBrains for dynamic and user-friendly web solutions.',
			'url'         => 'https://www.technbrains.com/hire-javascript-developer',
		),
		array(
			'@context'   => 'https://schema.org',
			'@type'      => 'FAQPage',
			'mainEntity' => array(
				array('@type' => 'Question', 'name' => 'How much does it cost to Hire a JavaScript Developer?',             'acceptedAnswer' => array('@type' => 'Answer', 'text' => 'The cost to hire JavaScript developers can vary based on factors such as experience, location, and project complexity. Freelance JavaScript developers may charge hourly rates, typically ranging from $25 to $150, while hiring a dedicated JavaScript developer through a company like TechnBrains might involve a monthly or project-based fee, starting from $2000.')),
				array('@type' => 'Question', 'name' => 'How much time will it take to develop a JavaScript Project?',        'acceptedAnswer' => array('@type' => 'Answer', 'text' => 'The timeline for JavaScript project development depends on project size and complexity. Simple projects may take a few weeks, while complex applications might require several months.')),
				array('@type' => 'Question', 'name' => 'What development process do you follow?',                            'acceptedAnswer' => array('@type' => 'Answer', 'text' => 'We follow an agile development process for JavaScript development services. This iterative approach ensures flexibility, transparency, and regular client feedback.')),
				array('@type' => 'Question', 'name' => 'What if I want to change the developers in the mid of the project?', 'acceptedAnswer' => array('@type' => 'Answer', 'text' => 'If you choose to hire JavaScript developers from TechnBrains and need to make changes during the project, we can discuss options to accommodate your preferences.')),
				array('@type' => 'Question', 'name' => 'Is there any hidden cost I should consider for Angular Development Services?', 'acceptedAnswer' => array('@type' => 'Answer', 'text' => 'At TechnBrains, we maintain transparency in our pricing. There are no hidden costs for our JavaScript development services.')),
				array('@type' => 'Question', 'name' => 'Do you provide NDA Signed Document for my project?',                'acceptedAnswer' => array('@type' => 'Answer', 'text' => 'Yes, we prioritize your project\'s confidentiality and offer NDA (Non-Disclosure Agreement) documents.')),
				array('@type' => 'Question', 'name' => 'Do I own the code authority of the project?',                       'acceptedAnswer' => array('@type' => 'Answer', 'text' => 'Absolutely! When you hire dedicated JavaScript developers from TechnBrains, you retain full code ownership and authority.')),
				array('@type' => 'Question', 'name' => 'Do you provide free after-sales support and maintenance?',           'acceptedAnswer' => array('@type' => 'Answer', 'text' => 'Yes, we offer post-launch support and maintenance for your JavaScript project.')),
				array('@type' => 'Question', 'name' => 'Why should I choose TechnBrains to hire JavaScript developers?',     'acceptedAnswer' => array('@type' => 'Answer', 'text' => 'Choosing TechnBrains to hire JavaScript developers ensures access to a highly skilled and experienced team. We offer comprehensive services, transparent pricing, NDA protection, full code ownership, and ongoing support.')),
			),
		),
	),
	'mock_data'  => array(
		'banner' => array(
    'head_text'   => 'Hire ReactJS Developers for Scalable Frontend Web Apps',
    'para_text'   => 'Hire ReactJS developers from TechnBrains to build fast, responsive, and scalable web applications, dashboards, SaaS platforms, portals, and customer-facing interfaces. Our ReactJS developers work with React, JavaScript, TypeScript, Redux, Next.js, REST APIs, GraphQL, component libraries, design systems, and modern frontend architecture. Whether you need a ReactJS developer to support your in-house team or a dedicated frontend team to build your product interface, we help you choose the right hiring model.',
    'span_text'   => 'Ready to elevate your frontend development? Hire ReactJS Developers now and unlock the potential of dynamic user interfaces!',
    'form_title'  => 'Deploy React Projects',
    'form_para'   => 'With Top React Developers we are here to launch your app with a bang!',
    'banner_list' => array(
        array( 'li_list' => 'Ensure project confidentiality and data security by signing NDA agreements.' ),
        array( 'li_list' => 'Save up to 70% on development costs when you hire React JS developers.' ),
        array( 'li_list' => 'Expertise in JavaScript, including ES5/ES6/ES7+ and Babel.' ),
        array( 'li_list' => 'Proficiency in Redux, Redux-Saga, Flow, and React DND.' ),
        array( 'li_list' => 'Ability to efficiently utilize cloud services such as AWS, GCP, and Azure for React Redux development.' ),
    ),
),
		'steps_hire'       => array(
			'sub_head' => 'Hire JavaScript Developers in Just 3 Easy Steps',
			'para_text' => 'Streamline your development process with ease – Hire JavaScript developers in just three simple steps and unlock the potential of dynamic frontend solutions',
			'box_list' => array(
				array('number' => '01', 'title' => 'Choose your Engagement Model',  'content' => array('Select the engagement model that suits your project and budget.'),                                                                                                        'image_src' => '/hire/boxone-img.webp',   'width' => 225, 'height' => 267),
				array('number' => '02', 'title' => 'Pick JavaScript Developers',    'content' => array('Handpick JavaScript developers from our talented pool of experts and interview them for their technical expertise.'),                                                    'image_src' => '/hire/boxtwo-img.webp',   'width' => 327, 'height' => 267),
				array('number' => '03', 'title' => 'Onboard JavaScript Developers', 'content' => array('Onboard your chosen JavaScript Developer seamlessly for a productive collaboration.'),                                                                                   'image_src' => '/hire/boxthree-img.webp', 'width' => 334, 'height' => 267),
			),
		),
		'expert'           => array(
			'sub_head'   => 'Hire JavaScript Developers for Your Next Project',
			'para_text'  => 'Start your journey to exceptional web and app development by hiring JavaScript developers. Our skilled professionals bring a wealth of experience in JavaScript, delivering robust, dynamic, and user-friendly solutions tailored to your unique needs. Elevate your digital presence and achieve your business goals with our expert team. Choose from Hourly, Part-time and Full-time hiring to get started. Secure your project\'s success with us today!',
			'expert_box' => array(
				array(
					'src' => '/hire/angular/clock.png',
					'width' => 85,
					'height' => 85,
					'head' => 'Hourly Hiring',
					'expert_list' => array(
						array('item' => 'Dedicated 8 Hrs/day for consistent progress.'),
						array('item' => 'Enjoy adaptability with a minimum 30-day engagement.'),
						array('item' => 'Simplify payments with convenient monthly billing cycles.'),
					),
				),
				array(
					'src' => '/hire/angular/full.png',
					'width' => 85,
					'height' => 85,
					'head' => 'Full Time Hiring',
					'expert_list' => array(
						array('item' => 'Dedicated 8 Hrs/day for consistent progress.'),
						array('item' => 'Enjoy adaptability with a minimum 30-day engagement.'),
						array('item' => 'Simplify payments with convenient monthly billing cycles.'),
					),
				),
				array(
					'src' => '/hire/angular/part.png',
					'width' => 85,
					'height' => 85,
					'head' => 'Part Time Hiring',
					'expert_list' => array(
						array('item' => 'Dedicated 8 Hrs/day for consistent progress.'),
						array('item' => 'Enjoy adaptability with a minimum 30-day engagement.'),
						array('item' => 'Simplify payments with convenient monthly billing cycles.'),
					),
				),
			),
		),
		'hire_cta_1'       => array(
			'title'             => 'READY TO START YOUR DREAM PROJECT?',
			'para'              => 'WE HAVE A TEAM TO GET YOU THERE.',
			'primary_button'    => true,
			'secondary_button'  => false,
			'primary_btn_title' => 'GET IN TOUCH',
			'primary_btn_popup' => true,
		),
		'hire_choose' => array(
    'sub_head'    => 'Engagement Models to Hire ReactJS Developers',
    'para_text'   => 'Choose the model based on your internal capacity, UI/UX complexity, and delivery roadmap.',
    'choose_list' => array(
        array( 'src' => '/hire/laravel/image1.png', 'width' => 88, 'height' => 88, 'head' => 'Staff Augmentation',   'para' => 'Ideal For: Teams needing specialized ReactJS, Redux, or frontend support to boost existing development velocity. Key Advantage: Integrate pre-vetted engineers into your workflow while maintaining full control over architecture. When to Choose: Best for supporting internal sprints, building new UI components, or scaling your frontend capacity.' ),
        array( 'src' => '/hire/laravel/image2.png', 'width' => 88, 'height' => 88, 'head' => 'Software Outsourcing', 'para' => 'Ideal For: Startups and SMBs looking for a managed approach to deliver clearly defined React modules or web apps. Key Advantage: Hand off the end-to-end management of frontend development, API integration, and QA to TechnBrains. When to Choose: Best for milestone-based delivery where you need a turnkey solution for a specific project scope.' ),
        array( 'src' => '/hire/laravel/image3.png', 'width' => 88, 'height' => 88, 'head' => 'Dedicated Teams',      'para' => 'Ideal For: Businesses building long-term SaaS platforms, enterprise web portals, or complex React ecosystems. Key Advantage: A fully integrated team of developers, designers, and DevOps working exclusively on your product vision. When to Choose: Best for evolving roadmaps that require consistent focus, deep product knowledge, and scalable growth.' ),
    ),
),
		'skills'           => array(
			'sub_head'  => 'Skilled JavaScript Developers at TechnBrains',
			'para_text' => 'TechnBrains offers a team of highly skilled JavaScript developers. Our experts are well-versed in creating dynamic and efficient frontend solutions, ensuring top-notch quality and innovation in every project we undertake.',
			'skill_box' => array(
				array(
					'head'       => 'Technical',
					'sub_head'   => 'JavaScript Developers Technical Skills',
					'skill_list' => array(
						array('item' => 'Profound expertise in core JavaScript, including ES6 and beyond.'),
						array('item' => 'Proficiency in front-end technologies such as HTML5, CSS3, and responsive design.'),
						array('item' => 'Mastery of popular JavaScript libraries and frameworks like React, Angular, or Vue.js.'),
						array('item' => 'Strong understanding of asynchronous programming and promises.'),
						array('item' => 'Knowledge of RESTful API integration and web services.'),
						array('item' => 'Experience with testing frameworks like Jest or Mocha.'),
						array('item' => 'Version control proficiency with Git.'),
					),
				),
				array(
					'head'       => 'Non-Technical',
					'sub_head'   => 'JavaScript Developers Non-Technical Skills',
					'skill_list' => array(
						array('item' => 'Effective communication and collaboration within development teams.'),
						array('item' => 'Problem-solving and critical thinking abilities to troubleshoot complex issues.'),
						array('item' => 'Time management and project planning skills for efficient development.'),
						array('item' => 'Adaptability to rapidly evolving technology trends.'),
						array('item' => 'Attention to detail to ensure code quality and reliability.'),
						array('item' => 'Strong work ethic and dedication to meeting project deadlines.'),
						array('item' => 'Continuous learning and staying updated with industry best practices.'),
					),
				),
			),
		),
		'hire_table'       => array(
			'sub_head'   => 'Why Hire JavaScript developers from TechnBrains over freelance or in-house developers?',
			'para_text'  => 'Hiring JavaScript developers from TechnBrains offers a distinct advantage over freelance or in-house developers. Our team brings a depth of expertise, collaborative synergy, and reliability that ensures streamlined development, consistent quality, and access to a diverse skill set, making us the ideal choice for your project\'s success.',
			'table_list' => array(
				array('id' => 1,  'hiring' => 'Time to Get Right Developers',          'in_house' => '4 - 12 weeks',         'technbrains' => '1 day - 2 weeks',                      'freelancer' => '1 - 12 weeks'),
				array('id' => 2,  'hiring' => 'Time to Start a Project',               'in_house' => '2 - 10 weeks',         'technbrains' => '1 day - 2 weeks',                      'freelancer' => '1 - 10 weeks'),
				array('id' => 3,  'hiring' => 'Recurring Cost of Training & Benefits', 'in_house' => '$10,000 - $30,000',    'technbrains' => '0',                                    'freelancer' => '0'),
				array('id' => 4,  'hiring' => 'Time to Scale Size of the Team',        'in_house' => '4 - 16 weeks',         'technbrains' => '48 hours - 1 week',                    'freelancer' => '1 - 12 weeks'),
				array('id' => 5,  'hiring' => 'Pricing (weekly average)',               'in_house' => '2.5 X',                'technbrains' => '1.5 X',                                'freelancer' => '1 X'),
				array('id' => 6,  'hiring' => 'Project Failure Risk',                  'in_house' => 'Low',                  'technbrains' => 'Extremely low, we have a 98% success ratio', 'freelancer' => 'Very High'),
				array('id' => 7,  'hiring' => 'Developers Backed by a Delivery Team',  'in_house' => 'Some',                 'technbrains' => 'Yes',                                  'freelancer' => 'No'),
				array('id' => 8,  'hiring' => 'Dedicated Resources',                   'in_house' => 'Yes',                  'technbrains' => 'Yes',                                  'freelancer' => 'No'),
				array('id' => 9,  'hiring' => 'Shadow Resource',                       'in_house' => 'Costly',               'technbrains' => 'Yes',                                  'freelancer' => 'No'),
				array('id' => 10, 'hiring' => 'Project Manager',                       'in_house' => 'Extra Cost',           'technbrains' => 'Minimal cost',                         'freelancer' => 'No'),
				array('id' => 11, 'hiring' => 'Quality Assurance Check',               'in_house' => 'Extra Cost',           'technbrains' => 'Assured',                              'freelancer' => 'No'),
				array('id' => 12, 'hiring' => 'Query Support',                         'in_house' => 'High',                 'technbrains' => '24 Hours Assurance',                   'freelancer' => 'No'),
				array('id' => 13, 'hiring' => 'Tools & Environment',                   'in_house' => 'Depend on Team',       'technbrains' => 'High',                                 'freelancer' => 'Uncertain'),
				array('id' => 14, 'hiring' => 'Agile Development Methodology',         'in_house' => 'May Be',               'technbrains' => 'Yes',                                  'freelancer' => 'No'),
				array('id' => 15, 'hiring' => 'Impact Due to Turnover',                'in_house' => 'High',                 'technbrains' => 'None',                                 'freelancer' => 'High'),
				array('id' => 16, 'hiring' => 'Structured Training Programs',          'in_house' => 'Some',                 'technbrains' => 'Yes',                                  'freelancer' => 'No'),
				array('id' => 17, 'hiring' => 'Communications',                        'in_house' => 'Seamless',             'technbrains' => 'Seamless',                             'freelancer' => 'Uncertain'),
				array('id' => 18, 'hiring' => 'Termination Costs',                     'in_house' => 'High',                 'technbrains' => 'None',                                 'freelancer' => 'None'),
				array('id' => 19, 'hiring' => 'Assured Work Rigor',                    'in_house' => '40 hrs/week',          'technbrains' => '40 hrs/week',                          'freelancer' => 'Not Sure'),
			),
		),
		'hire_cta_2'       => array(
			'title'              => 'LOOKING TO PARTNER WITH US?',
			'para'               => 'Prepare For a Genuine Business Partnership',
			'primary_button'     => true,
			'secondary_button'   => true,
			'primary_btn_title'  => 'Check Out Partnership Model',
			'primary_btn_popup'  => true,
			'secondary_btn_title' => "LET'S TALK",
		),
		'hire_tech_stack'  => array(
			'sub_head'  => 'Tailor Your JavaScript Development with Skilled Developers',
			'para_text' => 'Customize your JavaScript development with our proficient developers. We deliver tailored solutions to match your unique project requirements, ensuring efficient, high-quality development that meets your precise needs. Here\'s what we offer:',
			'hire_list' => array(
				array('img' => '/hire/angular/4.png', 'width' => 75, 'height' => 75, 'head' => 'Achieve Cutting-Edge JS Development',  'para' => 'Unlock the potential of highly skilled JavaScript development teams to effectively engage and convert casual users into loyal customers for your business.'),
				array('img' => '/hire/angular/3.png', 'width' => 75, 'height' => 75, 'head' => 'JavaScript Plug-In Development',       'para' => 'Our full-stack JavaScript engineers excel in crafting robust plugins that smartly enhance app functionalities in a scalable and secure manner.'),
				array('img' => '/hire/angular/2.png', 'width' => 75, 'height' => 75, 'head' => 'Custom Software Development',          'para' => 'Our JS engineers simplify complex business scenarios with customized Java structures, delivering tailored programming solutions.'),
				array('img' => '/hire/angular/1.png', 'width' => 75, 'height' => 75, 'head' => 'Mobile App Development',               'para' => 'Hire a JavaScript programmer who harnesses the right framework to deliver genuine functionality aligned with your business needs and market demands.'),
			),
		),
		'main_cta'         => array(),
		'faqs' => array(
    'head_text' => 'We\'re here to help',
    'faq_image' => true,
    'listing'   => array(
        array( 'faqhead' => 'How much does it cost to hire ReactJS developers?',                          'faqbody' => 'The cost to hire ReactJS developers depends on developer experience, project complexity, engagement model, UI requirements, backend integrations, and timeline. A simple frontend update may cost less than a SaaS dashboard, ecommerce platform, enterprise portal, or custom web app that needs complex state management, API integrations, performance optimization, and QA. At TechnBrains, you can hire ReactJS developers through staff augmentation, software outsourcing, or dedicated teams based on your project scope and budget.' ),
        array( 'faqhead' => 'What skills should I look for when hiring a ReactJS developer?',             'faqbody' => 'When hiring a ReactJS developer, look for experience in JavaScript, TypeScript, React, Redux, REST APIs, GraphQL, HTML, CSS, responsive design, Git, testing, and frontend performance optimization. For complex products, the developer should also understand component-based architecture, reusable UI systems, secure API handling, cloud deployment workflows, and scalable frontend development.' ),
        array( 'faqhead' => 'Can I hire ReactJS developers for an existing web app?',                     'faqbody' => 'Yes. You can hire ReactJS developers to improve, maintain, or scale an existing web application. This may include fixing frontend bugs, improving page speed, updating old React code, migrating class components to functional components, improving state management, redesigning UI screens, integrating APIs, or building new product features. This is a strong fit for staff augmentation when you already have an internal team and need additional ReactJS expertise.' ),
        array( 'faqhead' => 'Should I hire a ReactJS developer or outsource the full ReactJS project?',  'faqbody' => 'Hire a ReactJS developer through staff augmentation when you already have an internal product or engineering team and need frontend expertise to support development. Choose software outsourcing when you want TechnBrains to manage the full ReactJS development process, including planning, UI/UX, frontend development, backend integration, QA, deployment, and support. Choose a dedicated team when your product needs continuous frontend development, regular releases, and long-term technical support.' ),
        array( 'faqhead' => 'Do your ReactJS developers work with Redux, REST APIs, and GraphQL?',        'faqbody' => 'Yes. TechnBrains provides ReactJS developers experienced in React, Redux, RESTful APIs, GraphQL, JavaScript, Git, responsive web design, and component-based frontend development. These skills are useful for SaaS platforms, ecommerce websites, dashboards, admin panels, portals, and web apps that need clean user interfaces connected to reliable backend systems.' ),
        array( 'faqhead' => 'Can TechnBrains help migrate an existing frontend to ReactJS?',              'faqbody' => 'Yes. TechnBrains can help migrate an existing frontend to ReactJS when your business wants better performance, reusable components, easier maintenance, or a more scalable user interface. The migration process may include reviewing the current frontend, rebuilding key screens, improving component structure, connecting APIs, testing functionality, and preparing the application for stable deployment.' ),
        array( 'faqhead' => 'Do you provide post-launch support after hiring ReactJS developers?',        'faqbody' => 'Yes. TechnBrains provides post-launch ReactJS support for bug fixes, performance improvements, UI refinements, dependency updates, browser compatibility fixes, API integration support, feature improvements, QA, and ongoing maintenance. Post-launch support is important because user needs, browser behavior, frontend libraries, security requirements, and product priorities continue to change after deployment.' ),
    ),
),
	),
	'components' => array(
		array('name' => 'hire-banner',  'modifier_class' => '', 'args' => array()),
		array('name' => 'steps-hire',   'modifier_class' => '', 'args' => array()),
		array('name' => 'expert',       'modifier_class' => '', 'args' => array()),
		array('name' => 'hire-cta',     'modifier_class' => '', 'args' => array('data_key' => 'hire_cta_1')),
		array('name' => 'hire-choose',  'modifier_class' => 'white-bg', 'args' => array()),
		array('name' => 'skills',       'modifier_class' => '', 'args' => array()),
		array('name' => 'hire-table',   'modifier_class' => '', 'args' => array()),
		array('name' => 'hire-cta',     'modifier_class' => '', 'args' => array('data_key' => 'hire_cta_2')),
		array('name' => 'hire',         'modifier_class' => '', 'args' => array()),
		array('name' => 'main-cta',     'modifier_class' => '', 'args' => array()),
		array('name' => 'main-faqs',    'modifier_class' => '', 'args' => array()),
		array('name' => 'testimonials', 'modifier_class' => '', 'args' => array()),
	),
);
