<?php
defined( 'ABSPATH' ) || exit;

return array(
	'schemas'    => array(
		array(
			'@context'   => 'https://schema.org',
			'@type'      => 'FAQPage',
			'mainEntity' => array(
				array( '@type' => 'Question', 'name' => 'How does outsourcing to a Java development company work?',  'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Outsourcing to a Java development company involves a collaborative process where you entrust specific software development tasks or projects to a specialized team. Regular communication, updates, and milestones ensure transparency, making outsourcing a seamless experience.' ) ),
				array( '@type' => 'Question', 'name' => 'What kind of applications can you develop using Java?',     'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'The versatility of Java shines through in the diverse range of applications it can handle. A Java development company can create robust enterprise solutions, dynamic web applications, cross-platform games through platforms like LibGDX, and mobile applications through Android SDK.' ) ),
				array( '@type' => 'Question', 'name' => 'Which Java technologies are your developers proficient in?','acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Our developers are proficient in a comprehensive set of Java technologies including Spring, JavaServer Faces (JSF) for web development, and platforms such as LibGDX for Java game development.' ) ),
				array( '@type' => 'Question', 'name' => 'Why should I use Java Spring?',                             'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Java Spring offers dependency injection, simplified configuration, and enhanced testability, making it a preferred choice for creating scalable and maintainable applications.' ) ),
				array( '@type' => 'Question', 'name' => 'How can I keep track of my Java development project?',      'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Keeping track involves maintaining open channels of communication with the development team. Regular updates, milestones, and project management tools provide transparency throughout the entire process.' ) ),
				array( '@type' => 'Question', 'name' => 'Will I receive post-project support?',                      'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Yes, post-project support is a standard offering from a reputable Java development company, covering issue resolution, updates, and ongoing maintenance needs.' ) ),
				array( '@type' => 'Question', 'name' => 'Can Java be used for mobile app development?',              'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Java is a versatile language suitable for mobile app development on various platforms. Through frameworks like Android SDK, Java is widely used for creating robust and feature-rich Android mobile applications.' ) ),
				array( '@type' => 'Question', 'name' => 'What are the advantages of Java?',                          'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'The advantages of Java are multifaceted, ranging from platform independence and robust security features to scalability and an extensive ecosystem. Its widespread community support further adds to its appeal.' ) ),
				array( '@type' => 'Question', 'name' => 'How much does Java application development cost?',          'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'The cost of Java application development is influenced by project complexity, scope, and the expertise of the development team. Detailed discussions will help outline specific requirements and provide a customized cost estimate.' ) ),
				array( '@type' => 'Question', 'name' => 'Is Java still a good option for software development?',     'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Absolutely, Java remains an excellent and relevant choice for software development. Its enduring popularity, continuous updates, and adaptability make it a reliable language for various applications.' ) ),
			),
		),
	),
	'mock_data'  => array(
		'main_banner'         => array(
			'head_text'     => 'Java Application Development Services',
			'content'       => 'Experience excellence with our Java development company. We specialize in Java development, crafting dynamic solutions that enhance your online presence. Trust us for robust, secure, and scalable outcomes.',
			'img_src'       => '/stack/java/java-banner.png',
			'img_width'     => 640,
			'img_height'    => 640,
			'img_alt'       => 'java-banner',
			'btn_link'      => '/hire-java-developer',
			'btn_link_text' => 'Learn More',
			'popup_text'    => 'GET A FREE QUOTE',
		),
		'dedicated_lang_desc' => array(
			'para_html' => 'Java is one of the most <span>reliable and scalable programming languages</span>, making it the top choice for businesses with complex needs. If you\'re looking to hire dedicated Java developers, TechnBrains is here to help. For decades, our Java software development company has been assisting businesses in unlocking the full potential of Java, from single-page apps to <span>complex enterprise-grade systems</span>.<br /><br />With a track record of completing <span>100+ small to large-scale Java projects</span>, TechnBrains is a proven leader in the industry. We are also included in the list of top software development companies in Eastern Europe, with clients located across the USA, UK, Israel, Europe, Canada, and other regions. Let\'s discuss how we can help your business achieve success with Java.',
		),
		'language_services'   => array(
			'head_text' => 'Java Development Services for Your Business',
			'para_text' => 'Transform your business with our cutting-edge Java development services. From custom applications to cloud-based platforms, we offer tailored solutions for seamless integration and elevated performance.',
			'btn_text'  => 'Hire JAVA GEEKS NOW!',
			'anchor'    => true,
			'btn_url'   => '/hire-java-developer',
			'listing'   => array(
				array( 'img_src' => '/stack/java/app-dev.png',   'width' => '80', 'height' => '80', 'alt' => 'app-dev',   'list_head' => 'Custom Java Applications',                  'list_para' => 'We offer customized Java development solutions ranging from LMS to PM tools, prioritizing clean code for risk mitigation.' ),
				array( 'img_src' => '/stack/java/application.png','width' => '80', 'height' => '80', 'alt' => 'app',       'list_head' => 'Mobile & Web Applications',                 'list_para' => 'We leverage Java and Android SDK for mobile app development and frameworks like Spring and JavaServer Faces (JSF) for secure and scalable web development.' ),
				array( 'img_src' => '/stack/java/web-dev.png',   'width' => '80', 'height' => '80', 'alt' => 'web-dev',   'list_head' => 'Cloud-Based Platforms',                      'list_para' => 'Our Java developers use modern tools like Spring Cloud, Apache Kafka, Docker, and Kubernetes to build scalable, resilient, and cloud-native apps.' ),
				array( 'img_src' => '/stack/java/app-des.png',   'width' => '80', 'height' => '80', 'alt' => 'app-des',   'list_head' => 'Enterprise Java Applications',               'list_para' => 'Use our Java frameworks like Spring Boot and Hibernate to develop high-performance applications with efficient data persistence.' ),
				array( 'img_src' => '/stack/java/back.png',      'width' => '80', 'height' => '80', 'alt' => 'back',      'list_head' => 'Migrations & Integrations',                  'list_para' => 'We offer smooth migration to modern Java frameworks, including microservice architecture with Spring Boot and Kubernetes and integration with third-party systems.' ),
				array( 'img_src' => '/stack/java/mantain.png',   'width' => '80', 'height' => '80', 'alt' => 'mantain',   'list_head' => 'Java-based SaaS Application Development',   'list_para' => 'We specialize in creating secure, high-quality SaaS products catering to compliance, cost-efficiency, and user-friendly interfaces.' ),
				array( 'img_src' => '/stack/java/team.png',      'width' => '80', 'height' => '80', 'alt' => 'team',      'list_head' => 'Java Application Modernization',             'list_para' => 'We help revitalize your legacy Java applications through code refactoring, optimizing performance, enhancing security, and modernizing your tech stack.' ),
				array( 'img_src' => '/stack/java/integrate.png', 'width' => '80', 'height' => '80', 'alt' => 'integrate', 'list_head' => 'Java Software Support and Evolution',        'list_para' => 'Get comprehensive Java software support services including L1 to L3 support, performance optimization, compliance management, and security monitoring.' ),
				array( 'img_src' => '/stack/java/skill.png',     'width' => '80', 'height' => '80', 'alt' => 'skill',     'list_head' => 'Hire Skilled Java Developers',               'list_para' => 'Hire skilled Java developers who bring a wealth of experience ensuring robust, efficient, and scalable solutions tailored to your specific needs.' ),
			),
		),
		'proposal'            => array(
			'head_html' => '<h2>Build powerful Java-based applications with our Java application development services</h2>',
			'btn_text'  => 'Let\'s Build',
			'anchor'    => false,
		),
		'dev_process'         => array(
			'main_title' => 'TechnBrains JAVA development to boost your business',
			'lang_title' => 'Why Opt for TechnBrains in Java Development',
			'listing'    => array(
				array( 'img_src' => '/stack/java/d1.png', 'title' => '200+ Java Development Success Stories',     'para' => 'Choose TechnBrains for unparalleled expertise in Java development with a track record of over 200 successful engagements. As a leading Java development company, we\'ve left our mark in various sectors, from groundbreaking Java web development projects to innovative ventures in Java game development.' ),
				array( 'img_src' => '/stack/java/d2.png', 'title' => 'Elite Java Developers: Top 1% Talent Pool', 'para' => 'At TechnBrains, our commitment to quality is embodied by our Top 1% Java Developers. Selected through a meticulous process, our developers bring over a decade of average experience to the table, with both technical acumen and essential soft skills needed for successful collaboration.' ),
				array( 'img_src' => '/stack/java/d3.png', 'title' => 'Flexible Java Development Services',        'para' => 'TechnBrains stands out for providing tailored solutions to meet your unique needs in Java development. Our flexible engagement models allow you to build a team that precisely fits your project requirements, ensuring optimal outcomes.' ),
				array( 'img_src' => '/stack/java/d1.png', 'title' => '200+ Java Development Success Stories',     'para' => 'Choose TechnBrains for unparalleled expertise in Java development with a track record of over 200 successful engagements across various sectors.' ),
				array( 'img_src' => '/stack/java/d2.png', 'title' => 'Elite Java Developers: Top 1% Talent Pool', 'para' => 'At TechnBrains, our commitment to quality is embodied by our Top 1% Java Developers, bringing over a decade of average experience.' ),
				array( 'img_src' => '/stack/java/d3.png', 'title' => 'Flexible Java Development Services',        'para' => 'TechnBrains provides tailored solutions and flexible engagement models to precisely fit your Java project requirements.' ),
			),
		),
		'key_things'          => array(
			'sub_title' => 'Collaborate with our team of JAVA gurus',
			'title'     => 'Key Things To Know About Java Web Development',
			'listing'   => array(
				array( 'tab_title' => 'Benefits of Using Java for Software Development', 'tab_content' => '<h4>1. Versatility in Development:</h4><p>Java\'s versatility shines through in diverse domains, from robust enterprise applications to dynamic web solutions and engaging game development.</p><h4>2. Reliability and Stability:</h4><p>Renowned for its unwavering reliability, Java ensures consistent performance and minimal system failures.</p><h4>3. Platform Independence:</h4><p>Java\'s platform independence empowers businesses to run code seamlessly across different platforms.</p><h4>4. Security First Approach:</h4><p>With a robust security model, Java prioritizes security for applications handling sensitive data.</p><h4>5. Scalability and Performance:</h4><p>Java\'s unmatched scalability accommodates evolving business needs without sacrificing performance.</p><h4>6. Cost-Effective Solutions:</h4><p>Choosing Java leads to cost-effective solutions in the long run through code reuse and maintainability.</p>' ),
				array( 'tab_title' => 'Java is primarily used for',                     'tab_content' => '<p>Java is a versatile programming language primarily used for diverse applications. Its adaptability shines in Java web development, where frameworks like Spring and JavaServer Faces (JSF) create secure and scalable solutions.</p><p>Java\'s significance extends to Java game development, where platforms like LibGDX and JavaFX facilitate the creation of engaging, cross-platform games. It is frequently employed by leading Java development companies for Java application development.</p>' ),
				array( 'tab_title' => 'Reasons for Java\'s Popularity',                 'tab_content' => '<ul><li>Versatility Across Domains including enterprise, web, and game development.</li><li>Platform Independence with "write once, run anywhere" philosophy.</li><li>Strong Foundation for Enterprise Solutions with reliability, scalability, and security.</li><li>Dynamic Role in Web Development with frameworks like Spring and JSF.</li><li>Prominence in Game Development with platforms like LibGDX and JavaFX.</li><li>Preference Among Leading Development Companies due to syntax, reliability, and extensive ecosystem.</li><li>Opportunities for Outsourcing to access global talent pools.</li></ul>' ),
			),
		),
		'stack_new_box'       => array(
			'subtitle' => 'Redefine your app\'s visual appeal with TechnBrains',
			'title'    => 'Technology Stack for Java Web Development',
			'para'     => '',
			'listing'  => array(
				array( 'tab_title' => 'Framework',               'data_list' => array( array('title'=>'Spring MVC'), array('title'=>'Spring Security'), array('title'=>'JSF'), array('title'=>'Hibernate'), array('title'=>'Spring boot / Rest API') ) ),
				array( 'tab_title' => 'Apache Foundation',       'data_list' => array( array('title'=>'Jenkins'), array('title'=>'Terraform'), array('title'=>'AWS'), array('title'=>'Docker'), array('title'=>'Kubernetes'), array('title'=>'Azure Google Cloud') ) ),
				array( 'tab_title' => 'Project Management Tools','data_list' => array( array('title'=>'Jira'), array('title'=>'Trello'), array('title'=>'Microsoft Team'), array('title'=>'Slack') ) ),
				array( 'tab_title' => 'Front End',               'data_list' => array( array('title'=>'React'), array('title'=>'Vue'), array('title'=>'Bootstrap'), array('title'=>'Angular'), array('title'=>'jQuery'), array('title'=>'UWP Apps'), array('title'=>'WPF') ) ),
				array( 'tab_title' => 'Architecture',            'data_list' => array( array('title'=>'MVC'), array('title'=>'MVVM'), array('title'=>'MVP'), array('title'=>'Microservices') ) ),
				array( 'tab_title' => 'Testing',                 'data_list' => array( array('title'=>'Selenium'), array('title'=>'Postman OWASP ZAP'), array('title'=>'TestRail'), array('title'=>'Apache JMeter'), array('title'=>'Katalon Test Studio'), array('title'=>'BrowserStack') ) ),
				array( 'tab_title' => 'Database',                'data_list' => array( array('title'=>'SQL Server'), array('title'=>'PostgreSQL'), array('title'=>'MySQL'), array('title'=>'MongoDB'), array('title'=>'Azure SQL Amazon RDS'), array('title'=>'Oracle'), array('title'=>'Cassandra'), array('title'=>'Elasticsearch'), array('title'=>'Dynamo'), array('title'=>'Amazon RDS') ) ),
				array( 'tab_title' => 'Products',                'data_list' => array( array('title'=>'Office 365'), array('title'=>'Biztalk Server'), array('title'=>'Share point Server'), array('title'=>'Power BI') ) ),
				array( 'tab_title' => 'Caching',                 'data_list' => array( array('title'=>'Memcached'), array('title'=>'Reds') ) ),
			),
		),
		'hiring'              => array(
			'lang_title' => 'java Development Company',
			'hire_title' => 'Hiring Models for Business Success',
			'para_text'  => 'Take your business to new heights with our business-friendly hiring models, offering the flexibility of monthly or fixed-priced arrangements for our expert developers.',
			'listing'    => array(
				array( 'key' => 'tab-1', 'title' => 'Hire Team',                     'tab_points' => array( array('text'=>'Initiate the process with your requirements, followed by our team proposition.'), array('text'=>'Ensure the team aligns perfectly with your project needs before finalizing the dedicated team.') ) ),
				array( 'key' => 'tab-1', 'title' => 'Project Development Lifecycle', 'tab_points' => array( array('text'=>'Agile and Lean Software Development'), array('text'=>'Project Milestones & Bi-Weekly Sprint Designs'), array('text'=>'Iterative Development and Feedback') ) ),
				array( 'key' => 'tab-1', 'title' => 'Project Delivery Excellence',   'tab_points' => array( array('text'=>'Cloud and DevOps Integration'), array('text'=>'Manual/Automated Testing'), array('text'=>'Reliable and Flexible Delivery') ) ),
				array( 'key' => 'tab-2', 'title' => 'Project Requirements',          'tab_points' => array( array('text'=>'Requirement gathering and gap analysis'), array('text'=>'Time and cost estimation'), array('text'=>'Project agreement signing') ) ),
				array( 'key' => 'tab-2', 'title' => 'Project Development',           'tab_points' => array( array('text'=>'Agile and Lean Software Development'), array('text'=>'Project Milestones & Bi-Weekly Sprint Designs'), array('text'=>'Iterative Development and Feedback') ) ),
				array( 'key' => 'tab-2', 'title' => 'Project Delivery',              'tab_points' => array( array('text'=>'Manual/Automated Testing'), array('text'=>'Reliable and Flexible Delivery') ) ),
			),
		),
		'faqs'                => array(
			'head_text' => 'Things you might want to know',
			'faq_image' => false,
			'listing'   => array(
				array( 'faqhead' => 'How does outsourcing to a Java development company work?',  'faqbody' => 'Outsourcing to a Java development company involves a collaborative process where you entrust specific software development tasks to a specialized team. Regular communication, updates, and milestones ensure transparency.' ),
				array( 'faqhead' => 'What kind of applications can you develop using Java?',     'faqbody' => 'The versatility of Java shines through in diverse applications including enterprise solutions, dynamic web applications, cross-platform games, and mobile applications through Android SDK.' ),
				array( 'faqhead' => 'Which Java technologies are your developers proficient in?','faqbody' => 'Our developers are proficient in Spring, JavaServer Faces (JSF) for web development, and platforms such as LibGDX for Java game development.' ),
				array( 'faqhead' => 'Why should I use Java Spring?',                             'faqbody' => 'Java Spring offers dependency injection, simplified configuration, and enhanced testability, making it a preferred choice for scalable and maintainable Java applications.' ),
				array( 'faqhead' => 'How can I keep track of my Java development project?',      'faqbody' => 'Keeping track involves maintaining open communication with the development team. Regular updates, milestones, and project management tools provide transparency throughout.' ),
				array( 'faqhead' => 'Will I receive post-project support?',                      'faqbody' => 'Yes, post-project support is a standard offering covering issue resolution, updates, and ongoing maintenance needs for the longevity of your Java applications.' ),
				array( 'faqhead' => 'Can Java be used for mobile app development?',              'faqbody' => 'Java is a versatile language suitable for app development on various platforms. Through frameworks like Android SDK, Java is widely used for creating robust Android mobile applications.' ),
				array( 'faqhead' => 'What are the advantages of Java?',                          'faqbody' => 'The advantages include platform independence, robust security, scalability, and an extensive ecosystem. Its widespread community support further adds to its appeal.' ),
				array( 'faqhead' => 'How much does Java application development cost?',          'faqbody' => 'The cost is influenced by project complexity, scope, and development team expertise. Detailed discussions will provide a customized cost estimate tailored to your needs.' ),
				array( 'faqhead' => 'Is Java still a good option for software development?',     'faqbody' => 'Absolutely, Java remains an excellent and relevant choice. Its enduring popularity, continuous updates, and adaptability make it a reliable language for various applications.' ),
			),
		),
	),
	'components' => array(
		array( 'name' => 'main-banner',         'modifier_class' => '' ),
		array( 'name' => 'dedicated-lang-desc', 'modifier_class' => '' ),
		array( 'name' => 'language-services',   'modifier_class' => '' ),
		array( 'name' => 'proposal',            'modifier_class' => '' ),
		array( 'name' => 'development-process', 'modifier_class' => '' ),
		array( 'name' => 'java-expertise',      'modifier_class' => '' ),
		array( 'name' => 'key-things',          'modifier_class' => '' ),
		array( 'name' => 'stack-new-box',       'modifier_class' => 'angular-stack' ),
		array( 'name' => 'hiring',              'modifier_class' => '' ),
		array( 'name' => 'testimonials',        'modifier_class' => '' ),
		array( 'name' => 'main-faqs',           'modifier_class' => '' ),
	),
);
