<?php
defined( 'ABSPATH' ) || exit;

return array(
	'schemas'    => array(
		array(
			'@context'   => 'https://schema.org',
			'@type'      => 'FAQPage',
			'mainEntity' => array(
				array( '@type' => 'Question', 'name' => 'What is .NET Development?',                                               'acceptedAnswer' => array( '@type' => 'Answer', 'text' => '.NET development is a comprehensive approach to crafting powerful, scalable, and secure applications using the .NET framework. TechnBrains specializes in providing .NET software development, application development, web development, and custom .NET development.' ) ),
				array( '@type' => 'Question', 'name' => 'Is .NET Cross-Platform?',                                                 'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Absolutely! .NET has embraced cross-platform capabilities, ensuring that your applications can run seamlessly across various operating systems.' ) ),
				array( '@type' => 'Question', 'name' => 'Which Programming Languages Can be Used with .NET?',                      'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'TechnBrains supports multiple programming languages with .NET including C#, VB.NET, and F#, ensuring the language choice aligns with your project requirements.' ) ),
				array( '@type' => 'Question', 'name' => 'Can Existing Applications be Migrated to .NET?',                         'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Certainly! As a dedicated .NET development company, we offer seamless migration services to transition your existing applications to the .NET framework.' ) ),
				array( '@type' => 'Question', 'name' => 'What are the Advantages of Using .NET for Development?',                  'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Choosing .NET development comes with a myriad of advantages. TechnBrains specializes in delivering reliable, scalable, and secure solutions that meet and exceed industry standards.' ) ),
				array( '@type' => 'Question', 'name' => 'What Types of Cloud Platforms do .NET Development Services Cover?',       'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Our .NET development services extend to various cloud platforms, including Azure and AWS, ensuring your applications are scalable in a cloud environment.' ) ),
				array( '@type' => 'Question', 'name' => 'What is the Difference Between .NET Framework and .NET Core?',            'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'The .NET Framework is a traditional Windows-centric framework, while .NET Core is a cross-platform and modular solution. Our expertise allows us to tailor solutions to your specific needs.' ) ),
				array( '@type' => 'Question', 'name' => 'Will I Receive Post-Project Support?',                                    'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Absolutely! At TechnBrains, our commitment doesn\'t end with project delivery. We provide comprehensive post-project support ensuring the continued success of your .NET applications.' ) ),
			),
		),
	),
	'mock_data'  => array(
		'main_banner'         => array(
			'head_text'     => '.NET Development Company',
			'content'       => 'Need a full range of .NET software development services from a top .NET development company? With a decade of experience, TechnBrains delivers custom .NET applications that drive business growth and deliver compelling user experiences.',
			'img_src'       => '/stack/dot/dotnet.webp',
			'img_width'     => 1000,
			'img_height'    => 600,
			'img_alt'       => 'dotnet-banner',
			'btn_link'      => '/contact-us',
			'btn_link_text' => 'Learn More',
			'popup_text'    => 'GET A FREE QUOTE',
		),
		'dedicated_lang_desc' => array(
			'para_html' => 'The <span>power of Microsoft .NET framework</span> is undeniable when it comes to building secure, scalable, and high-performance enterprise applications. As a Microsoft Certified Gold Partner, we take pride in delivering the best possible bespoke .NET solutions to our clients. With over two decades of experience, we have created countless enterprise-grade full life cycle .NET solutions for customers in various industries.<br /><br />We dive deep into our customer\'s business challenges and provide them with quick measurable results. Our team of skilled .NET software developers are experts in using <span>ASP.NET, .NET Core, C#, VB.NET, MVC WPF, MVVM</span>, Entity Framework, Xamarin, SharePoint, and BizTalk Server to create hundreds of web applications. We are committed to delivering premium quality solutions that help our clients achieve their business goals.',
		),
		'language_services'   => array(
			'head_text' => '.NET Services We Provide',
			'para_text' => 'We offer .Net development services that create secure and sustainable solutions across devices. Our agile approach and custom solutions optimize performance, scalability, and responsiveness. We focus on client success with tailored .Net development services.',
			'btn_text'  => 'Hire .net GEEKS NOW!',
			'anchor'    => false,
			'listing'   => array(
				array( 'img_src' => '/stack/dot/icon-1.png',  'width' => '80', 'height' => '80', 'alt' => 'app-dev', 'list_head' => 'Custom .NET Software Development',    'list_para' => 'Our .NET developers have leveraged many of the ecosystem\'s libraries, tools, and components to complete over 200 projects, including interactive websites, mobile applications, and games.' ),
				array( 'img_src' => '/stack/dot/icon-2.png',  'width' => '80', 'height' => '80', 'alt' => 'app-dev', 'list_head' => '.NET Integration & API Development',  'list_para' => 'Our skilled .NET developers can efficiently link applications with databases, APIs, ERPs, CRMs and other platforms using frameworks like WCF and Entity Framework for seamless integrations.' ),
				array( 'img_src' => '/stack/dot/icon-3.png',  'width' => '80', 'height' => '80', 'alt' => 'app-dev', 'list_head' => '.NET Migration and Modernization',    'list_para' => 'Easily migrate from IBM Cloud to AWS or vice versa and update your framework. Our dedicated .NET development teams will refresh your architecture and tech stack.' ),
				array( 'img_src' => '/stack/dot/icon-4.png',  'width' => '80', 'height' => '80', 'alt' => 'app-dev', 'list_head' => '.NET E-commerce Solutions',            'list_para' => 'We have experience building secure, scalable e-commerce websites using .NET. Our developers create back-end infrastructure and add secure payment gateways.' ),
				array( 'img_src' => '/stack/dot/icon-5.png',  'width' => '80', 'height' => '80', 'alt' => 'app-dev', 'list_head' => '.NET Enterprise Solutions',            'list_para' => 'Our skilled .NET developers use a wide range of tools and frameworks to build custom solutions such as ERPs, CRMs, and BI platforms.' ),
				array( 'img_src' => '/stack/dot/icon-6.png',  'width' => '80', 'height' => '80', 'alt' => 'app-dev', 'list_head' => 'Cloud-Based Solutions',                'list_para' => 'We create fast and scalable cloud-native .NET solutions using ASP.NET Core and microservices architecture with Docker, Kubernetes, and Azure Functions.' ),
				array( 'img_src' => '/stack/dot/icon-7.png',  'width' => '80', 'height' => '80', 'alt' => 'app-dev', 'list_head' => 'Azure Development Services',           'list_para' => 'Our team of .NET developers specialize in leveraging Azure services such as Azure Apps, Blob & Table Storage, SQL Database, and Stream Analytics.' ),
				array( 'img_src' => '/stack/dot/icon-8.png',  'width' => '80', 'height' => '80', 'alt' => 'app-dev', 'list_head' => 'ASP.NET Web Application Development', 'list_para' => 'Our team develops custom ASP.NET web applications for businesses of all sizes, with a focus on functionality, robustness, and agility.' ),
				array( 'img_src' => '/stack/dot/icon-9.png',  'width' => '80', 'height' => '80', 'alt' => 'app-dev', 'list_head' => 'Universal App Development',           'list_para' => 'As a Microsoft .NET Development Company, we have created scalable, secure, and performant Universal Windows Platform apps for various devices.' ),
				array( 'img_src' => '/stack/dot/icon-10.png', 'width' => '80', 'height' => '80', 'alt' => 'app-dev', 'list_head' => '.NET Core Development',               'list_para' => 'We specialize in providing .NET services utilizing .NET Core, .NET Framework, and the latest front-end technologies for high-performance, cloud-based applications.' ),
				array( 'img_src' => '/stack/dot/icon-11.png', 'width' => '80', 'height' => '80', 'alt' => 'app-dev', 'list_head' => 'Application Lifecycle Management',    'list_para' => 'We offer comprehensive .NET development services, covering ideation, design, implementation, quality assurance, maintenance, CI/CD, and DevOps.' ),
				array( 'img_src' => '/stack/dot/icon-12.png', 'width' => '80', 'height' => '80', 'alt' => 'app-dev', 'list_head' => 'WPF Application Development',         'list_para' => 'Our team utilizes the Windows Presentation Foundation framework to develop lightweight applications optimized for speed.' ),
				array( 'img_src' => '/stack/dot/icon-13.png', 'width' => '80', 'height' => '80', 'alt' => 'app-dev', 'list_head' => 'Xamarin Development',                 'list_para' => 'We create cross-platform apps for iOS, Android, and Windows devices using Xamarin, saving time and money with our efficient development process.' ),
				array( 'img_src' => '/stack/dot/icon-5.png',  'width' => '80', 'height' => '80', 'alt' => 'app-dev', 'list_head' => 'ASP.NET Enterprise Solutions',        'list_para' => 'Our ASP.NET software development services create and manage secure SAAS applications that seamlessly interact with enterprise solutions.' ),
				array( 'img_src' => '/stack/dot/icon-14.png', 'width' => '80', 'height' => '80', 'alt' => 'app-dev', 'list_head' => 'Dedicated Development Team',          'list_para' => 'Our company\'s professionals can collaborate with your development team for scalable .NET project development.' ),
			),
		),
		'proposal'            => array(
			'head_html' => '<h2>Keep struggling with outdated tech!</h2><h5>Or... Dare To Ignite Progress With .NET Solutions? Your Call!</h5>',
			'btn_text'  => 'Hire an expert team of .net Developers',
			'anchor'    => false,
			'classes'   => 'net-development',
		),
		'dev_process'         => array(
			'main_title' => 'TechnBrains for Exceptional .NET services',
			'lang_title' => 'Why Choose TechnBrains for Your .NET Development Needs?',
			'listing'    => array(
				array( 'img_src' => '/stack/dot/dp1.png', 'title' => 'Expertise in .NET Development',             'para' => 'TechnBrains stands as a reputable .NET development company with a proven track record. Our expertise spans .NET software development, application development, web development, and more.' ),
				array( 'img_src' => '/stack/dot/dp2.png', 'title' => 'Comprehensive .NET Development Services',   'para' => 'We offer a holistic suite of .NET development services tailored to your specific requirements. Whether you need custom .NET development or a comprehensive web solution, TechnBrains has you covered.' ),
				array( 'img_src' => '/stack/dot/dp3.png', 'title' => 'Innovation in .NET Software Development',   'para' => 'Embrace innovation with our forward-thinking approach to .NET development. We don\'t just follow trends; we set them. Experience cutting-edge solutions that redefine the possibilities of .NET technology.' ),
				array( 'img_src' => '/stack/dot/dp4.png', 'title' => 'Specialized .NET Application Development',  'para' => 'Your unique needs deserve specialized attention. TechnBrains excels in custom .NET development, ensuring that your applications align perfectly with your business goals.' ),
				array( 'img_src' => '/stack/dot/dp5.png', 'title' => 'Seamless .NET Web Development',             'para' => 'Elevate your online presence with our seamless .NET web development services. We understand the importance of a robust web presence and deliver solutions that go beyond expectations.' ),
				array( 'img_src' => '/stack/dot/dp6.png', 'title' => 'Trusted .NET Software Development Company', 'para' => 'Trust is the cornerstone of our client relationships. TechnBrains is a trusted .NET software development company known for reliability, transparency, and delivering projects on time.' ),
				array( 'img_src' => '/stack/dot/dp7.png', 'title' => 'Tailored Solutions for Every Business',     'para' => 'We understand that one size doesn\'t fit all. TechnBrains crafts custom .NET solutions that cater to the unique challenges and aspirations of your business.' ),
				array( 'img_src' => '/stack/dot/dp8.png', 'title' => 'Proven Track Record',                       'para' => 'Our portfolio speaks volumes. TechnBrains has successfully executed a myriad of .NET development projects, showcasing our ability to transform ideas into impactful, scalable, and secure applications.' ),
			),
		),
		'key_things'          => array(
			'sub_title' => 'In and Outs of .NET',
			'title'     => 'Benefits of Using .NET for Software Development',
			'listing'   => array(
				array( 'tab_title' => 'Benefits of Using .NET for Software Development', 'tab_content' => '<h4>1. Versatile .NET Development Services:</h4><p>TechnBrains offers a versatile range of services covering .NET software development, application development, web development, and custom .NET development.</p><h4>2. Rapid Application Development:</h4><p>.NET is renowned for its efficiency in application development. TechnBrains accelerates the development process, saving time and resources.</p><h4>3. Scalability and Performance:</h4><p>As a scalable platform, .NET is designed to grow with your business, performing seamlessly as your user base increases.</p><h4>4. Security First Approach:</h4><p>.NET development services at TechnBrains prioritize security, offering a secure foundation for your applications.</p><h4>5. Custom .NET Development Tailored to You:</h4><p>TechnBrains specializes in custom .NET development, ensuring that your applications align perfectly with your business objectives.</p>' ),
				array( 'tab_title' => 'What .NET is Primarily Used For',                'tab_content' => '<p>.NET is primarily used for:</p><h4>Web Application Development:</h4><p>.NET is a popular choice for building dynamic and robust web applications.</p><h4>Enterprise-Level Applications:</h4><p>Businesses choose .NET for building scalable and secure enterprise-level applications.</p><h4>Cross-Platform Development:</h4><p>With .NET Core, .NET has become a go-to framework for cross-platform development across various operating systems.</p>' ),
				array( 'tab_title' => 'Other Reasons for .NET\'s Popularity',           'tab_content' => '<p>.NET\'s popularity is further attributed to:</p><h4>Extensive Language Support:</h4><p>.NET supports multiple programming languages, including C#, VB.NET, and F#, providing flexibility for developers.</p><h4>Integration with Microsoft Ecosystem:</h4><p>The integration with the Microsoft ecosystem provides a seamless development experience with a unified environment of tools and services.</p><h4>Strong Community Support:</h4><p>.NET boasts a robust and supportive developer community, enabling developers to stay abreast of industry trends and best practices.</p>' ),
			),
		),
		'stack_new_box'       => array(
			'subtitle' => 'Redefine your app\'s visual appeal with TechnBrains',
			'title'    => 'Technology Stack for .NET Development',
			'para'     => '',
			'listing'  => array(
				array( 'tab_title' => 'Framework & Languages',    'data_list' => array( array('title'=>'.NET'), array('title'=>'.NET Core'), array('title'=>'ASP.net'), array('title'=>'C#'), array('title'=>'VB.net') ) ),
				array( 'tab_title' => 'Apache Foundation',        'data_list' => array( array('title'=>'Maven'), array('title'=>'Hadoop'), array('title'=>'Kafka') ) ),
				array( 'tab_title' => 'DevOps',                   'data_list' => array( array('title'=>'Docker'), array('title'=>'Kubernetes'), array('title'=>'Jenkins') ) ),
				array( 'tab_title' => 'Project Management Tools', 'data_list' => array( array('title'=>'Jira'), array('title'=>'Trello'), array('title'=>'Microsoft Team'), array('title'=>'Slack') ) ),
				array( 'tab_title' => 'Front End',                'data_list' => array( array('title'=>'React'), array('title'=>'Vue'), array('title'=>'Bootstrap'), array('title'=>'Angular'), array('title'=>'jQuery') ) ),
				array( 'tab_title' => 'Testing',                  'data_list' => array( array('title'=>'Selenium'), array('title'=>'Postman OWASP ZAP'), array('title'=>'TestRail'), array('title'=>'Apache JMeter'), array('title'=>'Katalon Test Studio'), array('title'=>'BrowserStack') ) ),
				array( 'tab_title' => 'Cloud & DevOps',           'data_list' => array( array('title'=>'AWS'), array('title'=>'Azure'), array('title'=>'Google Cloud'), array('title'=>'Docker'), array('title'=>'Kubernetes'), array('title'=>'Terraform'), array('title'=>'Jenkins') ) ),
				array( 'tab_title' => 'Database',                 'data_list' => array( array('title'=>'SQL Server'), array('title'=>'PostgreSQL'), array('title'=>'MySQL'), array('title'=>'MongoDB'), array('title'=>'Azure SQL Amazon RDS'), array('title'=>'Oracle'), array('title'=>'Cassandra'), array('title'=>'Elasticsearch'), array('title'=>'Dynamo'), array('title'=>'Amazon RDS') ) ),
				array( 'tab_title' => 'Caching',                  'data_list' => array( array('title'=>'Memcached'), array('title'=>'Reds') ) ),
				array( 'tab_title' => 'Bl and Reporting',         'data_list' => array( array('title'=>'JasperReports'), array('title'=>'Pentaho / Hitachi Vantera') ) ),
			),
		),
		'hiring'              => array(
			'lang_title' => 'Hire Top .NET Developers in USA',
			'hire_title' => 'Hiring Models for Business Success',
			'para_text'  => 'Hire expert developers with flexible monthly or fixed-priced plans to take your business higher. Let us help you achieve success!',
			'listing'    => array(
				array( 'key' => 'tab-1', 'title' => 'Hire Team',                     'tab_points' => array( array('text'=>'Initiate the process with your requirements, followed by our team proposition.'), array('text'=>'Ensure the team aligns perfectly with your project needs before finalizing the dedicated team.') ) ),
				array( 'key' => 'tab-1', 'title' => 'Project Development Lifecycle', 'tab_points' => array( array('text'=>'Agile and Lean Software Development'), array('text'=>'Project Milestones & Bi-Weekly Sprint Designs'), array('text'=>'Iterative Development and Feedback') ) ),
				array( 'key' => 'tab-1', 'title' => 'Project Delivery Excellence',   'tab_points' => array( array('text'=>'Cloud and DevOps Integration'), array('text'=>'Manual/Automated Testing'), array('text'=>'Reliable and Flexible Delivery') ) ),
				array( 'key' => 'tab-2', 'title' => 'Project Requirements',          'tab_points' => array( array('text'=>'Requirement gathering and gap analysis'), array('text'=>'Time and cost estimation'), array('text'=>'Project agreement signing') ) ),
				array( 'key' => 'tab-2', 'title' => 'Project Development',           'tab_points' => array( array('text'=>'Agile and Lean Software Development'), array('text'=>'Project Milestones & Bi-Weekly Sprint Designs'), array('text'=>'Iterative Development and Feedback') ) ),
				array( 'key' => 'tab-2', 'title' => 'Project Delivery',              'tab_points' => array( array('text'=>'Manual/Automated Testing'), array('text'=>'Reliable and Flexible Delivery') ) ),
			),
		),
		'faqs'                => array(
			'head_text' => 'Things you might want to know',
			'faq_image' => false,
			'listing'   => array(
				array( 'faqhead' => 'What is .NET Development?',                                               'faqbody' => '.NET development is a comprehensive approach to crafting powerful, scalable, and secure applications using the .NET framework. TechnBrains specializes in providing .NET software development, application development, web development, and custom .NET development.' ),
				array( 'faqhead' => 'Is .NET Cross-Platform?',                                                 'faqbody' => 'Absolutely! .NET has embraced cross-platform capabilities, ensuring that your applications can run seamlessly across various operating systems.' ),
				array( 'faqhead' => 'Which Programming Languages Can be Used with .NET?',                      'faqbody' => 'TechnBrains harnesses the versatility of .NET by supporting multiple programming languages including C#, VB.NET, and F#, ensuring the language choice aligns with your project requirements.' ),
				array( 'faqhead' => 'Can Existing Applications be Migrated to .NET?',                         'faqbody' => 'Certainly! As a dedicated .NET development company, we offer seamless migration services to transition your existing applications to the .NET framework.' ),
				array( 'faqhead' => 'What are the Advantages of Using .NET for Development?',                  'faqbody' => 'Choosing .NET development comes with a myriad of advantages. TechnBrains specializes in delivering reliable, scalable, and secure solutions that meet and exceed industry standards.' ),
				array( 'faqhead' => 'What Types of Cloud Platforms do .NET Development Services Cover?',       'faqbody' => 'Our .NET development services extend to various cloud platforms, including Azure and AWS, ensuring that your applications are scalable in a cloud environment.' ),
				array( 'faqhead' => 'What is the Difference Between .NET Framework and .NET Core?',            'faqbody' => 'The .NET Framework is a traditional Windows-centric framework, while .NET Core is a cross-platform and modular solution. Our expertise allows us to tailor solutions to your specific needs.' ),
				array( 'faqhead' => 'Will I Receive Post-Project Support?',                                    'faqbody' => 'Absolutely! At TechnBrains, our commitment doesn\'t end with project delivery. We provide comprehensive post-project support ensuring the continued success of your .NET applications.' ),
			),
		),
	),
	'components' => array(
		array( 'name' => 'main-banner',         'modifier_class' => '' ),
		array( 'name' => 'dedicated-lang-desc', 'modifier_class' => '' ),
		array( 'name' => 'language-services',   'modifier_class' => '' ),
		array( 'name' => 'proposal',            'modifier_class' => 'net-development' ),
		array( 'name' => 'development-process', 'modifier_class' => '' ),
		array( 'name' => 'key-things',          'modifier_class' => '' ),
		array( 'name' => 'stack-new-box',       'modifier_class' => 'angular-stack' ),
		array( 'name' => 'hiring',              'modifier_class' => '' ),
		array( 'name' => 'testimonials',        'modifier_class' => '' ),
		array( 'name' => 'main-faqs',           'modifier_class' => '' ),
	),
);
