<?php
defined( 'ABSPATH' ) || exit;

return array(
	'schemas'    => array(
		array(
			'@context'   => 'https://schema.org',
			'@type'      => 'FAQPage',
			'mainEntity' => array(
				array( '@type' => 'Question', 'name' => 'How does outsourcing to a PHP development company work?',  'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Outsourcing to a PHP development company involves collaborating with a specialized team that provides a range of services, including PHP web development, custom PHP development, and more. The process typically includes discussing project requirements, receiving cost estimates, and establishing timelines.' ) ),
				array( '@type' => 'Question', 'name' => 'What is a scripting language?',                            'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'A scripting language, like PHP, is a type of programming language designed for scripting tasks, automating processes, and instructing a computer to perform specific functions. In the context of PHP web development, PHP is used for server-side scripting to generate dynamic content.' ) ),
				array( '@type' => 'Question', 'name' => 'What are the two types of scripting languages?',           'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'The two main types of scripting languages are server-side scripting languages and client-side scripting languages. PHP is a prime example of a server-side scripting language, while JavaScript is a client-side scripting language implemented in the user\'s browser for enhanced interactivity.' ) ),
				array( '@type' => 'Question', 'name' => 'What kind of applications can you build using PHP?',       'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'As a comprehensive PHP development company, we specialize in crafting a diverse range of applications including dynamic websites, eCommerce platforms, healthcare applications, social networking portals, and more.' ) ),
				array( '@type' => 'Question', 'name' => 'What is the difference between PHP and JavaScript?',       'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'PHP is a server-side scripting language primarily used for server operations and dynamic content generation. JavaScript is a client-side scripting language that executes within the user\'s browser, enhancing interactivity and user experience.' ) ),
				array( '@type' => 'Question', 'name' => 'Will TechnBrains do custom development work?',             'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Custom development is absolutely at the core of our offerings. As a leading PHP development company, we excel in tailoring solutions to meet your unique requirements.' ) ),
				array( '@type' => 'Question', 'name' => 'How much does it cost to build a PHP app?',                'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'The cost of building a PHP app varies based on factors like project complexity, features, and scope. Our PHP development services provide tailored solutions, and we offer transparent discussions to provide accurate cost estimates aligned with your project requirements.' ) ),
				array( '@type' => 'Question', 'name' => 'How much time will it take to complete my PHP project?',   'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Project timelines depend on the complexity and scope of your PHP project. Timelines are discussed during the project planning phase to ensure alignment with your expectations.' ) ),
				array( '@type' => 'Question', 'name' => 'Will I get my source code?',                               'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Yes, at TechnBrains, transparency is key. Upon project completion, you will receive the source code for your PHP application.' ) ),
				array( '@type' => 'Question', 'name' => 'How can I choose the right PHP development company?',      'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Choosing the right PHP web development company involves evaluating expertise, portfolio, and client reviews. Look for a company with a proven track record in PHP software development and positive client testimonials.' ) ),
			),
		),
	),
	'mock_data'  => array(
		'main_banner'         => array(
			'head_text'     => 'Custom PHP Development Services',
			'content'       => 'At TechnBrains, we excel as a PHP development company specializing in crafting dynamic, database-driven, and high-performance web applications. Our approach blends Agile methodologies with customized PHP development, propelling over 200 businesses to innovation and success in the digital realm.',
			'img_src'       => '/stack/php/php-banner.png',
			'img_width'     => 691,
			'img_height'    => 794,
			'img_alt'       => 'php-banner',
			'btn_link'      => '/hire-php-developer',
			'btn_link_text' => 'Learn More',
			'popup_text'    => 'GET A FREE QUOTE',
		),
		'dedicated_lang_desc' => array(
			'para_html' => 'PHP is a programming language renowned for its flexibility and scalability in executing complex functions. Whether you seek a <span>custom PHP solution</span> or a robust enterprise solution, TechnBrains, your trusted PHP development company, nurtures your growth, ensuring a competitive market edge.<br /><br />Our expertise spans custom PHP web apps, from dynamic e-learning platforms to multilingual e-commerce sites and feature-rich business applications. Backed by a wealth of industry knowledge and the technical prowess of our PHP developers, we stand at the forefront of <span>delivering exceptional results.</span>',
		),
		'language_services'   => array(
			'head_text' => 'PHP Development Services',
			'para_text' => 'From dynamic websites to custom applications, our PHP development services cater to diverse needs.',
			'btn_text'  => 'Hire PHP GEEKS NOW!',
			'anchor'    => true,
			'btn_url'   => '/hire-php-developer',
			'listing'   => array(
				array( 'img_src' => '/stack/php/app-dev.png',    'width' => '80', 'height' => '80', 'alt' => 'app-dev',   'list_head' => 'Custom PHP Web Development',            'list_para' => 'Tailor-made PHP web development services tailored to business requirements, crafting distinctive, database-driven websites for optimal performance.' ),
				array( 'img_src' => '/stack/php/application.png','width' => '80', 'height' => '80', 'alt' => 'app',       'list_head' => 'PHP Full-Stack Development',             'list_para' => 'Holistic PHP development services covering customized front-end and back-end application development for businesses.' ),
				array( 'img_src' => '/stack/php/web-dev.png',    'width' => '80', 'height' => '80', 'alt' => 'web-dev',   'list_head' => 'PHP API Development',                   'list_para' => 'Securely enhance web application functionality with PHP API development, integrating seamlessly with third-party systems and devices.' ),
				array( 'img_src' => '/stack/php/app-des.png',    'width' => '80', 'height' => '80', 'alt' => 'app-des',   'list_head' => 'Advanced PHP Framework Development',    'list_para' => 'Create web applications using cutting-edge PHP frameworks like Laravel and CodeIgniter, ensuring flexibility and scalability.' ),
				array( 'img_src' => '/stack/php/back.png',       'width' => '80', 'height' => '80', 'alt' => 'back',      'list_head' => 'PHP CMS/Platforms Development',          'list_para' => 'Utilize PHP and MySQL for CMS website development, constructing dynamic, database-driven websites.' ),
				array( 'img_src' => '/stack/php/mantain.png',    'width' => '80', 'height' => '80', 'alt' => 'mantain',   'list_head' => 'Custom PHP Back-End & Web Services',     'list_para' => 'Develop secure back-end frameworks with PHP technology, supporting the building, deployment, and running of applications and web services.' ),
				array( 'img_src' => '/stack/php/team.png',       'width' => '80', 'height' => '80', 'alt' => 'team',      'list_head' => 'Custom CRM, ERP & Portal Development',   'list_para' => 'Craft CRM, ERP, and portal solutions using PHP, meeting clients\' evolving business needs effectively.' ),
				array( 'img_src' => '/stack/php/integrate.png',  'width' => '80', 'height' => '80', 'alt' => 'integrate', 'list_head' => 'PHP Website Support & Maintenance',      'list_para' => 'Comprehensive support and maintenance services ensure the seamless performance of PHP websites and applications.' ),
				array( 'img_src' => '/stack/php/php.png',        'width' => '80', 'height' => '80', 'alt' => 'php',       'list_head' => 'PHP Web App Upgradation & Migration',    'list_para' => 'A full-stack PHP web development company offering website migration services, including performance tuning upgrades and application optimization.' ),
			),
		),
		'proposal'            => array(
			'head_html' => '<h2>Have an idea for Web Development? Let our PHP Development Services shape your vision!</h2>',
			'btn_text'  => 'Get Quote',
			'anchor'    => false,
		),
		'dev_process'         => array(
			'main_title' => 'Our PHP development expertise.',
			'lang_title' => 'PHP Frameworks',
			'lang_para'  => 'The team at TechnBrains, a leading PHP web development company, is poised not only to meet but exceed your digital aspirations. Our seasoned PHP developers specialize in a diverse array of frameworks, each carefully chosen to enhance the development journey.',
			'listing'    => array(
				array( 'img_src' => '/stack/php/laravel.png',     'title' => 'Laravel',     'para' => 'Recognized for its elegant syntax and developer-friendly features, Laravel stands as a cornerstone in our toolkit. Its capabilities empower us to sculpt dynamic, scalable, and visually appealing solutions in the realm of PHP web development.' ),
				array( 'img_src' => '/stack/php/sf.png',          'title' => 'Symfony',     'para' => 'As advocates for modularity and seamless integration, our team utilizes Symfony to craft solutions that not only meet but exceed expectations. Symfony\'s versatility aligns seamlessly with our commitment to delivering efficient and maintainable PHP development services.' ),
				array( 'img_src' => '/stack/php/codeigniter.png', 'title' => 'CodeIgniter', 'para' => 'Speed and agility define CodeIgniter, making it an invaluable asset in our arsenal. Rapid development is at the forefront, allowing us to deliver solutions that are both feature-rich and resilient within our PHP web development company offerings.' ),
				array( 'img_src' => '/stack/php/yii.png',         'title' => 'Yii',         'para' => 'Famed for its performance and versatility, Yii has become a trusted ally in our pursuit of scalable and high-performing solutions. As a PHP development company, we leverage Yii to navigate the intricacies of diverse projects seamlessly.' ),
				array( 'img_src' => '/stack/php/cake.png',        'title' => 'CakePHP',     'para' => 'With its emphasis on convention over configuration, CakePHP emerges as a reliable framework for rapid development. It aligns perfectly with our commitment to delivering swift and efficient solutions within the realm of PHP application development.' ),
				array( 'img_src' => '/stack/php/zend.png',        'title' => 'Zend',        'para' => 'Flexibility and extensibility define Zend, making it a natural choice to infuse robustness into our custom PHP development projects. As we delve into projects requiring scalability, Zend remains a stalwart companion.' ),
				array( 'img_src' => '/stack/php/laravel.png',     'title' => 'Laravel',     'para' => 'Recognized for its elegant syntax and developer-friendly features, Laravel stands as a cornerstone in our toolkit. Its capabilities empower us to sculpt dynamic, scalable solutions in the realm of PHP web development.' ),
				array( 'img_src' => '/stack/php/sf.png',          'title' => 'Symfony',     'para' => 'Symfony\'s versatility aligns seamlessly with our commitment to delivering efficient and maintainable PHP development services for our clients worldwide.' ),
				array( 'img_src' => '/stack/php/codeigniter.png', 'title' => 'CodeIgniter', 'para' => 'Speed and agility define CodeIgniter, making it an invaluable asset in our arsenal for rapid feature-rich solutions.' ),
				array( 'img_src' => '/stack/php/yii.png',         'title' => 'Yii',         'para' => 'Famed for its performance and versatility, Yii has become a trusted ally in our pursuit of scalable solutions.' ),
				array( 'img_src' => '/stack/php/cake.png',        'title' => 'CakePHP',     'para' => 'CakePHP emerges as a reliable framework for rapid development with convention over configuration approach.' ),
				array( 'img_src' => '/stack/php/zend.png',        'title' => 'Zend',        'para' => 'Flexibility and extensibility define Zend, making it a natural choice for robustness and long-term viability.' ),
			),
		),
		'key_things'          => array(
			'sub_title' => 'Explore the essentials of PHP development',
			'title'     => 'Key Things To Know About PHP Web Development',
			'listing'   => array(
				array( 'tab_title' => 'Benefits of Using PHP',           'tab_content' => '<p>1. Versatile PHP Web Development ensures dynamic, interactive, and scalable websites. 2. Expert Guidance from PHP Development Company guarantees access to expert guidance. 3. Holistic PHP Web Development Company provides a comprehensive approach from conceptualization to deployment. 4. Comprehensive PHP Development Services covers everything from website development to application creation. 5. Tailored Custom PHP Development allows businesses to tailor solutions to their specific needs.</p>' ),
				array( 'tab_title' => 'Main Uses of PHP',                'tab_content' => '<h4>Web Development:</h4><p>PHP is predominantly used for server-side scripting in web development, creating dynamic, interactive websites.</p><h4>Building Content Management Systems (CMS):</h4><p>PHP is widely employed in creating CMS platforms like WordPress and Joomla.</p><h4>E-commerce Development:</h4><p>PHP plays a vital role in e-commerce websites and applications.</p><h4>Collaboration with Databases:</h4><p>PHP seamlessly integrates with databases, making it preferred for database-driven applications.</p>' ),
				array( 'tab_title' => 'Advanced PHP Applications',       'tab_content' => '<p>1. SaaS and Product Development. 2. eCommerce Stores: Robust and feature-rich PHP-powered online stores. 3. Hospitality Solution. 4. Crowdfunding Portal Development. 5. Real Estate Portal. 6. Healthcare Application. 7. Education and eLearning Solution. 8. Social Networking Portal. 9. Corporate CMS Websites. 10. Marketplace Development.</p>' ),
			),
		),
		'hiring'              => array(
			'lang_title' => 'PHP App Development Company',
			'hire_title' => 'Hiring Models for Business Success',
			'para_text'  => 'Take your business to new heights with our top-notch developers and flexible hiring models. Choose between monthly or fixed-priced arrangements to suit your needs. Don\'t let staffing challenges hold you back - partner with us for success.',
			'listing'    => array(
				array( 'key' => 'tab-1', 'title' => 'Hire Team',                     'tab_points' => array( array('text'=>'Initiate the process with your requirements, followed by our team proposition.'), array('text'=>'Ensure the team aligns perfectly with your project needs before finalizing the dedicated team.') ) ),
				array( 'key' => 'tab-1', 'title' => 'Project Development Lifecycle', 'tab_points' => array( array('text'=>'Agile and Lean Software Development'), array('text'=>'Project Milestones & Bi-Weekly Sprint Designs'), array('text'=>'Iterative Development and Feedback') ) ),
				array( 'key' => 'tab-1', 'title' => 'Project Delivery Excellence',   'tab_points' => array( array('text'=>'Cloud and DevOps Integration'), array('text'=>'Manual/Automated Testing'), array('text'=>'Reliable and Flexible Delivery') ) ),
				array( 'key' => 'tab-2', 'title' => 'Project Requirements',          'tab_points' => array( array('text'=>'Requirement gathering and gap analysis'), array('text'=>'Time and cost estimation'), array('text'=>'Project agreement signing') ) ),
				array( 'key' => 'tab-2', 'title' => 'Project Development',           'tab_points' => array( array('text'=>'Agile and Lean Software Development'), array('text'=>'Project Milestones & Bi-Weekly Sprint Designs'), array('text'=>'Iterative Development and Feedback') ) ),
				array( 'key' => 'tab-2', 'title' => 'Project Delivery',              'tab_points' => array( array('text'=>'Manual/Automated Testing'), array('text'=>'Reliable and Flexible Delivery') ) ),
			),
		),
		'stack_new_box'       => array(
			'subtitle' => 'Redefine your app\'s visual appeal with TechnBrains',
			'title'    => 'PHP Frameworks and Libraries We Use',
			'para'     => '',
			'listing'  => array(
				array( 'tab_title' => 'Framework & Libraries',    'data_list' => array( array('title'=>'Laravel'), array('title'=>'Lumen'), array('title'=>'Symfony Codeigniter'), array('title'=>'Yii'), array('title'=>'Drupal') ) ),
				array( 'tab_title' => 'Project Management Tools', 'data_list' => array( array('title'=>'Jira'), array('title'=>'Trello'), array('title'=>'Microsoft Team'), array('title'=>'Slack') ) ),
				array( 'tab_title' => 'Caching',                  'data_list' => array( array('title'=>'Memcached'), array('title'=>'Redis') ) ),
				array( 'tab_title' => 'Front End',                'data_list' => array( array('title'=>'React'), array('title'=>'Vue'), array('title'=>'Bootstrap'), array('title'=>'Angular'), array('title'=>'jQuery') ) ),
				array( 'tab_title' => 'Cloud & DevOps',           'data_list' => array( array('title'=>'AWS'), array('title'=>'Azure'), array('title'=>'Azure Google Cloud'), array('title'=>'Docker'), array('title'=>'Kubernetes'), array('title'=>'Terraform Jenkins') ) ),
				array( 'tab_title' => 'Packages',                 'data_list' => array( array('title'=>'Magento'), array('title'=>'Wordpress'), array('title'=>'Moodle'), array('title'=>'Shopify'), array('title'=>'Drupal') ) ),
				array( 'tab_title' => 'Database',                 'data_list' => array( array('title'=>'SQL Server'), array('title'=>'PostgreSQL'), array('title'=>'MySQL'), array('title'=>'MongoDB'), array('title'=>'Azure SQL Amazon RDS'), array('title'=>'Oracle'), array('title'=>'Cassandra'), array('title'=>'Elasticsearch'), array('title'=>'Dynamo') ) ),
				array( 'tab_title' => 'eCommerce',                'data_list' => array( array('title'=>'Magento'), array('title'=>'Shopify') ) ),
				array( 'tab_title' => 'Testing',                  'data_list' => array( array('title'=>'Selenium'), array('title'=>'Postman'), array('title'=>'BrowserStack'), array('title'=>'Test Rail OWASP ZAP'), array('title'=>'Katalon Test Studio Apache JMeter') ) ),
			),
		),
		'faqs'                => array(
			'head_text' => 'Things you might want to know',
			'faq_image' => false,
			'listing'   => array(
				array( 'faqhead' => 'How does outsourcing to a PHP development company work?',  'faqbody' => 'Outsourcing to a PHP development company involves collaborating with a specialized team that provides a range of services, including PHP web development, custom PHP development, and more.' ),
				array( 'faqhead' => 'What is a scripting language?',                            'faqbody' => 'A scripting language, like PHP, is a type of programming language designed for scripting tasks, automating processes, and instructing a computer to perform specific functions.' ),
				array( 'faqhead' => 'What are the two types of scripting languages?',           'faqbody' => 'The two main types are server-side scripting languages and client-side scripting languages. PHP is server-side while JavaScript is client-side.' ),
				array( 'faqhead' => 'What kind of applications can you build using PHP?',       'faqbody' => 'We specialize in dynamic websites, eCommerce platforms, healthcare applications, social networking portals, and more as a comprehensive PHP development company.' ),
				array( 'faqhead' => 'What is the difference between PHP and JavaScript?',       'faqbody' => 'PHP is a server-side scripting language for server operations and dynamic content generation. JavaScript is a client-side scripting language that executes within the user\'s browser.' ),
				array( 'faqhead' => 'Will TechnBrains do custom development work?',             'faqbody' => 'Custom development is at the core of our offerings. As a leading PHP development company, we excel in tailoring solutions to meet your unique requirements.' ),
				array( 'faqhead' => 'How much does it cost to build a PHP app?',                'faqbody' => 'The cost varies based on project complexity, features, and scope. We offer transparent discussions to provide accurate cost estimates.' ),
				array( 'faqhead' => 'How much time will it take to complete my PHP project?',   'faqbody' => 'Project timelines depend on the complexity and scope and are discussed during the planning phase to ensure alignment with your expectations.' ),
				array( 'faqhead' => 'Will I get my source code?',                               'faqbody' => 'Yes, at TechnBrains, transparency is key. Upon project completion, you will receive the source code for your PHP application.' ),
				array( 'faqhead' => 'How can I choose the right PHP development company?',      'faqbody' => 'Evaluate expertise, portfolio, and client reviews. Look for a company with a proven track record in PHP software development and positive client testimonials.' ),
			),
		),
	),
	'components' => array(
		array( 'name' => 'main-banner',         'modifier_class' => '' ),
		array( 'name' => 'dedicated-lang-desc', 'modifier_class' => '' ),
		array( 'name' => 'language-services',   'modifier_class' => '' ),
		array( 'name' => 'proposal',            'modifier_class' => '' ),
		array( 'name' => 'development-process', 'modifier_class' => '' ),
		array( 'name' => 'key-things',          'modifier_class' => '' ),
		array( 'name' => 'hiring',              'modifier_class' => '' ),
		array( 'name' => 'stack-new-box',       'modifier_class' => 'angular-stack' ),
		array( 'name' => 'testimonials',        'modifier_class' => '' ),
		array( 'name' => 'main-faqs',           'modifier_class' => 'gray-bg' ),
	),
);
