<?php
return array(
	'schemas'   => array(
		array(
			'@context'   => 'https://schema.org',
			'@type'      => 'FAQPage',
			'mainEntity' => array(
				array( '@type' => 'Question', 'name' => 'How fast can engineers start?', 'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Pre-vetted engineers typically onboard within 1–2 weeks, ensuring rapid integration into your team.' ) ),
				array( '@type' => 'Question', 'name' => 'Is there time-zone overlap?', 'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Yes. Our nearshore model provides optimal overlap to align with your sprints and communication needs.' ) ),
				array( '@type' => 'Question', 'name' => 'How do you ensure senior-level talent?', 'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'All candidates undergo technical competency testing, cultural fit assessment, and reference verification before onboarding.' ) ),
				array( '@type' => 'Question', 'name' => 'Can startups use staff augmentation?', 'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Absolutely. Our flexible model helps startups scale quickly while controlling costs.' ) ),
				array( '@type' => 'Question', 'name' => 'How do you prevent junior stacking?', 'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'We provide experienced, senior engineers to maintain your technical standards and project quality.' ) ),
				array( '@type' => 'Question', 'name' => 'How is compliance and IP protected?', 'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'NDAs, IP protection protocols, and industry-compliant standards (HIPAA, GDPR, SOC 2) are enforced for all teams.' ) ),
				array( '@type' => 'Question', 'name' => 'What about costs and contract flexibility?', 'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'Flexible engagement models (T&M, outcome-based, or dedicated teams) ensure alignment with project budgets and timelines.' ) ),
				array( '@type' => 'Question', 'name' => 'How quickly can augmented engineers integrate into our team?', 'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'E-vetted engineers typically onboard within 1–2 weeks, ensuring they can contribute and align with your team\'s workflow rapidly.' ) ),
				array( '@type' => 'Question', 'name' => 'What happens if the engineers don\'t meet our expectations?', 'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'We offer a satisfaction guarantee. If the talent doesn\'t meet your expectations, we\'ll provide a replacement at no additional cost to ensure your project stays on track.' ) ),
				array( '@type' => 'Question', 'name' => 'Where can I find reliable IT staff augmentation agencies?', 'acceptedAnswer' => array( '@type' => 'Answer', 'text' => 'You can find reputable IT staff augmentation agencies through industry-specific platforms like Clutch, Upwork, or GoodFirms. Additionally, referrals from other tech startups or enterprises, along with networking in professional groups or events, can help you identify trusted partners who specialize in integrating senior engineers into development teams.' ) ),
			),
		),
	),
	'mock_data' => array(
		'banner' => array(
    'title_html'      => 'IT Staff Augmentation Services That Strengthen Your Existing Team',
    'para'            => 'Add pre-vetted developers directly into your sprints, workflows, and architecture, without rebuilding your hiring pipeline or slowing delivery.',
    'bg_image'        => '/revamp/banner/staff-banner-two.webp',
    'btn_text'        => 'View Case Studies',
    'btn_link'        => '/case-studies',
    'btn_classes'     => '',
    'btn_two_text'    => 'Contact Us',
    'btn_two_link'    => '/contact-us',
    'btn_two_classes' => 'btnTransparent',
),
		'trusted_by'   => array(
			'title'   => 'Brands That Trust Us',
			'para'    => 'Embedded engineers who operate like your own, same standards, same tools, shared outcomes.',
			'listing' => array(
				array( 'img_src' => '/revamp/home/t-7.png', 'width' => '124', 'height' => '40' ),
				array( 'img_src' => '/revamp/home/t-8.png', 'width' => '114', 'height' => '24' ),
				array( 'img_src' => '/revamp/home/t-9.png', 'width' => '107', 'height' => '36' ),
				array( 'img_src' => '/revamp/home/t-4.png', 'width' => '109', 'height' => '43' ),
				array( 'img_src' => '/revamp/home/t-5.png', 'width' => '142', 'height' => '42' ),
				array( 'img_src' => '/revamp/home/t-6.png', 'width' => '101', 'height' => '31' ),
			),
		),
		'choose_results' => array(
			'title'      => "Choose results,\nnot promises.",
			'para'       => 'With recognition from Clutch, TrustPilot, and GoodFirms, you can trust that the right provider is here to help you achieve your goals.',
			'sub_text'   => 'Your success is reflected in the outcomes',
			'side_items' => array(
				array( 'count' => '150+',  'label' => 'Software projects delivered' ),
				array( 'count' => '4.7/5', 'label' => 'Rating from 17+ verified reviews' ),
				array( 'count' => '90%',   'label' => 'Long-term client retention' ),
			),
		),
		'teams_choose' => array(
    'title'    => 'Why Teams Choose Our IT Staff Augmentation Services',
    'para'     => 'Engineering leaders turn to staff augmentation when internal hiring cannot keep pace with innovation and delivery demands. If you are evaluating how to choose the right IT staff augmentation company, here is why teams consistently choose TechnBrains:',
    'img_src'  => '/revamp/staff-aug/teamChoose.webp',
    'btn_text' => 'Schedule a Call',
    'listing'  => array(
        array( 'item' => 'Fast Access to Senior Talent',  'para' => 'Skip lengthy recruitment cycles and quickly onboard experienced engineers who are ready to contribute from day one.' ),
        array( 'item' => 'No Junior Stacking',            'para' => 'Work only with pre-vetted, senior-level engineers who meet strict technical and performance standards.' ),
        array( 'item' => 'Better Time-Zone Alignment',    'para' => 'Collaborate smoothly with nearshore and aligned teams for real-time communication and faster sprint execution.' ),
        array( 'item' => 'Compliance-Ready Expertise',    'para' => 'Ensure secure, regulation-compliant development aligned with standards like HIPAA, PCI-DSS, and fintech regulations.' ),
        array( 'item' => 'Senior Engineers, Not Just Resources', 'para' => 'Gain true engineering expertise, not task fillers, with professionals who match your technical and product expectations.' ),
    ),
),
		'scale_with_experts' => array(
    'title'    => 'Hire Vetted Engineering Talent for Team Scaling',
    'para'     => 'Access specialized, on-demand IT experts for your enterprise-level initiatives, accelerating your development without compromising quality. With IT staff augmentation services tailored to your needs, you can get the expertise required to keep your projects on track and moving forward seamlessly.',
    'btn_text' => 'Hire Vetted Engineers',
    'listing'  => array(
        array( 'icon' => '/revamp/common/frontend.png',      'title' => 'Frontend Engineers',        'para' => 'React, Vue, AngularJS, ReactJS, JavaScript' ),
        array( 'icon' => '/revamp/common/backend.png',       'title' => 'Backend Engineers',         'para' => 'Node.js, .NET, Python, Java, Laravel, PHP' ),
        array( 'icon' => '/revamp/common/mobile.png',        'title' => 'Mobile Developers',         'para' => 'iOS, Android, Flutter, React Native' ),
        array( 'icon' => '/revamp/common/qa.png',            'title' => 'QA Engineers',              'para' => 'Manual & Automation Testing' ),
        array( 'icon' => '/revamp/common/devops.png',        'title' => 'DevOps & Cloud',            'para' => 'AWS, Azure, GCP' ),
        array( 'icon' => '/revamp/common/ai.png',            'title' => 'AI & ML Engineer',          'para' => 'Machine learning, deep learning, MLOps' ),
        array( 'icon' => '/revamp/common/solution.png',      'title' => 'Solution Architects',       'para' => 'System design, scalable architecture, enterprise solutions' ),
        array( 'icon' => '/revamp/common/cybersecurity.png', 'title' => 'Cybersecurity Specialists', 'para' => 'Ethical hacking, penetration testing, SOC analysts' ),
    ),
),
		'case_studies' => array(
			'heading' => 'Augmented Teams, Real Business Impact',
			'para'    => 'See how our engineers help teams overcome skill gaps, hit deadlines, and deliver real business results across industries:',
		),
		'enterprise_level' => array(
    'title'    => 'How Enterprise-Level Projects Are Delivered Using IT Staff Augmentation Services',
    'para'     => 'IT staff augmentation helps teams close skill gaps, speed up delivery, and meet critical project deadlines without changing existing workflows. Senior engineers work directly inside your team, helping you move faster, stay aligned, and deliver complex products with better control and consistency.',
    'btn_text' => 'Schedule a Call',
    'bg_image' => '/revamp/staff-aug/enterpriseLevel.webp',
    'listing'  => array(
        array( 'item' => 'Accelerate Stalled Sprints',      'para' => 'When progress slows down, senior engineers join your team to restore speed and keep sprints on track.' ),
        array( 'item' => 'Fill Skill Gaps',                 'para' => 'Get access to AI/ML, mobile, cloud, backend, and cybersecurity engineers based on what your project needs.' ),
        array( 'item' => 'Launch New Products Faster',      'para' => 'Build MVPs, prototypes, and product features quickly with experienced developers working alongside your team.' ),
        array( 'item' => 'Reduce Vendor Dependency',        'para' => 'Move away from unreliable outsourcing setups and work with engineers who align with your delivery process.' ),
        array( 'item' => 'Support Enterprise Modernization','para' => 'Update and improve legacy systems while keeping your current operations stable.' ),
        array( 'item' => 'Handle Peak Workloads',           'para' => 'Add engineering capacity when demand increases, without slowing down release cycles.' ),
    ),
),
		'why_staff_aug' => array(
    'heading'    => 'Why Staff Augmentation Makes More Sense Than Hiring or Outsourcing',
    'para'       => 'Traditional hiring is slow, and outsourcing can reduce visibility and control. IT staff augmentation adds senior engineers directly to your team to fill skill gaps, speed up delivery, and maintain full ownership of your roadmap. Unlike fully managed models such as dedicated development teams or software outsourcing, staff augmentation keeps engineers working inside your existing workflows and delivery processes.',
    'subheading' => 'Benefits and Challenges of IT Staff Augmentation Services',
    'btn_text'   => 'Discuss Your Project Requirements',
    'benefits'   => array(
        'list_title' => 'Benefits',
        'items'      => array(
            array( 'title' => 'Speed to Execution',           'text' => 'Add senior engineers in weeks instead of months, without slowing down roadmaps or changing delivery workflows.' ),
            array( 'title' => 'Flexible Cost Structure',      'text' => 'Scale engineering capacity as needed without long-term payroll commitments, hiring delays, or rigid contract structures.' ),
            array( 'title' => 'Full Control Over Delivery',   'text' => 'Engineers work inside your repos, pipelines, and sprint cycles, while your team retains ownership of architecture, backlog, and releases.' ),
            array( 'title' => 'Lower Delivery Risk',          'text' => 'Adjust or scale engagements based on project needs without dependency lock-in or disruption to ongoing work.' ),
            array( 'title' => 'Works Within Organizational Limits', 'text' => 'Keep critical work moving even during hiring freezes, headcount restrictions, or tight budget cycles.' ),
            array( 'title' => 'Consistent Engineering Quality','text' => 'Extend your team with senior, pre-vetted engineers without reducing standards or introducing unnecessary technical debt.' ),
        ),
    ),
    'challenges' => array(
        'list_title' => 'Challenges',
        'items'      => array(
            array( 'title' => 'Requires Clear Technical Ownership',  'text' => 'Staff augmentation works best when your internal team defines product direction and architecture decisions.' ),
            array( 'title' => 'Onboarding Needs Structure',          'text' => 'Access, documentation, and workflow clarity help engineers contribute faster, even though ramp-up is still quicker than hiring or outsourcing.' ),
            array( 'title' => 'Not a Replacement for Core Hiring',   'text' => 'Best suited for scaling delivery and filling gaps while permanent hiring continues in parallel.' ),
            array( 'title' => 'Partner Quality Impacts Results',     'text' => 'Outcomes depend on proper vetting, delivery management, and ongoing performance oversight.' ),
        ),
    ),
),
		'leading_tech_partner' => array(
    'title'   => 'Recognized as a Leading Tech Partner',
    'para'    => 'Trusted by engineering teams to support delivery, close skill gaps, and keep complex projects moving without delays. As an IT staff augmentation company, we help teams stay on track and meet critical deadlines with the right talent in place.',
    'listing' => array(
        array( 'img_src' => '/revamp/common/inc-500.png' ),
        array( 'img_src' => '/revamp/common/clutch.png' ),
        array( 'img_src' => '/revamp/common/horizon-silver.png' ),
        array( 'img_src' => '/revamp/common/top-dev.png' ),
        array( 'img_src' => '/revamp/common/horizon-gold.png' ),
        array( 'img_src' => '/revamp/common/top-software.png' ),
    ),
),
		'streamlined' => array(
			'title'    => 'Accelerate Delivery with a Streamlined Staff Augmentation Approach',
			'para'     => 'TechnBrains becomes an extension of your engineering team, integrating senior talent that aligns with your existing methods. With IT staff augmentation services and an agile staffing approach, your team scales efficiently without compromising quality.',
			'btn_text' => 'Boost My Velocity',
			'listing'  => array(
				array(
					'heading'   => 'Align on Scope & Standards',
					'item_list' => array(
						array( 'item' => 'Understand your roadmap, backlog, and velocity targets' ),
						array( 'item' => 'Define communication rhythm, review cycles, and success metrics' ),
					),
				),
				array(
					'heading'   => 'Integrate Into Your Workflow',
					'item_list' => array(
						array( 'item' => 'Join your tools (Jira, Slack, GitHub)' ),
						array( 'item' => 'Match your sprint cycles and documentation standards' ),
						array( 'item' => 'Maintain full transparency with daily updates and shared ownership' ),
						array( 'item' => 'Work as part of your internal team with pre-vetted talent' ),
					),
				),
				array(
					'heading'   => 'Deliver With Accountability',
					'item_list' => array(
						array( 'item' => 'Time-to-first-PR in Week 1' ),
						array( 'item' => 'Track sprint accuracy and review lag' ),
						array( 'item' => 'Maintain the same engineering bar as your internal teams' ),
					),
				),
			),
		),
		'cta_two' => array(
			'title'           => '<span>Build Faster. Scale Confidently.</span><br> Stay in Control.',
			'para'            => 'Maintain full control over your workflow while scaling your team quickly and efficiently with TechnBrains.',
			'btn_text'        => 'Start a Trial Sprint',
			'btn_link'        => '',
			'btn_two_text'    => 'Book a Free Consultation',
			'btn_two_link'    => '',
			'bg_image'        => '/revamp/cta/cta-bg.webp',
			'bottom_btn_text' => 'See Case Studies',
			'bottom_btn_link' => '/portfolio',
		),
		'industry_slider' => array(
			'title'   => 'Specialized IT Teams That Understand Your Industry Challenges',
			'para'    => 'Complex and highly regulated industries need engineers who know the rules, workflows, and risks. TechnBrains provides on-demand IT experts who help teams deliver faster, stay compliant, and solve problems specific to their domain.',
			'listing' => array(
				array( 'title' => 'Logistic',    'paragraph' => 'Automation, route optimization, fleet tracking',                     'bg_image' => '/revamp/industrySlider/logistic.webp',    'link' => '/industries/logistics-software-development' ),
				array( 'title' => 'Healthcare',  'paragraph' => 'HIPAA-compliant apps, EMRs, telehealth platforms',                   'bg_image' => '/revamp/industrySlider/healthcare.webp',  'link' => '/industries/healthcare-app-development' ),
				array( 'title' => 'Fintech',     'paragraph' => 'KYC systems, payments, anti-fraud, compliance-first solutions',      'bg_image' => '/revamp/industrySlider/fintech.webp',     'link' => '/industries/fintech-software-development' ),
				array( 'title' => 'Retail',      'paragraph' => 'Omnichannel commerce, personalization engines',                      'bg_image' => '/revamp/industrySlider/retail.webp',      'link' => '/industries/retail-app-development' ),
				array( 'title' => 'Real Estate', 'paragraph' => 'Property platforms, tenant management, listing engines',             'bg_image' => '/revamp/industrySlider/realestate.webp',  'link' => '/industries/real-estate-app-development' ),
				array( 'title' => 'Education',   'paragraph' => 'LMS integrations, learning platforms',                               'bg_image' => '/revamp/industrySlider/education.webp',   'link' => '/industries/education-app-development' ),
				array( 'title' => 'Automotive',  'paragraph' => 'Dealership CRM, inventory management, digital showroom platforms.',  'bg_image' => '/revamp/industrySlider/automotive.webp',  'link' => '/industries/automotive-app-development' ),
				array( 'title' => 'Energy',      'paragraph' => 'IoT monitoring, field-data apps, Microgrid Control',                 'bg_image' => '/revamp/industrySlider/energy.webp',      'link' => '/industries/energy-management-software-development' ),
			),
		),
		'faqs' => array(
    'listing' => array(
        array( 'faqhead' => 'How fast can engineers join a team?',                        'faqbody' => 'Pre-vetted engineers typically join within 1–2 weeks, depending on the required skill set and onboarding process.' ),
        array( 'faqhead' => 'Is staff augmentation better than outsourcing?',             'faqbody' => 'Staff augmentation gives businesses greater control over workflows, team collaboration, and delivery priorities compared to traditional outsourcing models. Understanding the pros and cons of staff augmentation can help organizations choose the right engagement model based on project complexity, scalability needs, and internal team structure.' ),
        array( 'faqhead' => 'Can startups use IT staff augmentation?',                    'faqbody' => 'Yes. Startups use staff augmentation to scale quickly, access senior talent, and build products without long hiring cycles or high upfront costs.' ),
        array( 'faqhead' => 'How do you ensure senior-level engineers?',                  'faqbody' => 'All engineers go through technical evaluation, project experience review, and communication assessment before being assigned to any project.' ),
        array( 'faqhead' => 'How do you avoid junior-level talent in teams?',             'faqbody' => 'Only pre-vetted engineers with proven project experience are included, ensuring teams stay senior-heavy and delivery-focused.' ),
        array( 'faqhead' => 'Do augmented engineers work like in-house employees?',       'faqbody' => 'Yes. They join your tools, sprint cycles, repositories, and communication channels as part of your internal team structure.' ),
        array( 'faqhead' => 'What skills can be added through staff augmentation?',       'faqbody' => 'Teams can scale across frontend, backend, mobile, DevOps, cloud, AI/ML, QA, and cybersecurity roles based on project needs.' ),
        array( 'faqhead' => 'Is IT staff augmentation suitable for long-term projects?',  'faqbody' => 'Yes. It works for both short-term scaling needs and long-term product development when continuous expertise is required.' ),
    ),
),
	),
	'components' => array(
		array( 'name' => 'banner',                  'modifier_class' => '' ),
		array( 'name' => 'trusted-by',              'modifier_class' => '' ),
		array( 'name' => 'choose-results',          'modifier_class' => '' ),
		array( 'name' => 'teams-choose',            'modifier_class' => '' ),
		array( 'name' => 'scale-with-experts',      'modifier_class' => '' ),
		array( 'name' => 'case-studies-tabs-two',   'modifier_class' => '' ),
		array( 'name' => 'enterprise-level',        'modifier_class' => '' ),
		array( 'name' => 'why-staff-augmentation',  'modifier_class' => '' ),
		array( 'name' => 'leading-tech-partner',    'modifier_class' => '' ),
		array( 'name' => 'streamlined',             'modifier_class' => '' ),
		array( 'name' => 'cta-two',                 'modifier_class' => '' ),
		array( 'name' => 'industry-slider',         'modifier_class' => '' ),
		array( 'name' => 'revamp-faqs',             'modifier_class' => '' ),
	),
);
